package com.bitdubai.fermat_api.layer._3_platform_service.event_manager;

/**
 * Created by ciencias on 24.01.15.
 */
public enum EventType {

    DEVICE_USER_CREATED,
    DEVICE_USER_LOGGED_IN,
    DEVICE_USER_LOGGED_OUT,
    INTRA_USER_LOGGED_IN,
    INTRA_USER_LOGGED_OUT,
    INTRA_USER_CONTACT_CREATED,
    INCOMING_NETWORK_SERVICE_CONNECTION_REQUEST,

    WALLET_CREATED, 
    WALLET_WENT_ONLINE, 
    WALLET_INSTALLED, 
    BEGUN_WALLET_INSTALLATION, 
    WALLET_UNINSTALLED, 
    WALLET_CLOSED, 
    WALLET_OPENED,
    WALLET_RESOURCES_INSTALLED,
    NAVIGATION_STRUCTURE_UPDATED,
    MONEY_RECEIVED, 
    FINISHED_WALLET_INSTALLATION,

    INCOMING_CRYPTO_RECEIVED,
    INCOMING_CRYPTO_RECEPTION_CONFIRMED,
    INCOMING_CRYPTO_REVERSED,
    INCOMING_CRYPTO_IDENTIFIED,
    INCOMING_CRYPTO_IDENTIFIED_FROM_EXTRA_USER,
    INCOMING_CRYPTO_IDENTIFIED_FROM_INTRA_USER,
    INCOMING_CRYPTO_IDENTIFIED_FROM_DEVICE_USER,
    INCOMING_CRYPTO_RECEIVED_FROM_EXTRA_USER,
    INCOMING_CRYPTO_RECEIVED_FROM_INTRA_USER,
    INCOMING_CRYPTO_RECEIVED_FROM_DEVICE_USER,
    INCOMING_CRYPTO_RECEPTION_CONFIRMED_FROM_EXTRA_USER,
    INCOMING_CRYPTO_RECEPTION_CONFIRMED_FROM_INTRA_USER,
    INCOMING_CRYPTO_RECEPTION_CONFIRMED_FROM_DEVICE_USER,
    INCOMING_CRYPTO_REVERSED_FROM_EXTRA_USER,
    INCOMING_CRYPTO_REVERSED_FROM_INTRA_USER,
    INCOMING_CRYPTO_REVERSED_FROM_DEVICE_USER,

    INCOMING_MONEY_REQUEST_RECEIVED,
    OUTGOING_MONEY_REQUEST_DELIVERED,
    OUTGOING_MONEY_REQUEST_APPROVED,
    OUTGOING_MONEY_REQUEST_REJECTED,
    INCOMING_MONEY_REQUEST_APPROVED,
    INCOMING_MONEY_REQUEST_REJECTED,

    DEVICE_CONNECTIVITY_NETWORK_CHANGE,

    BITCOIN_NEW_PEER_CONNECTED,
    BITCOIN_NEW_CRYPTO_WALLET_CREATED,
    BITCOIN_CRYPTO_WALLET_LOADED,
    BITCOIN_BLOCKCHAIN_DOWNLOADED,
    BITCOIN_NEW_PEER_CONNECTED_INTRA_USER;

    }
