package com.bitdubai.fermat_api.layer._3_platform_service.event_manager;

/**
 * Created by ciencias on 24.01.15.
 */
public enum EventSource {
    USER_DEVICE_USER_PLUGIN,
    CRYPTO_NETWORK_BITCOIN_PLUGIN,
    COMMUNICATION_CLOUD_PLUGIN,
    NETWORK_SERVICE_INTRA_USER_PLUGIN,
    NETWORK_SERVICE_WALLET_RESOURCES_PLUGIN,
    NETWORK_SERVICE_WALLET_COMMUNITY_PLUGIN,
    MIDDLEWARE_APP_RUNTIME_PLUGIN,
    MIDDLEWARE_WALLET_CONTACTS_PLUGIN,
    MIDDLEWARE_WALLET_PLUGIN,
    MODULE_WALLET_MANAGER_PLUGIN,
    USER_INTRA_USER_PLUGIN, CRYPTO_ADDRESS_BOOK, 
    NETWORK_SERVICE_MONEY_REQUEST_PLUGIN, 
    MIDDLEWARE_MONEY_REQUEST_PLUGIN, 
    NETWORK_SERVICE_MONEY_PLUGIN,
    WORLD_BLOCKCHAIN_INFO_PLUGIN,
    DISCOUNT_WALLET_BASIC_WALLET_PLUGIN
    
    }
