[[fbk-01 Welcome to FERMAT]]
== Welcome to FERMAT !

=== Beyond Bitcoin: FERMAT 

((("fermat", id="ix_fbk-01-asciidoc0", range="startofrange")))((("fermat","defined")))
FERMAT is an inspired vision, a project to attain this vision, a group of pioneers of the software development industry working on it, a community supporting the core idea and providing the environment, and the whole world of potential users who will profit and be served by this. 
FERMAT's vision is based on the huge potential of the blockchain transaction technology underlying the first sucessfully implemented cryptocurrency: Bitcoin. The undeniable goal of Bitcoin's crytographic based electronic signature protocol that builds a distributed public ledger of peer-to-peer electronic transactions opens the door to a new paradigma in economics, computer science, financial operations, and world-wide commerce. Sakamoto's invention makes possible to unveil the world of financial transactions, to get rid of the necessity of trust into a third party institution or central goverments, to make money a secure thing, and transactions transparent and effortless, giving back the absolute control to the money's owner. The cryptocurrency scheme encourages us to adopt a radical new point of view on money and the concept fo value itself and its transport, so radical, that it will take us some time and effort to really grasp it, because it leads to unconditionally honoring and empowering of each individual. 
FERMAT as a project is also a big challenge to the open source software industry because it firmly believes that the comunnity has much more talent and intelligent collectively than isolated individuals, and the project is inscribed in the wolrd-wide cryptoindustry ecosystem with the conviction of laying the seeds of a global collaborative endeavourw ith a firm call to commited collaboration from peers and colleagues.
FERMAT from its conception is addressed to pioneers, and we have already engaged a solid core of software developers that is working in shaping the first version of the platform to be soon released.
  
FERMAT is, technically speaking , an Open Source P2P (Peer-to-Peer) System built on a Plug-in Architecture running on end-user's devices. The first goal is to get very close to the end user offering and easy way of coming onboard the crytocurrency world by means of and insutitively easy to access cryptocurrency Wallet. At the same time, the open source plug-in platform allow any skilled actor in the community to jump in and develop applications and offering services with different abstractin levels and addressing a wide range of segmented markets. In fact, FERMAT as whole sets a common ground, a kind of "Master Plan" for developing wallets, wallet services, p2p network services and all kind of future develpments based in blockchain tech, using the existent global talent and intelligence that the community already has and collaborating with very intense feedback in expanding this technology to reach rapidily end user's mass adoption, giving all the participants in the different sectors a sense of trust, safety and equity, and the corresponding right to become a revenue for each one's contribution and effort.
Instead of begginning a new project in this industry completley from zero point, the clear and firm logic of FERMAT can turn it to become a new standard in the industry by giving the collective a group coherence as it had never before, and encourages to grow safely in a collaborative way.

.Challenges and opportunities: inspiration from Fermat's Last Theorem
****

((("bitcoin","precursors to"))) 
---------------------
As you may have noticed, the entire project has been named following the famous mathematical puzzle that haunted generations of mathemathicians until it was finally proven after 350 years. (if you are courious about the whole story, see http: ....    ).
It is so because this project was born when trying to solve the new questions, issues and puzzles that the genious Sakamoto's solution to an old cryptographic called , which let him consolidet the foundation of Bitcoin, the first sucessfull cryptocurrency. (for a wonderful detailed introduction to Bitcoin's world, please refer to the "must read"excellent book of Antonio Papadopoulos "Mastering Bitcoin").

The "puzzle"to solve in the emerging field of blockchain tecnology is related to finding the answers to the following questions:

* How can we isolate ordinary people from the perceived complexity? 
* How can we use the collective intelligence of the developer community? 
* How can we reuse the entire current infrastructure already in place? 
* How do we integrate legacy financial institutions in a way they feel comfortable? 
* How do we integrate merchants, retailers and brands of all sizes in a clever way?

The answers to each of these questions are addressed within the FERMAT platform.
****

=== FERMAT's Mission: 

> Empower every person in the world with the appropriate tools to save and move their money in a digital format in an efficient, secure an private way. And at the same time allow them to choose which currency to use, regardless of the place they live or where they were born.


=== What makes FERMAT different from other wallet platforms or services?

* **FERMAT is P2P.** This makes it censorship resistent and difficult to be attacked.

* **FERMAT is built with plugins.** This enables functionality to be reused and opens the door to any developer to participate.

* **FERMAT runs on end users' devices.** This enables users to hold their own money eliminating the need to trust a third party. 

* **FERMAT is inclusive.** By creating their own plugins, current industry members can integrate with FERMAT to offer their services and products to FERMAT user base. 

* **FERMAT segments the world population and offers a custom tailored solution for each segment.** Any developer can easily create niche wallets for a particular group of people. Brands can create their own wallets for their followers. All the heavy lifting is done by the FERMAT platform.

* **FERMAT guaratees plugins and wallet developers a revenue stream.** FERMAT implements an innovative business model which allows plugins and wallet developers to define a use license, and FERMAT itself enforces this license on behalf of developers. )



=== FERMAT's Principles

==== 1. FERMAT should not allow censorship.
* Open Source.
* P2P architecture. 

#### 2. FERMAT should not allow spying on their user base.


* Point to point encrypted communications.
* Geofenced P2P network enabling the shortest communication path between peers.
* Multi-technology communication layer (cloud, p2p, wifi, bluetooth, nfc, mesh, etc.).


#### 3. FERMAT should be secure and resistant to all kind of attacks.


* No centralized point to be attacked.
* Multiple identities and roles per user.
* Device Private Network (DPN) concept.
* Pocket Money concept and a Multi-Signature Vault owned by the DPN.
* Reviews and Reputation concepts. 


#### 4. FERMAT should never loose a user's funds. 


* Transaction responsability transmission protocols.
* Remote technical support by wallet and plugins developers.


#### 5. FERMAT should be usefull to each segment of the world population.


* Niche wallets concept.
* Branded wallets concept.


#### 6. FERMAT should be extensible and open to innovation.


* Plugins architecture.
* Multi dimensional layer architecture.


#### 7. FERMAT should be open and inclusive. 


* Any developer could contribute to the shared infraestructure.
* Any developer could write code for new plugins.
* Any developer could write code for new niche wallets.
* Any developer could fork an existing niche wallet to further specialize it.
* Any graphic / UX designer could provide skins to existing wallets.
* Anyone could provide language packs to existing wallets.


#### 8. Each developer should be compesated by their contribution to FERMAT.


* Micro license concept.
* Micro license structure concept.
* FERMAT automatically enforcing license agreements.
* Plugin ownership concept.
* Niche wallet ownership concept.
* Branded wallet onwnership concept.
* Master plan design comcept, wiht no overlaping functionality but shared ownership.


#### 9. FERMAT user base should be a shared asset.


* Any developer should be able to profit from the growing FERMAT user base by writing Plugins this user base could consume via the developers of the wallets they are using.
 

#### 10. FERMAT should be inclusive with crypto currency industry members. 

* Any bitcoin | crypto | blockchain established startup could write their own plugins and expose their services to both FERMAT developers and the FERMAT user base.
* Any alt-coin community could write plugins to enable their crypto currency within the FERMAT wallet ecosystem.


#### 11. FERMAT should be inclusive with the current financial system.


* Banks and financial institutions could write plugins to enable FERMAT wallets hold funds in banks and other financial institutions.

* FERMAT allows it users to move money both through public value transport networks as crypto currency networks and also thwough private or legacy financial networks.


#### 12. FERMAT should be unbanked-people friendly.


* Multiple logins per device (Device user concept)
* Crypto banking concept.


#### 13. FERMAT should be OS agnostic. 


* OSA layer concept (Operative System API).
* OS dependent UI on top of FERMAT concept.


#### 14. FERMAT should learn from its user base.


* Integrated feedback functionality.
* Voting over feature wish-lists concept.


#### 15. FERMAT should be the finacially most efficient way to move or spend the end user's money. 


* Crypto Vault for multiple wallets concept.
* Financial AI Agents concept.


#### 16. FERMAT should facilitate the regional distribution and access to crypto currencies.


* Crypto Distribution Network concept. 
* Crypto Brokers concept.



