:numbered:
== FERMAT'S Master Plan

As we firmly believe that the next decade will witness crypto currencies going mainstream and governments issuing digital currency as well, we expect paper money is going to disappear within the next 5 to 10 years. Thus a strong consumer demand for digital wallets will inevitably emerge. In order to meet this demand thousands of wallets, different in terms of not only the level of abstraction they apply (some of them showing crypto currencies while others digital fiat over crypto or even digital assets) but also with respect to their look and feel and their functionalities, should be available. Such a wide variety of wallets is indispensable owing to the diversity characterizing the world's population. Thus this is the first acknowledgment that sets the foundation of FERMAT's plan inside this global trend: to address this UNIQUENESS of each individuum and every kind of collective gathering of human beings (associations, clubs, NGO's, educational institutions, even banks, financial institutions, etc) that will adopt blockchain technology based transactions on their lives, in a similar way we have already adopted digitalised pictures, music, books, cell phones and internet as a whole.


NOTE: We have an special word for this selectivity. We call it : SEGMENTATION

On the other hand, there are many people who earn their living generating products and services at the heart of this digital world, being interconnected in an complex pattern of giving and receiving, services, money, assets, knowledge, permanently exchanging information of all kinds, weaving relationships, building a *community*. We do believe the community collectively has more talent than any of us individually. We believe it is important to build on top of services and knowledge that others took time and effort to build.


NOTE: we believe in a vision of humanity as a COLLABORATIVE LEARNING SPECIES and in an ECOSYSTEM view of a Global Integral Civilisation.

FERMAT'S Master Plan is about laying a solid foundation organized in layers and pillars, building a coherent pattern of relationships and interactions which can help to bridge the gap between the already complex world of digital systems and the end user's very specific need in a simple, easy to understand, transparent and yet very powerful way.

We believe in *decentralization* . 
With the rising of Internet and the giant proliferation of computers permanently connected , what turn "the web" nowadays into "the cloud, among the huge benefits of a myriad of services running 24 hours on-line, we have also witnessed some vulnerability of systems totally dependent on a specific server ( or net of servers) when they crashed victim of hackers attack or when they were banned or controlled by goverments or central institutions not only causing data and money loses, but also spreading an awkward feeling of mistrust and being abused.
At the contrary, a new era of distributed systems which run on a decentralized peer-to-peer network, secured by the use of cryptographic signatures is being born, turning the old systems based on a "central"server or central point of control gradually obsolete. The demand of such distributed systems is getting bigger because they are naturally safer ( ther's no central point to attack or control) and they honor the integrity of every participant and are provably fair and honest.

 
In FERMAT we believe in people with passion and commitment to attain higher purposes, who are "crazy enough" to think they can change the world. We do believe we are going to change this world and move it forward.

=== Core concepts 
==== What's behind money?
In our daily live we have accepted money as something present in almost every activity of human endeavour, and most of us use it without reflecting on its origin or its deeper meaning. Making it simple, money is an agreed mean of exchanging value. By its universal adoption it allows a flow of products and services between the different actors in a producer-consumer chain ( or better, in a "web" of commercial interactions) and following this, an exchange of the value associated with each step, rewarding each actor with a portion of the entire value, what we call "profit". During the early ages trading was made directly exchanging certain goods for other goods, then as trading was growing at scale, the necessity of unification of mass and measures lead to the rising of money representing in some way the value of what was being exchange and a relative consensus over it. Later on, with the rising of the different nations which created a certain unification under certain name, language and goverment and rules to be applied to a determined territory and its inhabitants extend the souveranity also to the issue of a national currency and the printing of "official" paper money. At the begginning the amount of paper money was guaranteed by a national reserve on gold, what was no longer needed after .... ( complete). This means, that the current money we use only depends on the "trust" we deposit on the goverment that rules its emission and this "legal curse" is enforced by law. There is NOT ANY OTHER intrinsec propierty on paper money to ensure its value than this!! When talking about corruption in some of our political and financial institutions, we can easily perceive how often this trust has been abused.This kind of money enforced by law has been called *fiat money*.

==== Cryptocurrency
When Bitcoin solved the issues that prevented other digital currencies to become a viable digital money ( "authenticity" (of the issuing and ownership) and the "double-spend" problem) it opened a whole new world where cryptography provides the basis for trusting the legitimacy of a user's claim to value. So, this new kind of currency that is entirely virtual and that is implied in transactiones that transfer value from sender to recipient based on crytographic signatures is what we call *cryptocurrency*

TIP: Taking Bitcoin as "the" paradigmatic model of every cryptocurrency, we need to have in mind that for Bitcoin to exist following is needed:

* A decentralized peer-to-peer network (the bitcoin protocol)
* A public transaction ledger (the blockchain)
* A decentralized mathematical and deterministic currency issuance (distributed mining)
* A decentralized transaction verification system (transaction script)


--> consensus agreement to transport value from one point to another


=== FERMAT as a system of platforms
FERMAT was originally conceived as a new platform for wallet production to reach end user's that were ready to adopt cryptocurrency but did not want to get involved in the technichal aspecting of programming or needing developer{ s skills to use them. The initial goal could be reached and at the same time the technology to be developed was thought to expand the possibilities of wallets to marketing agencies to rebrand wallets  for their customers and event reach to the retailers circuit in a very convinient way. After the first months of development where the team has rapidly grown to more than 20 people, the implications of FERMAT{ s conceptual framework led to the exploration and development of new applications, that reorganized, have turn FERMAT instead of a platform into a system of platforms ( a platform stack) based on a plug-in architecture to be implemented as a distributed system that runs on multiple OS including Android, Linux, iOS, OSX and Windows.

* OPEN SOURCE
The code can be reviewed and audited by anyone.

* DECENTRALIZED
It runs on end users’ devices.

* PUBLIC
Anybody can connect to the Fermat P2P network and use its services. Anybody can write plug-ins for the platform.

* OPEN
Anybody can participate and innovate without requiring permission.

* INCLUSIVE
Any existing crypto service running outside the Fermat network / platform can be integrated and consumed from within the network.

* OPEN STANDARD
Can be freely adopted, implemented and extended.

:numbered:
=== Segmentation and different levels of abstraction
Cryptocurrencies are born into existent by a very specific mathemathical algorithym based on cryptographics rules run by a computer in a process called " mining". They are held and stored by their owners in specific applications called * wallets * that live in a certain device of the decentralized p2p network. To start using a cryptocurrency you have to download a client application ( full node or leightweight) to your device or use a cloud base application. The client application provides the basic functionalities to operate, i.e. usually one or a couple of "basic wallets" which generates an user unique identification and also a specific adress in the chosen cryptonetwork.

FERMAT understands that there exists on the world so many different tastes and preferences like humans exists on earth, because each one is unique, and therefore there are potentially so many differents ways of shaping the accessibility, appearance and functionality of applications dealing with cryptocurrencies and blockchain technology to match very specific need and scalable demand of each consumer's niche. Here begins the huge differentation between FERMAT applications and the rest ! FERMAT takes very seriously into account the actor's profile to develop attractive application in each case.


=== Specific architecture 
:numbered!:
FERMAT consists of small applications called plug-ins that run a small and very specific set of rules to process certain input data and to get " its job done " by offering an output data with a well defined structure. Each plug-in is given certain responsability within the whole environment where it dwells and they are set to operate into different layers that stack one over the other building a hierachical structure where responsability is transfered from the lower layer onto the next upper one. The plug-ins sharing alike purposes live in the same layer but they also build a second array in columns if the depend one another to provide certain functionality. 
 
==== General overview on layers

* FERMAT OSA (operating system )
* FERMAT CORE
* FERMAT P2P ( network and communication layers)
* FERMAT BCH (blockchain)
** FERMAT PIP
*** FERMAT WPD (wallet production)
*** FERMAT DPN (digital privat network)
**** FERMAT CCP (crypto currency platform)
**** FERMAT SHP (shop platform)
**** FERMAT DAP (digital assets platform)



 



