:numbered: 
== FERMAT WPD: Wallet Factory & Wallet Production Line

In the cryptocurrency environment, value is held in specific applications/programs called *WALLET*.
The main and basic functions of a Wallet is to send and receive money as a result of a transaction between two wallet' s owners.
Regarding one of FERMAT'S target,i.e. allowing a great segmentation and abstraction levels and at the same time offering the user a pleasant, safe and easy-to-use exprience, the first job is to offer a number of *reference Wallets* for each *niche* discovered, wallets that can be adopted to inmediate use and also which can be taken as a " template" to build other more customized and complex wallets reusing the most of the components available in the platform at the time of the new development.

For the first distribution of FERMAT, we have chosen Android as operative system, and a couple of reference wallets and services.

These reference wallets allow the basic functiones of any wallet:

* Transactions Log: (transactions in both status: Book balance & Available balance)
* Contacts: manager of contact's info and their cryptoaddresses
* Send: send money to a given crytoaddress
* Receive: creates a valid cryptoaddress to let others send cryptocurrency to the wallet's owner.
* Balance: yout count status!

 
.Reference Wallets included in version 1.0
* *BitWa (Basic Bitcoin Wallet)*
*
*

The first service, really an innovation introduced by FERMAT, is the FERMAT WPD, FERMAT' S Wallet Factory and Production Line.

TIP: Beforing exploring this fascinating environment, we need to introduce two distincts 
gatherings of the components of a certain wallet: + 
* components oriented towards the user (what he sees and how hi manages the wallet), called *front-end* modules.
* components that perform each function of the wallet at operational level, called *back-end* modules.

 
=== FERMAT Wallet Factory

Once we have at least one *Niche Reference Wallet* (e.g.*Bitcoin Reference Wallet*), we can realize that in the *front-end* there are two disctint tasks taking place: on one hand, there exist a *navigation structure* (available menus, tabs, buttons, etc) that provides the means by which the user operates the wallet, an on the other hand, there exists a set of *resources* (multimedia files, images, etc) used for the visualization of each element of the wallet.
At the 
En el *back-end* , where the really action is occuring, we have a lot of modules acting to provide the necessary functions, like: +
* sending and receiving the cryptocurrency
* keeping track of the balance of the wallet
* managing the contacts ( register, identification, etc)

If someone having the required programmer's skills wants to build a Wallet, he would necessary have to build every and each one of the modules needed for the wallet to run begin to write the code from zero. However, if you remember that FERMAT is an open system allowing third part developers and actors in general to form part, developers of new wallet can use any of the available *reference niche wallet* to reutilize the COMPLETE back-end ( all the programming code stuff!), and concentrate his endeavour only to the *front-end*making his job a lot easier and allowing all his creativity to be channeled in a better and more attractive result for the end user. ( not only for a nice look but also for improved and more efficient functionalities!).


=== FERMAT Wallet Publisher
=== FERMAT Wallet Store
=== FERMAT wallet Manager




