Author: Furszyfer Matias

== Soporte para multiples pantallas:

El soporte para multiples pantallas se encuentra dado por diversos factores los cuales voy a detallar a continuación.

=== El tamaño de la pantalla en la cual puede estar corriendo la aplicación:

* Small:	Recursos para small size screens.
* Normal:	Recursos para normal size screens.
* Large:	Recursos para large size screens.
* Xlarge:	Recursos para extra-large size screens.

=== La densidad de la pantalla:

* ldpi: Para recursos con low density de pantalla -120 dpi
* mdpi: Para recursos con medium density de pantalla -160 dpi
* hdpi: Para recursos con high density de pantalla -240 dpi
* xhdpi: Para recursos con extra-high density de pantalla ~320dpi
* xxhdpi: Para recursos con extra-extra-high density de pantalla ~480dpi
* xxxhdpi: Para recursos con extra-extra-extra high density de pantalla ~640dpi. Esto se usa solo para el icono de inicio solamente

=== La forma de visualizar la pantalla:

* Portrait:  Forma vertical de ver el dispositivo.
* Landscape: Forma horizontal de ver el dispositivo.


== Por lo cual en nuestro repositorio de github debemos estar organizados con lo siguiente:

Para cada tamaño de pantalla debe haber una carpeta y dentro de este directorio deben estar dos sub directorios de portrait y landscape.
Por ejemplo la forma de tratarlo para una determinada wallet sería:

* wallet/small/landscape/layout_landscape.xml
* wallet/small/portrait/layout_portrait.xml
* wallet/large/landscape/layout_large.xml

A su vez tambíen debe haber un directorio con las imagenes e iconos que puedan ser llamados desde la
aplicación para un tipo de densidad y un tamaño de pantalla. Esto lo va a saber la aplicación al
momento en el que se instala la wallet, que va a obtener los recursos necesarios a traves del
walletResources y a guardarlos en el dispositivo.

=== En github los directorios estos van a estar dispuestos de la siguiente forma:

* wallet/drawables/drawable_ldpi/icono.ico
* wallet/drawables/drawable_xxxhdpi/icono.ico

=== Observaciones a considerar:
* Por lo menos el icono pertinente al laucher debe estar en todos los tamaños disponibles.
* Cada wallet debe tener un directorio por defecto al cual el resources vaya a buscar los recursos necesarios para correr la si estos no estan definidos por el developer.
* Puede haber layout que sean adaptables a más de un tamaño de pantalla.


=== En cuanto a la aplicación va a haber que hacer cambios:

==== Wallet resources:
* Deberá implementar la funcionalidad para obtener desde el repositorio solo los recursos que son compatibles con el dispositivo en el cual se encuentra instalado, se le debe entregar desde el sistema operativo el tamaño de la pantalla y la densidad que la misma posee.
Encargando se de está manera de traer los siguientes recursos:
** layout: estos vienen dados por el tamaño de la pantalla y si esta misma soporta landscape o portrait.
** Drawables: estos vienen dados por la densidad de la pantalla en cuestión (dpi).

==== Wallets:
* Los fragmentos de la wallet van a tener que implementar la logica para decidir si el dispositivo se encuentra en landscape usar un layout y si se encuentra en portrait usar el otro correspondiente.
* El manejo de las imagenes/iconos es indistinto ya que solo se bajarian los cuales son compatibles con el dispositivo en cuestión.

TODO: Analizar cambios en Wallet Factory y Wallet Store