package com.bitdubai.fermat_api.layer._2_platform_service.event_manager;

/**
 * Created by ciencias on 24.01.15.
 */
public enum EventType {

    USER_CREATED, 
    USER_LOGGED_IN, 
    USER_LOGGED_OUT,
    INTRA_USER_CONTACT_CREATED,

    WALLET_CREATED, 
    WALLET_WENT_ONLINE, 
    WALLET_INSTALLED, 
    BEGUN_WALLET_INSTALLATION, 
    WALLET_UNINSTALLED, 
    WALLET_CLOSED, 
    WALLET_OPENED,
    WALLET_RESOURCES_INSTALLED,
    NAVIGATION_STRUCTURE_UPDATED,
    MONEY_RECEIVED, FINISHED_WALLET_INSTALLATION,

    INCOMING_CRYPTO_RECEIVED,
    INCOMING_CRYPTO_RECEPTION_CONFIRMED,
    INCOMING_CRYPTO_REVERSED,
    INCOMING_CRYPTO_IDENTIFIED,
    INCOMING_CRYPTO_IDENTIFIED_FROM_EXTRA_USER,
    INCOMING_CRYPTO_IDENTIFIED_FROM_INTRA_USER,
    INCOMING_CRYPTO_IDENTIFIED_FROM_DEVICE_USER,
    INCOMING_CRYPTO_RECEIVED_FROM_EXTRA_USER,
    INCOMING_CRYPTO_RECEIVED_FROM_INTRA_USER,
    INCOMING_CRYPTO_RECEIVED_FROM_DEVICE_USER,
    INCOMING_CRYPTO_RECEPTION_CONFIRMED_FROM_EXTRA_USER,
    INCOMING_CRYPTO_RECEPTION_CONFIRMED_FROM_INTRA_USER,
    INCOMING_CRYPTO_RECEPTION_CONFIRMED_FROM_DEVICE_USER,
    INCOMING_CRYPTO_REVERSED_FROM_EXTRA_USER,
    INCOMING_CRYPTO_REVERSED_FROM_INTRA_USER,
    INCOMING_CRYPTO_REVERSED_FROM_DEVICE_USER


    }
