package com.bitdubai.fermat_api.layer.all_definition.enums;

import com.bitdubai.fermat_api.layer.all_definition.enums.interfaces.FermatEnum;
import com.bitdubai.fermat_api.layer.all_definition.exceptions.InvalidParameterException;

import java.util.Objects;

/**
 * Created by ciencias on 2/13/15.
 */
public enum Plugins implements FermatEnum {

    //Modified by Manuel Perez on 03/08/2015
    BITDUBAI_LICENSE_MANAGER("BLICM", Developers.BITDUBAI),
    BITDUBAI_BLOCKCHAIN_INFO_WORLD("BBLOCKIW", Developers.BITDUBAI),
    BITDUBAI_SHAPE_SHIFT_WORLD("BSHAPESW", Developers.BITDUBAI),
    BITDUBAI_COINAPULT_WORLD("BCOINAW", Developers.BITDUBAI),
    BITDUBAI_CRYPTO_INDEX("BCRYPTOINW", Developers.BITDUBAI),
    BITDUBAI_BITCOIN_CRYPTO_NETWORK("BBTCCNET", Developers.BITDUBAI),
    BITDUBAI_BITCOIN_CRYPTO_NETWORK2("BBTCCNET2", Developers.BITDUBAI),
    BITDUBAI_CLOUD_CHANNEL("BCLOUDC", Developers.BITDUBAI),

    BITDUBAI_WS_COMMUNICATION_CLOUD_SERVER("BWSCCLSERVER", Developers.BITDUBAI),
    BITDUBAI_WS_COMMUNICATION_CLIENT_CHANNEL("BWSCCLIENTCH", Developers.BITDUBAI),

    BITDUBAI_CLOUD_SERVER_COMMUNICATION("BCLOUSC", Developers.BITDUBAI),
    BITDUBAI_USER_NETWORK_SERVICE("BUSERNETS", Developers.BITDUBAI),
    BITDUBAI_TEMPLATE_NETWORK_SERVICE("BTEMNETS", Developers.BITDUBAI),
    BITDUBAI_INTRAUSER_NETWORK_SERVICE("BINUSERNS", Developers.BITDUBAI),
    BITDUBAI_APP_RUNTIME_MIDDLEWARE("BAPPRUNM", Developers.BITDUBAI),
    BITDUBAI_DISCOUNT_WALLET_BASIC_WALLET("BDWALLBW", Developers.BITDUBAI),
    BITDUBAI_WALLET_RUNTIME_MODULE("BWALLRUNM", Developers.BITDUBAI),
    BITDUBAI_BITCOIN_CRYPTO_VAULT("BBTCCRYV", Developers.BITDUBAI),
    BITDUBAI_ASSETS_CRYPTO_VAULT("BASSTCRYV", Developers.BITDUBAI),
    BITDUBAI_INTRA_USER_FACTORY_MODULE("BINUSFACM", Developers.BITDUBAI),
    BITDUBAI_BANK_NOTES_WALLET_WALLET_MODULE("BBNWWM", Developers.BITDUBAI),
    BITDUBAI_CRYPTO_LOSS_PROTECTED_WALLET_WALLET_MODULE("BCLPWWM", Developers.BITDUBAI),
    BITDUBAI_CRYPTO_WALLET_WALLET_MODULE("BCWWM", Developers.BITDUBAI),
    BITDUBAI_DISCOUNT_WALLET_WALLET_MODULE("BDWWM", Developers.BITDUBAI),
    BITDUBAI_FIAT_OVER_CRYPTO_LOSS_PROTECTED_WALLET_WALLET_MODULE("BFOCLPWWM", Developers.BITDUBAI),
    BITDUBAI_FIAT_OVER_CRYPTO_WALLET_WALLET_MODULE("BFOCWWM", Developers.BITDUBAI),
    BITDUBAI_MULTI_ACCOUNT_WALLET_WALLET_MODULE("BMAWWM", Developers.BITDUBAI),
    BITDUBAI_INCOMING_INTRA_USER_TRANSACTION("BININUST", Developers.BITDUBAI),
    BITDUBAI_INCOMING_DEVICE_USER_TRANSACTION("BINDEVUT", Developers.BITDUBAI),
    BITDUBAI_OUTGOING_DEVICE_USER_TRANSACTION("BODEVUST", Developers.BITDUBAI),
    BITDUBAI_INTER_WALLET_TRANSACTION("BINWALLT", Developers.BITDUBAI),
    BITDUBAI_BANK_NOTES_MIDDLEWARE("BBNMIDD", Developers.BITDUBAI),
    BITDUBAI_BANK_NOTES_NETWORK_SERVICE("BBNNETSER", Developers.BITDUBAI),
    BITDUBAI_WALLET_RESOURCES_NETWORK_SERVICE("BWRNETSER", Developers.BITDUBAI),
    BITDUBAI_WALLET_STORE_NETWORK_SERVICE("BWSTONETSER", Developers.BITDUBAI),
    BITDUBAI_WALLET_COMMUNITY_NETWORK_SERVICE("BWCNETSER", Developers.BITDUBAI),
    BITDUBAI_CRYPTO_ADDRESS_BOOK("BCADDB", Developers.BITDUBAI),
    BITDUBAI_OUTGOING_EXTRA_USER_TRANSACTION("BOUEXUT", Developers.BITDUBAI),
    BITDUBAI_INCOMING_EXTRA_USER_TRANSACTION("BINEXUT", Developers.BITDUBAI),
    BITDUBAI_INCOMING_CRYPTO_TRANSACTION("BINCRYT", Developers.BITDUBAI),
    BITDUBAI_USER_DEVICE_USER("BUDEVU", Developers.BITDUBAI),
    BITDUBAI_ACTOR_EXTRA_USER("BAEXU", Developers.BITDUBAI),
    BITDUBAI_USER_INTRA_USER("BUINU", Developers.BITDUBAI),
    BITDUBAI_COINBASE_WORLD("BCOINW", Developers.BITDUBAI),
    BITDUBAI_BITCOIN_WALLET_BASIC_WALLET("BBTCWBW", Developers.BITDUBAI),
    BITDUBAI_DEVICE_CONNECTIVITY("BBTCDEVC", Developers.BITDUBAI),
    BITDUBAI_LOCATION_WORLD("BLOCW", Developers.BITDUBAI),
    BITDUBAI_ACTOR_DEVELOPER("BACTORD", Developers.BITDUBAI),
    BITDUBAI_WALLET_LANGUAGE_MIDDLEWARE("BWLMIDD", Developers.BITDUBAI),
    BITDUBAI_WALLET_SKIN_MIDDLEWARE("BWSMIDD", Developers.BITDUBAI),
    BITDUBAI_WALLET_NAVIGATION_STRUCTURE_MIDDLEWARE("BWNSMIDD", Developers.BITDUBAI),
    BITDUBAI_SUB_APP_SETTINGS_MIDDLEWARE("BSASEMIDD", Developers.BITDUBAI),
    BITDUBAI_WALLET_STATISTICS_NETWORK_SERVICE("BWSTANETSER", Developers.BITDUBAI),
    BITDUBAI_SUBAPP_RESOURCES_NETWORK_SERVICE("BSRNETSER", Developers.BITDUBAI),
    BITDUBAI_CCP_CRYPTO_TRANSMISSION_NETWORK_SERVICE("BCTNSER", Developers.BITDUBAI),
    BITDUBAI_REQUEST_MONEY_REQUEST("BRMR", Developers.BITDUBAI),
    BITDUBAI_DEVELOPER_IDENTITY("BDEVID", Developers.BITDUBAI),
    BITDUBAI_TRANSLATOR_IDENTITY("BDTRAID", Developers.BITDUBAI),
    BITDUBAI_IDENTITY_MANAGER("BIDMAN", Developers.BITDUBAI),
    BITDUBAI_DESIGNER_IDENTITY("BDDESID", Developers.BITDUBAI),
    BITDUBAI_DEVELOPER_MODULE("BDEVMOD", Developers.BITDUBAI),
    BITDUBAI_MIDDLEWARE_NOTIFICATION("BDNOTMID", Developers.BITDUBAI),
    BITDUBAI_DESKTOP_RUNTIME("BDR",Developers.BITDUBAI),

    // Init CCP Plugins
    BITDUBAI_CCP_INTRA_WALLET_USER_ACTOR                    ("BCCPIWUA" , Developers.BITDUBAI),
    BITDUBAI_CCP_CRYPTO_ADDRESSES_NETWORK_SERVICE           ("BCCPCANS" , Developers.BITDUBAI),
    BITDUBAI_CCP_CRYPTO_CRYPTO_TRANSMISSION_NETWORK_SERVICE ("BCCPCTNS" , Developers.BITDUBAI),
    BITDUBAI_CCP_CRYPTO_PAYMENT_REQUEST_NETWORK_SERVICE     ("BCCPCPRNS", Developers.BITDUBAI),
    BITDUBAI_CCP_INTRA_WALLET_USER_IDENTITY                 ("BCCPIUI"  , Developers.BITDUBAI),
    BITDUBAI_CCP_WALLET_CONTACTS_MIDDLEWARE                 ("BCCPWCM"  , Developers.BITDUBAI),
    BITDUBAI_CCP_CRYPTO_PAYMENT_REQUEST                     ("BCCPCPR"  , Developers.BITDUBAI),
    BITDUBAI_CCP_OUTGOING_INTRA_ACTOR_TRANSACTION           ("BCCPOIAT" , Developers.BITDUBAI),

    BITDUBAI_CRYPTO_TRANSMISSION_NETWORK_SERVICE ("BCTNS"),


    // End  CCP Plugins

    //CCM Plugins

    BITDUBAI_CCM_INTRA_WALLET_USER_ACTOR                    ("BCCMIWUA" , Developers.BITDUBAI),

    // Init DAP Plugins
    BITDUBAI_DAP_ASSET_ISSUER_ACTOR                       ("BDAPAIA",    Developers.BITDUBAI),
    BITDUBAI_DAP_ASSET_USER_ACTOR                         ("BDAPAUA",    Developers.BITDUBAI),
    BITDUBAI_DAP_REDEEM_POINT_ACTOR                       ("BDAPRPA",    Developers.BITDUBAI),
    BITDUBAI_DAP_ASSET_ISSUER_IDENTITY                    ("BDAPAII",    Developers.BITDUBAI),
    BITDUBAI_DAP_ASSET_USER_IDENTITY                      ("BDAPAUI",    Developers.BITDUBAI),
    BITDUBAI_DAP_REDEEM_POINT_IDENTITY                    ("BDAPRPI",    Developers.BITDUBAI),
    BITDUBAI_ASSET_ISSUING_TRANSACTION                    ("BAIT",       Developers.BITDUBAI),
    BITDUBAI_ASSET_DISTRIBUTION_TRANSACTION               ("BADT",       Developers.BITDUBAI),
    BITDUBAI_ASSET_RECEPTION_TRANSACTION                  ("BADR",       Developers.BITDUBAI),
    BITDUBAI_ASSET_APPROPRIATION_TRANSACTION              ("BAAT",       Developers.BITDUBAI),
    BITDUBAI_ASSET_WALLET_ISSUER                          ("BASWI",      Developers.BITDUBAI),
    BITDUBAI_ASSET_FACTORY                                ("BASF",       Developers.BITDUBAI),
    BITDUBAI_ASSET_FACTORY_MODULE                         ("BASFM",      Developers.BITDUBAI),
    BITDUBAI_DAP_ASSET_USER_WALLET_MODULE                 ("BDAUWMO",    Developers.BITDUBAI),
    BITDUBAI_DAP_ASSET_ISSUER_WALLET_MODULE               ("BDAIWMO",    Developers.BITDUBAI),
    BITDUBAI_DAP_ASSET_REDEEM_POINT_WALLET_MODULE         ("BDARWMO",    Developers.BITDUBAI),
    BITDUBAI_DAP_ASSET_ISSUER_COMMUNITY_SUB_APP_MODULE    ("BDAPAICSAM", Developers.BITDUBAI),
    BITDUBAI_DAP_ASSET_USER_COMMUNITY_SUB_APP_MODULE      ("BDAPAUCSAM", Developers.BITDUBAI),
    BITDUBAI_DAP_REDEEM_POINT_COMMUNITY_SUB_APP_MODULE    ("BDAPRPCSAM", Developers.BITDUBAI),
    BITDUBAI_DAP_ASSET_REDEEM_POINT_WALLET                ("BDAPAWRD",   Developers.BITDUBAI),
    BITDUBAI_DAP_ASSET_USER_WALLET                        ("BDAPAWU",    Developers.BITDUBAI),
    BITDUBAI_DAP_ASSET_USER_ACTOR_NETWORK_SERVICE         ("BDAPAUANS",  Developers.BITDUBAI),
    BITDUBAI_DAP_ASSET_ISSUER_ACTOR_NETWORK_SERVICE       ("BDAPAIANS",  Developers.BITDUBAI),
    BITDUBAI_DAP_ASSET_REDEEM_POINT_ACTOR_NETWORK_SERVICE ("BDAPARANS",  Developers.BITDUBAI),
    BITDUBAI_DAP_ASSET_TRANSMISSION_NETWORK_SERVICE       ("BDAPATNS",   Developers.BITDUBAI),
    // End  DAP Plugins

    // Init WPD Plugins
    BITDUBAI_WPD_WALLET_MANAGER_DESKTOP_MODULE          ("BWPDWMDM"),
    BITDUBAI_WPD_WALLET_FACTORY_MIDDLEWARE              ("BWPDWFM"),
    BITDUBAI_WPD_WALLET_MANAGER_MIDDLEWARE              ("BWPDWMM"),
    BITDUBAI_WPD_WALLET_PUBLISHER_MIDDLEWARE            ("BWPDWPM"),
    BITDUBAI_WPD_WALLET_SETTINGS_MIDDLEWARE             ("BWPDWSEM"),
    BITDUBAI_WPD_WALLET_STORE_MIDDLEWARE                ("BWPDWSTM"),
    BITDUBAI_WPD_PUBLISHER_IDENTITY                     ("BWPDPI"),
    BITDUBAI_WPD_WALLET_COMMUNITY_NETWORK_SERVICE       ("BWPDWCNS"),
    BITDUBAI_WPD_WALLET_RESOURCES_NETWORK_SERVICE       ("BWPDWRNS"),
    BITDUBAI_WPD_WALLET_STATISTICS_NETWORK_SERVICE      ("BWPDWSNS"),
    BITDUBAI_WPD_WALLET_STORE_NETWORK_SERVICE           ("BWPDSNS"),
    BITDUBAI_WPD_WALLET_FACTORY_SUB_APP_MODULE          ("BWPDWFSAM"),
    BITDUBAI_WPD_WALLET_PUBLISHER_SUB_APP_MODULE        ("BWPDWPSAM"),
    BITDUBAI_WPD_WALLET_STORE_SUB_APP_MODULE            ("BWPDWSSAM"),
    // End  WPD Plugins

    //Init CBP Plugins
    BITDUBAI_CBP_CRYPTO_BROKER_IDENTITY ("BCBPCBI", Developers.BITDUBAI),
    BITDUBAI_CBP_CRYPTO_CUSTOMER_IDENTITY ("BCBPCCI", Developers.BITDUBAI),
    BITDUBAI_CBP_CRYPTO_BROKER_IDENTITY_SUB_APP_MODULE ("BCBPCBISAM", Developers.BITDUBAI),
    BITDUBAI_CBP_CRYPTO_CUSTOMER_IDENTITY_SUB_APP_MODULE ("BCBPCCISAM", Developers.BITDUBAI),
    //End CBP Plugins
    
    // Init new Plugins

    BITCOIN_WALLET         ("BW" ),
    CRYPTO_ADDRESSES       ("CA" ),
    CRYPTO_PAYMENT_REQUEST ("CPR"  ),
    CRYPTO_TRANSMISSION    ("CT" ),
    CRYPTO_WALLET          ("CW"  ),
    EXTRA_WALLET_USER      ("EWU" ),
    INCOMING_EXTRA_USER    ("IEU" ),
    INCOMING_INTRA_USER    ("IIU" ),
    INTRA_WALLET_USER      ("IWU" ),
    OUTGOING_EXTRA_USER    ("OEU" ),
    OUTGOING_INTRA_ACTOR   ("OIA" ),
    WALLET_CONTACTS        ("WC"  );

    // End  new Plugins

    private final String code;

    Plugins(final String code) {
        this.code = code;
    }

    public String getKey() {
        return this.code;
    }

    @Override
    public String getCode() {
        return this.code;
    }

    public static Plugins getByKey(String code) throws InvalidParameterException {
        for (Plugins plugin : values()) {
            if (Objects.equals(plugin.getCode(), code)) return plugin;
        }
        throw new InvalidParameterException(InvalidParameterException.DEFAULT_MESSAGE, null, "Code Received: " + code, "This Code Is Not Valid for the Plugins enum");
    }
}
