package com.bitdubai.reference_niche_wallet.fermat_wallet.fragment_factory;

import com.bitdubai.fermat_android_api.layer.definition.wallet.enums.FermatFragmentsEnumType;

/**
 * Created by Matias Furszyfer on 2015.07.22..
 */
public enum ReferenceFragmentsEnumType implements FermatFragmentsEnumType<ReferenceFragmentsEnumType> {


    /**
     * FERMAT WALLET
     */

    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_SEND("CWRWBTCFABS"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_BALANCE("CWRWBTCFABB"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_RECEIVE("CWRWBTCFABR"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_TRANSACTIONS("CWRWBTCFABT"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_CONTACTS("CWRWBTCFABC"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_DETAIL_CONTACTS("CWRWBFABDC"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_CREATE_CONTACTS("CWRWBTCFABCC"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_MONEY_REQUEST("CWRWBTCFABMR"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_TRANSACTIONS_BOOK("CWRWBTCFABTB"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_TRANSACTIONS_AVAILABLE("CWRWBTCFABTA"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_CHUNCK_VALUES("CWRWBTCFABCV"),

    CCP_BITCOIN_FERMAT_WALLET_HOME("CCPFWH"),
    CCP_BITCOIN_FERMAT_WALLET_TRANSACTIONS_SENT("CCPFWTS"),
    CCP_BITCOIN_FERMAT_WALLET_TRANSACTIONS_RECEIVED("CCPFWTR"),
    CCP_BITCOIN_FERMAT_WALLET_REQUEST_RECEIVED("CCPFWRR"),
    CCP_BITCOIN_FERMAT_WALLET_REQUEST_SEND("CCPFWRS"),
    CCP_BITCOIN_FERMAT_WALLET_TRANSACTIONS_SENT_HISTORY("CCPFWTSH"),
    CCP_BITCOIN_FERMAT_WALLET_TRANSACTIONS_RECEIVED_HISTORY("CCPFWTRH"),
    CCP_BITCOIN_FERMAT_WALLET_REQUEST_SENT_HISTORY("CCPFWRSH"),
    CCP_BITCOIN_FERMAT_WALLET_REQUEST_RECEIVED_HISTORY("CCPFWRRH"),

    CCP_BITCOIN_FERMAT_WALLET_SEND_FORM_FRAGMENT("CPPFWSFF"),
    CCP_BITCOIN_FERMAT_WALLET_SEND_WALLET_FORM_FRAGMENT("CPPFWSWFF"),
    CCP_BITCOIN_FERMAT_WALLET_REQUEST_FORM_FRAGMENT("CCPFWRFF"),
    CCP_BITCOIN_FERMAT_WALLET_SETTINGS_FRAGMENT("CCPFWSF"),
    CCP_BITCOIN_FERMAT_WALLET_SETTINGS_FRAGMENT_NOTIFICATIONS("CCPFWSFN"),
    CCP_BITCOIN_FERMAT_WALLET_SETTINGS_FRAGMENT_MAIN_NETWORK("CCPFWSFMN"),
    CCP_BITCOIN_FERMAT_WALLET_ADD_CONNECTION_FRAGMENT("CCPFWACF"),
    CCP_BITCOIN_FERMAT_WALLET_NO_IDENTITY_FRAGMENT("CCPFWNIF"),
    CCP_BITCOIN_FERMAT_WALLET_MNEMONIC_FRAGMENT("CCPFWMNF"),
    CCP_BITCOIN_FERMAT_WALLET_CHUNCK_VALUES_DETAIL_FRAGMENT("CCFBWCVDF"),
    CCP_BITCOIN_FERMAT_WALLET_SEND_ERROR_REPORT_FRAGMENT("CCPFWSER");

    /**
     * FERMAT WALLET
     */


    private String key;

    ReferenceFragmentsEnumType(String key) {
        this.key = key;
    }

    public static ReferenceFragmentsEnumType getValue(String name) {
        for (ReferenceFragmentsEnumType fragments : ReferenceFragmentsEnumType.values()) {
            if (fragments.key.equals(name)) {
                return fragments;
            }
        }
        // throw an IllegalArgumentException or return null
        // throw new IllegalArgumentException("the given number doesn't match any Status.");
        //TODO METODO CON RETURN NULL - OJO: solo INFORMATIVO de ayuda VISUAL para DEBUG - Eliminar si molesta
        return null;
    }

    @Override
    public String getKey() {
        return this.key;
    }

    @Override
    public String toString() {
        return key;
    }


}
