[line-through]#[[flujo-general-BitDubai-V1]]

= Flujo General de la Plataform DAP


El actor ISSUER procede a crear el Asset donde colocara la informacion relevante:

  * Tienen un Emisor, que es alguno de los actores del sistema.
  * Tienen una fecha de expiración. (aunque en algunos casos puede ser que no expiren nunca)
  * Tienen uno o mas elementos multi-media (imagen, sonido, video, animación, etc.) destinados a
    representar ante el usuario final dicho asset.
  * Son de un determinado tipo.
  * Pueden ser redimido.
  * Tienen una lista de condiciones que dependen de su tipo. (Las entienden cualquier wallet que maneje
    ese tipo de Assets)
  * Son de un determinado sub-tipo.
  * Tienen una lista de condiciones que dependen de su sub-tipo. (Las entienden cualquier wallet que
    maneje ese sub-tipo de Assets)
  * Tienen una lista de condiciones que dependen de su emisor. (Solo las entienden las wallets del emisor)

El Issuer determinara en que momento el Asset estara disponible para su envio o publicacion a las Wallets
instaladas en otros dispositivos y de manera asincrona comenzara la instalacion del Asset, siempre y
cuando se haya validado algunas informacion tecnica del Asset, por ejemplo que no haya caducado,
el actor User, debera de una manera aceptar
el Asset recibido.

Deberiamos de buscar la manera de saber el codigo de la billetera para proceder a enviar el asset.

Interacion y Flujo de pluggin, subapp, explicacion.

= Flujo Desarrollo

El flujo de desarrollo del Asset describe lo necesario para generar un Digital Asset.
El objeto DigitalAsset de la plataforma, contará con las siguientes propiedades:

 * Identity Asset Issuer: Identity del Actor AssetIssuer
 * String name: nombre del Asset definido por el issuer.
 * String description: descripción del asset definido por el issuer.
 * List<Resource>: lista de recursos posibles del asset, como por ejemplo imágenes, videos, etc.
 * String GenesisTransaction: hash de la transacciín bitcoin donde el asset está incluido.
 * Address GenesisAddress: dirección Genesis generada por la Asset Vault
 * long GenesisAmount: valor crypto del digital asset en Satoshis.

Como contrato básico para el Digital Asset para poder cerrar el ciclo en el desarrollo inicial de la plataforma,
especificaremos que:

 * Redimible
 * ExpirationDate: fecha de expiración que puede ser nunca.

Una vez completadas estas propiedades por parte del Issuer, y cerrado y decidido a crear el Digital Asset sin más cambios,
la Asset Issuer subApp, inicia una Digital Asset Transaction de Asset Issuing en la que lo siguiente ocurre:

* Se solicita a la Crypto Vault la creación de una transaction bitcoin la cual devuelve un hash. Este hash se define como la GenesisTransaction
en el Digital Asset.
* Se solicita a la Asset Vault una dirección bitcoin que será la GenesisAddress
* Se completa la crypto transacción especificando el GenesisAmount.
* Se ejecuta un hash del Digital Asset y el mismo se coloca en el OP_OUTPUT de la crypto transacción.
* Se commitea la transacción y la misma es publicada a la red de bitcoin a través de la Crypto Network.
* El Digital Asset es considerado creado y cerrado.


[Manuel completar más info de la transacción]

Realizadas estas operaciones, y al momento de recibir el GenesisAmount en la Asset Vault, las operaciones de crédito dentro de la
Asset Wallet deben ocurrir. [Franklin, completar más info]


= Transferencia y confirmación de Asset a beneficiario

= Notificación en Incoming Issuer

El plugin Incoming Issuer en el lado del consumidor o beneficiario será el encargado de monitorear la existencia de un Digital Asset (de alguna manera, por definir) que esté dirigido para la Asset Wallet del usuario,
en caso de recibir la notificación de la existencia de un Digital Asset, este plugin deberá verificar la metadata que debe estar incluida en el Asset,  esta comprobación debe
incluir la verificación de la genesis Transaction, con lo cual se puede verificar el origen del Asset.
Una vez verificado el origen del Asset, el plugin debe lanzará una notificación a una capa superior para que el usuario esté en cuenta de la existencia de este Asset.
Es de hacer notar que hasta el momento, se piensa que el usuario va a autorizar si el Asset va a ser descargado en el dispositivo, esto podría cambiar en un futuro,
ya que se plantea que este Asset puede estar "pre-instalado" en el dispositivo. Se podría definir varias posibles condiciones de descarga de un Asset:
 * descargable automáticamente (el Issuer la instala automáticamente en las Asset Wallets destino)
 * descargable por autorización del usuario.
 * preinstalada en la Asset Wallet.
Una vez que la Asset Wallet autoriza la instalación o descarga del Digital Asset, se procede a crear la transacción que va a transferir el monto crypto asociado a la metadata
de la genesis transaction a la Asset Vault del destinatario. Una vez realizada correctamente la transferencia de fondos, se debe notificar a las capas que controlan la UI la
correcta instalación/descarga del Asset.

= Registro en Asset Issuer Wallet

Es importante mencionar que este proceso realizara una transaccion contable al Asset del Issuer, aumentando la cantidad de Asset originado por el Asset en su creacion,
para que cuando sea enviado a un Asset User, le sea debitado dicho asset al Issuet y acreditados al Asset User, de esta forma podriamos conocer cuantos Asset de ese tipo
han sido creados y estan disponible para su envio, todo esta operacion debe ser originado mediante una transaccion de la capa transaction.

= Registro en Asset User Wallet

Este proceso realizara una transaccion contable al Asset del User, aumentando la cantidad de Asset User enviado por el Asset Issuer, y acreditando dicho asset al Issuet
de esta forma podriamos conocer cuantos Asset de ese tipo tiene disponible el Aset User para su intercambio, todo esta operacion debe ser originado mediante una transaccion
de la capa transaction.

= Registro en Redeem Point Wallet

Este proceso determina el intercambio del Asset User donde mediante un metodo donde se pase las direcciones correspondiente se realizara una transaccion contable al Asset del User, disminuyendo la cantidad de Asset User,
y acreditando o retornando dicho asset al Asset Issuer o alguna wallet que determine la Redemcion.
Aclarar que pasa con este Asset si se puede volver a enviar.




#