package com.bitdubai.fermat_p2p_api.layer.p2p_communication.fmp;

public class MalformedFMPPacketException extends FMPException {
	
	/**
	 * autogenerated serialVersionUID
	 */
	private static final long serialVersionUID = -1102140907777389730L;

	public MalformedFMPPacketException(){
		super();
	}
	
	public MalformedFMPPacketException(final String message){
		super(message);
	}
	
}
