= Wallet Resources - Network Service Layer

Este plugin es un nodo de una DAPP (Distributed Application). Administra los recursos y la estructura
de navegación de las wallets que reciden en el dispositivo (instalados y publicados). También se
encarga de obtener los recursos y estructura de navegación de wallets que desean instalarse. Cuando
un plugin requiere un recurso para una wallet, este plugin es quien se lo entrega. +
También entrega al Wallet Manager la estructura de navegación para que él pueda instalar una nueva
wallet. +


En términos generales esta DAPP hace lo siguiente:

.A nivel de Recursos
* Le da servicios a las NicheWalletType para obtener los recursos que necesitan las NicheWallets que
corren encima de ellas.
* Almacena los recursos de las wallets instaladas. Para esto lleva la cuenta de cuantas walles hay
instaladas de cada tipo, y mientras la cuenta sea mayor que cero garantiza de que los recursos
estarán almacenados localmente.
* Almacena los recursos de las wallets publicadas (posiblemente no instaladas) y garantiza que no
serán borrados.
* Almacena los recursos de wallets no instaladas pero relevantes para la región. Esta funcionalidad
le permite a la red de nodos corriendo este network service, servirse unos a otros de los recursos
de distintos tipos de wallets, elminando la dependencia de un punto central.
* Es capaz de obtener los recursos de wallets de los repositorios centralizados desde donde nacen
originalmente.

.A nivel de Estructura de Navegación
* Le da servicio al Wallet Manager cuando necesita la estructura de navegación de un tipo determinado de wallet durante su proceso de instalación.
* Al igual que los recursos, mantiene la estructura de navegación de los distintos tipos de wallets instalados, garantizando de que los tendrá localmente mientras ese tipo de wallet tenga al menos una instancia instalada.
* Mantiene la estructura de navegación de wallets no instaladas para servirlas a otros peers corriendo el mismo network service, habilitando de esta manera la decentralización de este tipo de información.
* Sabe como localizar la Estructura de Navegación del repositorio centralizado desde donde nace ese tipo de wallet.
