= Intra User - Actor Layer

== Lectura previa

"Agregado de Usuarios | Wallet Contacts | Actor Intra User | Intra User Network Service.asciidoc"


== Descripción detallada de métodos

=== askIntraUserForAcceptance

Tras obtener los datos del intra user que queremos agregar a nuestra lista de conexiones, tocaremos
un botón en la interfaz gráfica que llamará a un método del plugin Intra User Module de la capa Module
que terminará llamando a este método del Actor Intra User. +
Este método va a registrar los datos del intra user que le pasan y le colocará un ContactState de
PENDING_HIS_ACCEPTANCE. A su vez invocará a un método del Intra User Network Service para que envíe
la solicitud de conexión al intra user seleccionado. +

=== Recepción de solicitudes

Cuando llega una solicitud de conexión de otro intra user se desplegará en pantalla un pop-up que nos
informará este evento y nos dará tres opciones:

* Aceptar la solicitud
* Resolver más tarde
* Denegar la solicitud

==== acceptIntraUser

Este método se usa para aceptar la solicitud. En este caso se guarda al contacto en los registros que
lleva este plugin con ContactState CONTACT. Una cuestión a observar es que debe asegurarse que el
usuario que envió la solicitud sea notificado de la aceptación para que pase su estado de
PENDING_HIS_ACCEPTANCE a CONTACT.

==== decideAcceptanceLater

Este método corresponde a postrgar la decisión de aceptación para más adelante, lo cual conlleva a
almacenar los datos del intra user solicitante con ContactState PENDING_YOUR_ACCEPTANCE. En este caso
no hay comunicación con el intra user que envió la solicitud. +

==== denyConnection

Este método corresponde a rechazar la solicitud de conexión. No registramos nada en el registro e
informamos a través del Intra User Network Service esta decisión al usuario que envió la solicitud.

=== deleteIntraUSer

Este método borra el registro de un intra user e informa a través del Intra User Network Service al
intra user que se está borrando para que también nos borre de su lista.

== Inicialización

Al iniciar/hacer cambio de login debe consultar al Network Service las notificaciones pendientes y
actualizar la información de los registros.

== Eventos

=== Events Handlers

* Cuando nos aceptan una solicitud debemos pasar el ContactStatus de PENDING_HIS_ACCEPTANCE a CONTACT. +
* Cuando rechazan una solicitud se borra del registro del plugin
* Cuando nos borra un intra user se debe borrar al intra user de nuestro registro. Considerar que
probablemente se deban borrar registros del wallet contacts, Actor Address Book y Wallet Address Book. +

=== Eventos que lanza

Tras actualizar cuando alguien nos aceptó una solicitud debería lanzar un evento a la interfaz gráfica
tras actualizar los registros correspondientes