= Crypto Transmission - Network Service Layer

Este plugin envía y recibe la metainformación de las transacciones crypto entre intra users. Como es
parte del ciclo transaccional implementará el protocolo de traspaso de transacciones cuando reciba
una transacción. +
Además tendrá un método para chequear el envío de un mensaje con la metainformación, el cual pasará
por los estados:

* PROCESSING: Dado que uno puede pedir a un network service que envíe algo mientras no se está en línea,
este estado lo colocará el network service hasta que envíe a la red el mensaje pedido.
* SENT: Lo coloca el network service al lograr enviar el mesnaje solicitado
* SEEN_BY_DESTINATION_NETWORK_SERVICE: Estado que se obtiene cuando el network service par informa la recepción del mensaje
* SEEN_BY_DESTINATION_VAULT: Estado que se obtiene cuando el receptor de la transacción vió la transacción crypto en la red
* CREDITED_IN_DESTINATION_WALLET; Estado que se obtiene cuando el receptor aplicó la transacción en el book balance de la wallet receptora.

El pasaje del estado PROCESSING a SENT lo realiza el network service localmente. El resto de los cambios
se realizan cuando el network service par informa las situaciones correspondientes. El aviso de recepción
de parte del network service remoto lo realiza el network service apenas recibe el mensaje de su par.
El informe de los estados SEEN_BY_DESTINATION_VAULT y CREDITED_IN_DESTINATION_WALLET es disparado al
llamar a los métodos `informTransactionSeenByVault` e `informTransactionCreditedInWallet`
respectivamente.

Al igual que diversos network services deberá prohibir enviar transacciones a usuarios que no son
nuestros contactos.

NOTE: Podríamos enviar el public key de la walelt acá si lo intercambiamos en el crypto addresses al
agendar contactos. +
Tras ver esto concluímos en que no es una buena idea que el emisor de una transacción te indique a
qué wallet deberías ingresarla.