= Intra User - Identity Layer

Al igual que los demás plug-ins de la capa Identity, este permite la creación de una nueva identidad,
en este caso de una identidad de Intra User. +
El plugin se comunica con el plugin Device User de la capa User para saber qué usuario está usando el
dispositivo. Cuando se crea una nueva identidad se debe pedir este dato al Device User para saber a
quién asociar la nueva identidad. +
Cuando se pide la lista de intra users a este plugin nuevamente se consulta el Device User logueado
para saber qué intra users retirnar. +
En principio, un intra user consta de cinco datos:

* Una clave pública para el intra user
* Una clave privada para el intra user
* Un nombre o alias
* La clave pública correspondiente al device user asociado.
* Una imagen de perfil

De estos cinco sólo se entrega la información de tres: la clave pública, la imagen de perfil y el alias.
No se informa el Device User por una cuestión de seguridad y además por ser algo implícito. La clave
privada tampoco se informa por cuestiones de seguridad. +

