= Intra User - Module Layer

Este plugin es la conexión entre la interfaz gráfica y la plataforma. +
Debe permitir:

* Crear una identidad de intra user
  Esto se hará llamando al plugin Intra User de la capa Identity
* Setear una imagen de perfil
  Esto se hará llamando al plugin Intra User de la capa Identity
* Mostrar las identidades existentes para loguearse.
  Esto se hará llamando al plugin Intra User de la capa Identity
* Loggearse con alguna de las identidades existentes
  Este es un proceso interno del plugin de la capa Module
* Mostrar una lista de sugerencias de contactos para agregar.
  Se reliaza consultando al plugin Intra User Network Service
* Buscar un intra user por su nombre u otros parámetros
  Se reliaza consultando al plugin Intra User Network Service
* Iniciar el proceso para agendar a un usuario como conexión
  Esto involucra llamar al Actor Intra User (él llamará al Network Service Intra User)
* Aceptar una solicitud de conexión
  Esto involucra llamar al Actor Intra User (él llamará al Network Service Intra User)
* Posponer la decisión para aceptar una solicitud
  Esto involucra llamar al Actor Intra User
* Iniciar el proceso que rechaza una solicitud de conexión
  Esto involucra llamar al Actor Intra User (él llamará al Network Service Intra User)
* Borrar un intra user existente de nuestra agenda de conexiones
  Esto involucra llamar al Actor Intra User (él llamará al Network Service Intra User)
* Obtener nuestra lista de conexiones
  Esto involucra llamar al Actor Intra User
* Obtener la lista se solicitudes de conexión
  Esto involucra llamar al Actor Intra User
* Obtener la lista de solicitudes enviadas sin respuesta
  Esto involucra llamar al Actor Intra User
