= Nerwork Service Intra User

Veamos el proceso para agregar un contacto desde la sub app Intra User (posiblemente se presentará
con otro nombre al usuario final) desde el punto de vista del Network Service Intra User. +

Supongamos que nos encontramos logueados con la identidad de Intra User A y deseamos agregar al Intra
User B como conexión. Podemos buscar a B desde diversas sub apps como ya hemos mencionado, en este
milestone podría ser desde un tab de una wallet o desde la sub app Intra Users. +
Como buscamos agendarlo como conexión y no como contacto de una wallet en particular lo primero que
hacemos es buscar a B en la sub app Intra User.
Tras agendar al usuario en el plugin Actor Intra User debemos enviar la solicitud de conexión con
nuestros datos. Para estas tareas necesitamos que el Network Service Intra User:

* Nos de una lista de contactos sobre la que podramos elegir agregar por defecto
* Nos de formas de buscar un contacto en particular siguiendo filtros como el nombre del usuario. +
* Cuando encontramos al usuario a agendar y accionamos el inicio del proceso de agendar al usuario (lo
cual podría ser presionar un botón), agregamos un campo en el Actor Intra User con estado "Solicitud
Enviada". El network service envía un mensaje a su par en B con los datos de A solicitando aceptación,
el usuario podrá entonces aceptar o rechazar la solicitud.

Cuando el mensaje es recibido por este network service en el dispositivo de B lanzará un evento con
la información de la solicitud a la cuál responde la interfaz gráfica llamando posteriormente a un
método del plugin Intra User Module para aceptar, rechazar o posponer la decisión sobre la solicitud. +

* Si es rechazada el network service de B comunica la decisión a su par en A para que este envíe un
evento informativo y se elimine el registro del Actor Intra User.
* Si es aceptada el network service de B comunica la decisión a su par en A para que este marque en
estado del usuario en el Actor Intra User el valor "Contacto". +

Para no perder estas respuestas, el network service de A guarda estas notificaciones de aceptación o
rechazo hasta que el Actor Intra User confirme su recepción. Estas notificaciones guardadas deben ser
pedidas por el Actor Intra User al iniciarse y procesarlas para actualizar sus registros. +

Hasta no ser un contacto aceptado no podrán darse ciertos servicios a A que involucren a B, como enviar
mensajes y hasta no ser aceptado como contacto de alguna wallet no se podrán usar servicios aún más
específicos como enviar dinero, solicitudes de pago, etc. +
Estas restricciones deben registrarse principalmente en los network services del dispositivo de B.
Es decir, que los network services controlaran los contactos agendados antes de aceptar ciertos
mensajes de otros network services pares. +

== Eventos

Este plugin lanza entonces los eventos de una nueva solicitud que es capturada por la interfaz gráfica
y un evento de nuevas notificaciones que debe escuchar el Actor Intra User para actualizar su información
según rechazos o aceptaciones.