= Nerwork Service Intra User

Veamos el proceso para agregar un contacto desde la sub app Intra User (posiblemente se presentará
con otro nombre al usuario final). +

Supongamos que nos encontramos logueados con la identidad de Intra User A y deseamos agregar al Intra
User B como conexión. Podemos buscar a B desde diversas sub apps como ya hemos mencionado, en este
milestone podría ser desde un tab de una wallet o desde la sub app Intra Users. +
Como buscamos agendarlo como conexión y no como contacto de una wallet en particular lo primero que
hacemos es buscar a B en la sub app Intra User.
 agendar al usuario en el plugin Actor Intra User por lo que debemos almacenar sus datos
allí y enviar la solicitud de conexión con nuestros datos. Para esta tarea necesitamos que el Network
Service Intra User nos de una lista de contactos sobre la que podramos elegir agregar por defecto
(como la típica sugerencia de ¿conoces a...?) y además formas de buscar un contacto en particular siguiendo filtros como el nombre del usuario. +
Cuando encontramos al usuario a agendar y accionamos el inicio del proceso de agendar al usuario (lo
cual podría ser presionar un botón), agregamos un campo en el Actor Intra User con estado "Solicitud
Enviada". El network service envía un mensaje a su par en B con los datos de A solicitando aceptación,
el usuario podrá entonces aceptar o rechazar la solicitud.

* Si es rechazada el network service de B comunica la decisión a su par en A para que este envíe un
evento informativo y se elimine el registro del Actor Intra User.
* Si es aceptada el network service de B comunica la decisión a su par en A para que este marque en
estado del usuario en el Actor Intra User el valor "Contacto". +

Hasta no ser un contacto aceptado no podrán darse ciertos servicios a A que involucren a B, como enviar
mensajes y hasta no ser aceptado como contacto de alguna wallet no se podrán usar servicios aún más
específicos como enviar dinero, solicitudes de pago, etc. +
Estas restricciones deben registrarse principalmente en los network services del dispositivo de B.
Es decir, que los network services controlaran los contactos agendados antes de aceptar ciertos
mensajes de otros network services pares. +
