= Money Request Network Service

A partir de este Milestone podremos enviarle a otros contactos (por el momento de tipo intra user)
requerimientos de pago. Esto significa enviar un mensaje que establece a grandes rasgos un monto a
pagar y una descripción que estipula qué se está pagando. +

Generar un request involucra el envío de un mensaje al destinatario a través de la capa de comunicaciones,
por otro lado al recibir un request se evnía un evento informando la llegada de nuevos requests. Ante
este evento el plugin Money Request de la capa Middleware busca los request pendientes y los registra
confirmando el registro de cada request al network service para que este lo quite de su lista de
pendiantes a entregar. +

El network service debe informar rechazos de los request enviados mediante eventos para que el plugin
Money Request de la capa Middleware actualice su base de datos. Para actualizar al estado de requests
aceptados no intervendrá este plugin sino el transaccional Incoming Intra USer.