package com.bitdubai.fermat_api.layer._14_middleware.app_runtime.enums;

/**
 * Created by ciencias on 2/14/15.
 */
public enum Fragments {

    CWP_SHELL_LOGIN,
    CWP_WALLET_MANAGER_MAIN,
    CWP_WALLET_MANAGER_SHOP,
    CWP_SHOP_MANAGER_MAIN,
    CWP_SHOP_MANAGER_FREE,
    CWP_SHOP_MANAGER_PAID,
    CWP_SHOP_MANAGER_ACCEPTED_NEARBY,
    CWP_WALLET_RUNTIME_WALLET_AGE_KIDS_ALL_BITDUBAI_PROFILE,
    CWP_WALLET_RUNTIME_WALLET_AGE_KIDS_ALL_BITDUBAI_DESKTOP,
    CWP_WALLET_RUNTIME_WALLET_AGE_KIDS_ALL_BITDUBAI_CONTACTS,
    CWP_WALLET_RUNTIME_WALLET_AGE_KIDS_ALL_BITDUBAI_COMMUNITY,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_HOME,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_BALANCE,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_SEND,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_RECEIVE,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_SHOPS,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_REFFIL,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_DISCOUNTS,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_SHOP_SHOP,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_SHOP_PRODUCTS,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_SHOP_REVIEWS,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_SHOP_CHAT,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_SHOP_HISTORY,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_SHOP_MAP,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_ACCOUNTS_DEBITS,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_ACCOUNT_CREDITS,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_ACCOUNTS_ALL,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_CONTACTS_CHAT,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_CONTACTS,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_CONTACTS_SEND,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_CONTACTS_NEW_SEND,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_CONTACTS_RECEIVE,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_CONTACTS_NEW_RECEIVE,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_CHAT_TRX,
    CWP_WALLET_RUNTIME_ADULTS_ALL_AVAILABLE_BALANCE,
    CWP_WALLET_ADULTS_ALL_REQUESTS_RECEIVED,
    CWP_WALLET_ADULTS_ALL_REQUESTS_RECEIVED_HISTORY,
    CWP_WALLET_ADULTS_ALL_REQUEST_SEND,
    CWP_WALLET_ADULTS_ALL_SEND_HISTORY,
    CWP_WALLET_ADULTS_ALL_DAILY_DISCOUNT,
    CWP_WALLET_ADULTS_ALL_WEEKLY_DISCOUNT,
    CWP_WALLET_ADULTS_ALL_MONTHLY_DISCOUNT,
    CWP_WALLET_STORE_MAIN,
    CWP_WALLET_FACTORY_MAIN;

}
