= Wallet Publisher

== Wallet Publisher SubApp

Publicar una wallet significa exponerla en el wallet store para que otros usuarios puedan descargarla.

El Wallet Publisher presenta las wallets que el developer logueado tiene publicadas.
Al igual que otros plug-ins, la información sobre el developer actualmente logueado se obtiene del
plugin Developer de la capa Identity (este plugin provee en su interfaz un método que permite consultar el developer
actualmente logueado).

Al tocar una de estas wallets publicadas se debería poder ingresar a la lista de versiones de la misma. +
Cuando la lista de versiones está desplegada debería permitir ver información de las versiones que
se pueda obtener de la red (número de usuarios, información de la licencia, metadata, etc). +
También podría mostrarse información de la wallet como conjunto (sumando información de todas sus versiones). +

Se debe permitir publicar una nueva wallet pidiéndole al usuario que escoja un WFP y una Versión que
el mismo posea, o publicar una nuevo release de una wallet existente también pidiendo al usuario que
indique el WFP y la versión asociada a la wallet.

Como mencionamos antes, se podrían pensar en mecanismos que le impidan al desarrollador publicar una
wallet que aún no ha sido aceptada por bitDubai (una que no está instalada en la plataforma).
Sin embargo, dado que el desarrollador tiene acceso a todo el código desde su máquina este podría
saltear las restricciones que querramos imponer editando el código y corriendo una versión modificada
de la plataforma.

== Wallet Publisher plugin - Module Layer

== Wallet Publisher plugin - Middleware Layer

Algunas de las funcionalidades específicas de este módulo serán:

* Comunica al Wallet Store Network Service que se tiene una nueva wallet en el catálogo completando
la información de la versión, nombre, id de la wallet, desarrollador y descripción.
* A futuro: llevar algunas estadísticas sobre la wallet. Por ejemplo, cómo ha crecido el número de
usuarios de una wallet o versión de la misma entre un par de sesiones de conexión del desarrollador.

