= Flujos identificados en el Milestone 02

En reuniones con el equipo actual para cerrar el Milestone 02 hemos identificado principalmente dos
flujos a tener en cuenta.
Ellos son: flujo de *producción* y de *desarrollo*.

== Flujo de Desarrollo

Se inicia con la creación de una Wallet, Skin y/o Language en la Wallet Factory hasta su
publicación en el Wallet Store

Involucra los plugines:

* Wallet Factory
* Wallet Publisher
* Wallet Store

*Wallet Factory -> Wallet Publisher -> Wallet Store*

=== Descripción de procesos:

A nivel funcional, los pasos dentro de la _Wallet Factory_ son:
El desarrollador (o diseñador o traductor), crea un proyecto de Wallet Factory Project
luego de haber clonado el repositorio de Fermat y haber modificado una Reference Wallet disponible.
Le pudo haber realizado cambios a su estructura de navegación, skins, etc.

En el proyecto de Wallet Factory creado define y edita estos componentes de la Wallet.
Cuando la edición finaliza y el proyecto se marca como final, el proyecto pasa a estar disponible
en la Wallet Publisher.

A nivel funcional, los pasos dentro de la _Wallet Publisher_ son:
El wallet Publisher debe mostrar todos aquellos proyectos de WPF que están finalizados listos para
ser publicados. Debemos determinar qué información no está definida en el Wallet Factory que
necesitamos para publicarla y eta información se obtiene en
esta sub app.

Una vez obtenida la información necesaria, la función del publisher es pasarle esta información
al Wallet Store para que se encargue de hacerla pública en el catálogo y distribuilrla a los peers
que cualifiquen.


== Flujo de Producción

Al haber publicado el objeto creado en el flujo de desarrollo en el catálogo de la Wallet Store,
la nueva Wallet se propaga al resto de los dispositivos conectados y figura disponible para otros
usuarios instalarla.
El flujo termina cuando la wallet, skin u/o language, se instalan o actualizan en el
nuevo dispositivo.

Involucra los plugines:

* Wallet Store
* Wallet Manager
* Wallet Resources

*Wallet Store -> Wallet Manager -> Wallet Resources -> Instalación -> Disponible en Wallet Manager*

A nivel funcional, los pasos dentro de la _Wallet Store_ son:

Detectar en otro peer si tiene una nueva wallet que no tenga localmente y que aplique a cierto
criterio básico como por ejemplo, corre en la versión de plataforma en la que estoy, si lo nuevo
es un skin y tengo instalada anteriormente la Wallet donde ese skin va a correr, etc.

Si este criterio se cumple, entonces actualizo el catalogo disponible con el nuevo objeto
desde otro peer.
El proceso se inicia con el usuario instalando la wallet.

A nivel funcional, los pasos dentro de la _Wallet Manager_ son:

El wallet manager recibe de parte del store la petición de instalación de una nueva Wallet,
que a su vez le pasa el proceso al Wallet Resources quien es quien finalmente inicia la
instalación del Wallet.

El wallet Manager, terminada la instalación, muestra el nuevo objeto disponible para ser
iniciado normalmente.

A nivel funcional, los pasos dentro de la _Wallet Resources_ son:

este plug in se encarga de iniciar una instalación y desinstalación obteniendo los recursos y
configuraciones de la wallet desde el repositorio de Github.

Al recibir el pedido de una isntalación, obtiene lo necesario desde github y lo guarda localmente
en el dispositivo para hacer la instalación.
Una vez realizada la instalación, el objeto está disponible para ser iniciado desde el
Wallet Manager.


== Puntos pendientes de definir

* Firmado de objetos
* Identidad de usuarios



