package com.bitdubai.fermat_api.layer._10_communication.fmp;

import com.bitdubai.fermat_api.layer._10_communication.fmp.FMPException;

public class MalformedFMPPacketException extends FMPException {
	
	/**
	 * autogenerated serialVersionUID
	 */
	private static final long serialVersionUID = -1102140907777389730L;

	public MalformedFMPPacketException(){
		super();
	}
	
	public MalformedFMPPacketException(final String message){
		super(message);
	}
	
}
