= Wallet Store

== Wallet Store SubApp

La sub app Wallet Store es la encargada de mostrarle al usuario las wallets que tiene disponibles
para instalar. +
En un futuro también debería mostrar las que podría instalar si actualizara su versión de la
plataforma (ńos quedaremos sólo con las que se puede instalar para este milestone). +
La idea es que no se muestre el catálogo de todas las wallets que hay, sino que mostrmos un
subconjunto de interés para el usuario. La sub app pediría al plug-in de la capa module el catálogo
a mostrar. Será tarea de los módulos de capas inferiores resolver qué parte del catálogo proveer. +

La información que queremos mostrar para esta versión incluye:

* Un nombre de la wallet
* El nombre del desarrollador que la creó
* La versión de la wallet
* Una descripción de la wallet

En un futuro querríamos incorporar:

* Calificación de la wallet realizada por otros usuarios.
* Comentarios de otros usuarios.
* Al ingresar a una wallet poder ver otras wallets recomendadas o similares.
* Más información típica como la que podemos ver en google play, amazon, etc.

Queremos que el usuario pueda recorrer el catálogo; al tocar una wallet queeríamos que se despliegue
la información descriptiva de la misma y habilitar la opción para instalar la misma, decir que ya está
instalada.

NOTE: Podríamos cobrar a desarrolladores si desean publicar su wallet más arriba en el wallet store
o figurar según cierta información del usuario, etc.

Sería interesante permitir al usuario buscar wallets que no están en el catálogo del dispositivo.

== Wallet Store plugin - Module Layer

Este plugin conecta el front-end con los plug-ins que manejan la lógica de negocio de los datos que
manipula la app. Es decir, este es el plug-in que le otorga la información al front-end que es generada
por otros plug-ins. Si bien en esta primer implementación su función será delegar el pedido que le hagan
al plugin Wallet Store de la capa Middleware, al incorporar más funciones probablemente aparecerá una
lógica de presentación más elaborada (como por ejemplo, llevar información propia que calcula durante
una sesión del usuario logueado)

== Wallet Store plugin - Middleware Layer

Gran parte de este módulo consistirá en generar la información que se mostrará al usuario. Este
plug-in tomará la información del catálogo del network service de la wallet store y aplicará los
filtros necesarios. +