[[wallet-asset-over-bitcoin-BitDubai-V1]]
== Version 1
    El componente Over Bitcoin Wallet registrara todas las transacciones contables que ocurran en la Reference Asset Wallet, y almacenara dicha transacción en la base de datos,
  de esa manera el componente podra emitir todo los movimientos registrados en el Asset Wallets.


== Plug-in Description

== Plug-in Structure

    fermat-dap-api===>wallet===>fermat-dap-plugin-wallet-asset-over-bitcoin-bitdubai

== Events

== Implementation Details

    Se crearan las siguientes Interfaces:
      bitcoinwalletasset:
         Implementara todo el objeto que manipulara la información de la Asset.

      bitCoinwalletassetmanager:
         Implementara la interfaz publica hacia los otros pluggins.

      dealswithbitcoinwalletassets:
         Implementara la Interfaz BitCoinWalletAssetManager para la interconexion hacia los otros pluggins.

      bitcoinwalletassettransaction:
         Implementara la interfaz para el registro de la transacción involucrada.

      bitcoinwalletassetsubsystem:
         Implementara la interfaz para el comportamiento del Pluggin.