= How to configure a local bitcoin environment to send and receive Bitcoins

The following instructions will let you install the Bitcoin core client and execute it in the regression test (_RegTest_) network.
The regression test network is a local network with zero difficulty and no miners.

== Installing the Bitcoin core client.
* Execute the following commands to download and install the client

[source, linux]
----
sudo apt-add-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install bitcoin-qt
----

* execute the client installed
[source, linux]
----
bitcoin-qt
----

this will start the bitcoin core client in the main (_production_) network. It will start by downloading the entire production blockchain
 and will take days. We need to create a configuration file to fit our purpose.

* create a text file called bitcoin.conf and save it in the default hidden directory ./bitcoin with the following parameters
(in my case the path is /home/rodrigo/.bitcoin)

[source]
----
regtest=1
daemon=1
server=1
rpcuser= [aVeryComplexUserName]
rpcpassword= [aVeryComplexPassword]
rpcport=9000
allowreceivebyip=1
----

* execute again the client installed and verify that the splash screen changed to green and says TestNet network.
[source, linux]
----
bitcoin-qt
----

== Modify the Fermat platform to connect to your local bitcoin network
* get your ip address
* and change it in com.bitdubai.fermat_cry_api.layer.crypto_network.bitcoin.BitcoinManager interface
[source, java]
 public final String REGTEST_SERVER_ADDRESS = "yourIpAddress";

[TIP]
*Remember not to commit this change and upload your IP to the repository.*

== Generate new blocks and add bitcoins to your client.

* in the terminal console, execute the following command
[source, linux]
----
bitcoin-cli setgenerate true 101
----

This command will generate 101 blocks in the network mined by selves. This operation will also add 50 bitcoins to our wallet.

* Each time you generate a new block in your local network, bitcoins will be added to your bitcoin client wallet.
* Now you are ready to send bitcoins to your Fermat wallet.
* If you need to generate new blocks in the network to confirm the transactions, just execute the following command
[source, linux]
----
bitcoin-cli setgenerate true 1
----

* Remember that these bitcoins have zero value and are only valid to your local PC.

== Sending and recieving bitcoins

* Sending bitcoins to your Fermat wallet is the first step. A good tip to get the Basic Wallet Bitcoin Address is to install an aplication
to be able to scan QR code like QtQR.

[source, linux]
----
sudo apt-get install qtqr
----

* Generate an address in the Fermat Bitcoin Wallet and scan it with you pc camera.

* Copy that address in the Send tab of the Bitcoin core client and send as many bitcoins as you want.

* Confirm the bitcoins you just recieved by generating a new block in the blockchain as explained before.