//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.26 at 02:09:24 PM VET 
//


package com.bitdubai.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}platforms"/>
 *         &lt;element ref="{}super_layers"/>
 *         &lt;element ref="{}layers"/>
 *         &lt;element ref="{}processes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "platforms",
    "superLayers",
    "layers",
    "processes"
})
@XmlRootElement(name = "fermat")
public class Fermat {

    @XmlElement(required = true)
    protected Platforms platforms;
    @XmlElement(name = "super_layers", required = true)
    protected SuperLayers superLayers;
    @XmlElement(required = true)
    protected Layers layers;
    @XmlElement(required = true)
    protected Processes processes;

    /**
     * Gets the value of the platforms property.
     * 
     * @return
     *     possible object is
     *     {@link Platforms }
     *     
     */
    public Platforms getPlatforms() {
        return platforms;
    }

    /**
     * Sets the value of the platforms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Platforms }
     *     
     */
    public void setPlatforms(Platforms value) {
        this.platforms = value;
    }

    /**
     * Gets the value of the superLayers property.
     * 
     * @return
     *     possible object is
     *     {@link SuperLayers }
     *     
     */
    public SuperLayers getSuperLayers() {
        return superLayers;
    }

    /**
     * Sets the value of the superLayers property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuperLayers }
     *     
     */
    public void setSuperLayers(SuperLayers value) {
        this.superLayers = value;
    }

    /**
     * Gets the value of the layers property.
     * 
     * @return
     *     possible object is
     *     {@link Layers }
     *     
     */
    public Layers getLayers() {
        return layers;
    }

    /**
     * Sets the value of the layers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Layers }
     *     
     */
    public void setLayers(Layers value) {
        this.layers = value;
    }

    /**
     * Gets the value of the processes property.
     * 
     * @return
     *     possible object is
     *     {@link Processes }
     *     
     */
    public Processes getProcesses() {
        return processes;
    }

    /**
     * Sets the value of the processes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Processes }
     *     
     */
    public void setProcesses(Processes value) {
        this.processes = value;
    }


    @Override
    public String toString() {
        return "Fermat{" +
                "layers=" + layers +
                ", platforms=" + platforms +
                ", superLayers=" + superLayers +
                ", processes=" + processes +
                '}';
    }
}
