= Version 1

== Plug-in Description

Along the system many modules use events to communicate specific information of the state of the platform. For example, there is an event to communicate a variation in the exchange rate of a crypto currency, another event informs when a user logs in, etc. +
For each event we can define a corresponding component called *event listeners* which will be informed every time the event occurs.
The event manager is the plug-in responsable of receiving the events thrown by the system and inform them to the event listeners.

An event listeners have a reference to a module called **event handlers** which is the component invoked to react when an event occur. +
The event handler try to execute an action when he is invoke by the listener. This action can possibly fail and throw an exception (java exception). However, as we said before, events have an informative role so it is not correct for the system to throw an exception to the event listener who invoked the handler neither to the module that threw the event. +
To solve this problem, the event listener catch the exception and gives it to a component called *event monitor* which register the exceptions and inform the platform. +
We expect that in the future the platform will be able to make decisions according to the information provided by the event monitor.s