= Metodos sin uso en fermat

- Constructors

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-wallet-store-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/wallet_store/developer/bitdubai/version_1/structure/catalog/Translator.java

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-wallet-store-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/wallet_store/developer/bitdubai/version_1/structure/catalog/Skin.java

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-wallet-store-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/wallet_store/developer/bitdubai/version_1/structure/catalog/Language.java

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-wallet-store-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/wallet_store/developer/bitdubai/version_1/structure/catalog/CatalogItemImpl.java

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-wallet-store-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/wallet_store/developer/bitdubai/version_1/structure/catalog/DetailedCatalogItemImpl.java

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-wallet-store-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/wallet_store/developer/bitdubai/version_1/structure/networkService/WalletStoreNetworkServiceMessage.java

* /DMP/android/sub_app/fermat-dmp-android-sub-app-intra-user-bitdubai/src/main/java/com/bitdubai/sub_app/intra_user/common/adapters/ImagesAdapter.java

* /DMP/android/sub_app/fermat-dmp-android-sub-app-intra-user-bitdubai/src/main/java/com/bitdubai/sub_app/intra_user/common/adapters/IntraUserConnectionsAdapter.java

* /DMP/android/sub_app/fermat-dmp-android-sub-app-intra-user-bitdubai/src/main/java/com/bitdubai/sub_app/intra_user/common/models/WalletStoreListItem.java

* /DMP/android/sub_app/fermat-dmp-android-sub-app-intra-user-bitdubai/src/main/java/com/bitdubai/sub_app/intra_user/session/IntraUserSubAppSession.java

* /DMP/android/sub_app/fermat-dmp-android-sub-app-wallet-factory-bitdubai/src/main/java/com/bitdubai/sub_app/wallet_factory/session/WalletFactorySubAppSession.java

* /DMP/android/sub_app/fermat-dmp-android-sub-app-wallet-publisher-bitdubai/src/main/java/com/bitdubai/sub_app/wallet_publisher/adapters/InformationPublishedComponentAdapter.java

* /DMP/android/sub_app/fermat-dmp-android-sub-app-wallet-publisher-bitdubai/src/main/java/com/bitdubai/sub_app/wallet_publisher/adapters/WalletFactoryProjectsAdapter.java

* /DMP/android/sub_app/fermat-dmp-android-sub-app-wallet-store-bitdubai/src/main/java/com/bitdubai/sub_app/wallet_store/common/adapters/ImagesAdapter.java

* /DMP/android/sub_app/fermat-dmp-android-sub-app-wallet-store-bitdubai/src/main/java/com/bitdubai/sub_app/wallet_store/session/WalletStoreSubAppSession.java

* /DMP/plugin/identity/fermat-dmp-plugin-identity-publisher-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/identity/publisher/publisher/bitdubai/version_1/structure/PublisherIdentityRecord.java

* /DMP/plugin/identity/fermat-dmp-plugin-identity-publisher-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/identity/publisher/publisher/bitdubai/version_1/PublisherIdentityPluginRoot.java

* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-bank-notes-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/bank_notes/developer/bitdubai/version_1/beans/dto/Bill.java

* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-bank-notes-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/bank_notes/developer/bitdubai/version_1/beans/dto/Coin.java

* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-bank-notes-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/bank_notes/developer/bitdubai/version_1/beans/dto/Depot.java

* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-bank-notes-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/bank_notes/developer/bitdubai/version_1/beans/dto/ItemByAccount.java

* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-bank-notes-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/bank_notes/developer/bitdubai/version_1/beans/dto/ItemByDepot.java

* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-bank-notes-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/bank_notes/developer/bitdubai/version_1/beans/dto/Record.java

* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-wallet-publisher-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/wallet_publisher/developer/bitdubai/version_1/structure/ImageMiddlewareImpl.java

* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-wallet-publisher-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/wallet_publisher/developer/bitdubai/version_1/structure/InformationPublishedComponentMiddlewareImpl.java

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-template-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/template/developer/bitdubai/version_1/structure/TemplateNetworkServiceMessage.java




- Method Private

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-wallet-store-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/wallet_store/developer/bitdubai/version_1/structure/database/WalletStoreCatalogDatabaseDao.java

    private DatabaseTransaction getDatabaseTransaction()

* /DMP/plugin/module/fermat-dmp-plugin-module-wallet-store-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/module/wallet_store/developer/bitdubai/version_1/structure/WalletStoreModuleManager.java

    private InstallationStatus getSkinInstallationStatus(UUID skinId)

    private InstallationStatus getLanguageInstallationStatus(UUID languageId)

    private WalletStoreSkin getWalletStoreSkin(final Skin skin, final InstallationStatus installationStatus)

    private com.bitdubai.fermat_api.layer.ccp_identity.designer.interfaces.DesignerIdentity getDesigner(UUID designerId)

    private WalletStoreLanguage getWalletStoreLanguage(final Language language, final InstallationStatus installationStatus)

    private DeveloperIdentity getDeveloper(UUID developerId)

* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-wallet-publisher-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/wallet_publisher/developer/bitdubai/version_1/database/InformationPublishedComponentDao.java

    private ComponentVersionDetailMiddlewareImpl constructComponentVersionDetailMiddlewareFrom(DatabaseTableRecord record) throws InvalidParameterException

    private ImageMiddlewareImpl constructImageMiddlewareFrom(DatabaseTableRecord record) throws FileNotFoundException, CantCreateFileException

* /DMP/plugin/module/fermat-dmp-plugin-module-wallet-store-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/module/wallet_store/developer/bitdubai/version_1/structure/WalletStoreModuleManager.java

    private InstallationStatus getSkinInstallationStatus(UUID skinId) throws CantGetItemInformationException

    private InstallationStatus getLanguageInstallationStatus(UUID languageId) throws CantGetItemInformationException

    private WalletStoreSkin getWalletStoreSkin(final Skin skin, final InstallationStatus installationStatus)

    private com.bitdubai.fermat_api.layer.ccp_identity.designer.interfaces.DesignerIdentity getDesigner(UUID designerId) throws CantGetDesignerException

    private WalletStoreLanguage getWalletStoreLanguage(final Language language, final InstallationStatus installationStatus)

    private DeveloperIdentity getDeveloper(UUID developerId) throws CantGetDeveloperException

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-crypto-transmission-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/crypto_transmission/developer/bitdubai/version_1/CryptoTransmissionNetworkServicePluginRoot.java

    private void moneyReceived()

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-wallet-resources-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/wallet_resources/developer/bitdubai/version_1/database/NetworkServicesWalletResourcesDAO.java

    private Repository getRepository(String repositoryName,UUID skinId) throws CantGetRepositoryPathRecordException, com.bitdubai.fermat_ccp_plugin.layer.network_service.wallet_resources.developer.bitdubai.version_1.exceptions.RepositoryNotFoundException



- Method Public
* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-wallet-store-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/wallet_store/developer/bitdubai/version_1/structure/networkService/database/IncomingMessageDAO.java

    public WalletStoreNetworkServiceMessage findById(String id) throws CantReadRecordDataBaseException

    public List<WalletStoreNetworkServiceMessage> findAll() throws CantReadRecordDataBaseException

    public List<WalletStoreNetworkServiceMessage> findAll(String columnName, String columnValue) throws CantReadRecordDataBaseException

    public List<WalletStoreNetworkServiceMessage> findAll(Map<String, Object> filters) throws CantReadRecordDataBaseException

    public void delete(Long id) throws CantDeleteRecordDataBaseException

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-wallet-store-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/wallet_store/developer/bitdubai/version_1/structure/networkService/database/OutgoingMessageDAO.java

    public WalletStoreNetworkServiceMessage findById(String id) throws CantReadRecordDataBaseException

    public List<WalletStoreNetworkServiceMessage> findAll() throws CantReadRecordDataBaseException

    public List<WalletStoreNetworkServiceMessage> findAll(Map<String, Object> filters) throws CantReadRecordDataBaseException

    public void delete(Long id) throws CantDeleteRecordDataBaseException

* DMP/plugin/network_service/fermat-dmp-plugin-network-service-wallet-store-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/wallet_store/developer/bitdubai/version_1/structure/networkService/WalletStoreNetworkServiceLocalAgent.java

    public void sendMessage(Message message)

    public String getRemoteNetworkServicePublicKey()

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-wallet-store-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/wallet_store/developer/bitdubai/version_1/structure/networkService/WalletStoreNetworkServiceMessage.java

    public void setSignature(String signature)

* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-wallet-store-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/wallet_store/developer/bitdubai/version_1/structure/database/WalletStoreMiddlewareDatabaseDao.java

    public void setPluginId(UUID pluginId)

* /DMP/plugin/module/fermat-dmp-plugin-module-wallet-store-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/module/wallet_store/developer/bitdubai/version_1/structure/WalletStoreModuleManager.java

    public WalletStoreDetailedCatalogItem getCatalogItemDetails(UUID walletCatalogId) throws CantGetWalletsCatalogException

* /DMP/android/sub_app/fermat-dmp-android-sub-app-intra-user-bitdubai/src/main/java/com/bitdubai/sub_app/intra_user/adapters/CheckBoxListItem.java

    public void setIntraUserIdentity(IntraUserLoginIdentity intraUserIdentity)

* /DMP/android/sub_app/fermat-dmp-android-sub-app-intra-user-bitdubai/src/main/java/com/bitdubai/sub_app/intra_user/common/models/IntraUserConnectionListItem.java

     public void setProfilePhrase(String profilePhrase)

    public void setProfileImage(byte[] profileImage)

    public void setConnectionStatus(String connectionStatus)

* /DMP/android/sub_app/fermat-dmp-android-sub-app-intra-user-bitdubai/src/main/java/com/bitdubai/sub_app/intra_user/fragments/MainActivityFragment.java

    public static MainActivityFragment newInstance()

* /DMP/android/sub_app/fermat-dmp-android-sub-app-intra-user-bitdubai/src/main/java/com/bitdubai/sub_app/intra_user/util/CommonLogger.java

    public static void info(String tag, String msg)

    public static void debug(String tag, String msg)

    public static void error(String tag, String msg)

* /DMP/android/sub_app/fermat-dmp-android-sub-app-wallet-store-bitdubai/src/main/java/com/bitdubai/sub_app/wallet_store/util/CommonLogger.java

    public static void info(String tag, String msg)

    public static void debug(String tag, String msg)

    public static void error(String tag, String msg)

* /DMP/plugin/actor/fermat-dmp-plugin-actor-intra-user-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/actor/intra_user/developer/bitdubai/version_1/exceptions/CantInitializeIntraUserActorDatabaseException.java

    public CantInitializeIntraUserActorDatabaseException()

* /DMP/plugin/engine/fermat-dmp-plugin-engine-sub-app-runtime-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/engine/app_runtime/developer/bitdubai/version_1/structure/RuntimeSubApp.java

    public void addLanguagePackage (LanguagePackage languagePackage)

* /DMP/plugin/identity/fermat-dmp-plugin-identity-publisher-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/identity/publisher/publisher/bitdubai/version_1/structure/PublisherIdentityDao.java

    public void setDeveloperIdentityDatabaseFactory(PublisherIdentityDatabaseFactory databaseFactory)

* /DMP/plugin/identity/fermat-dmp-plugin-identity-publisher-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/identity/publisher/publisher/bitdubai/version_1/structure/PublisherIdentityRecord.java

    public void setAlias (String alias)

    public void setPublicKey (String publicKey)

* /DMP/plugin/identity/fermat-dmp-plugin-identity-publisher-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/identity/publisher/publisher/bitdubai/version_1/PublisherIdentityPluginRoot.java

    public void setPluginId(UUID pluginId)

    public void setServiceStatus(ServiceStatus serviceStatus)

    public void setDao(PublisherIdentityDao dao)

* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-wallet-navigation-structure-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/navigation_structure/developer/bitdubai/version_1/database/WalletNavigationStructureMiddlewareDao.java

    public void createNavigationStructure(WalletNavigationStructure walletNavigationStructure) throws CantCreateEmptyWalletNavigationStructureException

    public void deleteNavigationStructure(String publicKey) throws CantDeleteNavigationStructureException, NavigationStructureNotFoundException

    public List<WalletNavigationStructure> findAllNavigationStructuresByActivity(String activity) throws CantListNavigationStructuresException

    public WalletNavigationStructure findWalletNavigationStructureById(String id) throws CantGetWalletNavigationStructureException, NavigationStructureNotFoundException

    public List<WalletNavigationStructure> findAllNavigationStructuresById(String id) throws CantListNavigationStructuresException

    public void updateWalletNavigationStructure(WalletNavigationStructure walletNavigationStructure) throws NavigationStructureNotFoundException, CantUpdateNavigationStructureException

    private Database openDatabase() throws CantExecuteDatabaseOperationException

    private DatabaseTable getDatabaseTable(String tableName)

* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-wallet-publisher-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/wallet_publisher/developer/bitdubai/version_1/database/ComponentVersionDetailDao.java

    public ComponentVersionDetail findById(String id) throws CantReadRecordDataBaseException

    public List<ComponentVersionDetail> findAll() throws CantReadRecordDataBaseException

    public List<ComponentVersionDetail> findAll(Map<String, Object> filters) throws CantReadRecordDataBaseException

    public void update(ComponentVersionDetailMiddlewareImpl entity) throws CantUpdateRecordDataBaseException

    public void delete(Long id) throws CantDeleteRecordDataBaseException

* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-wallet-publisher-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/wallet_publisher/developer/bitdubai/version_1/database/InformationPublishedComponentDao.java

    public List<InformationPublishedComponent> findAll() throws CantReadRecordDataBaseException

    public void delete(Long id) throws CantDeleteRecordDataBaseException

* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-wallet-publisher-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/wallet_publisher/developer/bitdubai/version_1/database/ScreensShotsComponentsDao.java

    public Image findById(String id) throws CantReadRecordDataBaseException

    public List<Image> findAll() throws CantReadRecordDataBaseException

    public List<Image> findAll(Map<String, Object> filters) throws CantReadRecordDataBaseException

    public void update(ImageMiddlewareImpl entity) throws CantUpdateRecordDataBaseException

    public void delete(Long id) throws CantDeleteRecordDataBaseException

* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-wallet-skin-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/wallet_skin/developer/bitdubai/version_1/database/WalletSkinMiddlewareDao.java

    public void updateSkin(WalletSkin walletSkin) throws CantUpdateSkinException, SkinNotFoundException

* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-wallet-store-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/wallet_store/developer/bitdubai/version_1/structure/database/WalletStoreMiddlewareDatabaseDao.java

    public void setPluginId(UUID pluginId)

* /DMP/plugin/module/fermat-dmp-plugin-module-wallet-store-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/module/wallet_store/developer/bitdubai/version_1/structure/WalletStoreModuleManager.java

    public WalletStoreDetailedCatalogItem getCatalogItemDetails(UUID walletCatalogId) throws CantGetWalletsCatalogException

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-crypto-transmission-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/crypto_transmission/developer/bitdubai/version_1/CryptoTransmissionNetworkServicePluginRoot.java

    public void sendMoney()

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-intra-user-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/intra_user/developer/bitdubai/version_1/structure/IncomingMessageDataAccessObject.java

    public IncomingIntraUserNetworkServiceMessage findById(String id) throws CantReadRecordDataBaseException

    public List<IncomingIntraUserNetworkServiceMessage> findAll() throws CantReadRecordDataBaseException

    public List<IncomingIntraUserNetworkServiceMessage> findAll(String columnName, String columnValue) throws CantReadRecordDataBaseException

    public List<IncomingIntraUserNetworkServiceMessage> findAll(Map<String, Object> filters) throws CantReadRecordDataBaseException

    public void delete(Long id) throws CantDeleteRecordDataBaseException

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-intra-user-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/intra_user/developer/bitdubai/version_1/structure/IntraUserNetworkServiceLocal.java

    public void sendMessage(Message message)

    public String getRemoteNetworkServicePublicKey()

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-intra-user-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/intra_user/developer/bitdubai/version_1/structure/IntraUserNetworkServiceManager.java

    public void connectTo(String remoteNetworkServicePublicKey)

    public void closeConnection(String remoteNetworkServicePublicKey)

    public IntraUserNetworkServiceLocal getIntraUserNetworkServiceLocalInstance(String remoteNetworkServicePublicKey)

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-intra-user-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/intra_user/developer/bitdubai/version_1/structure/IntraUserNetworkServiceMessage.java

    public void setSignature(String signature)

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-intra-user-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/intra_user/developer/bitdubai/version_1/structure/OutgoingMessageDataAccessObject.java

    public OutgoingIntraUserNetworkServiceMessage findById(String id) throws CantReadRecordDataBaseException

    public List<OutgoingIntraUserNetworkServiceMessage> findAll() throws CantReadRecordDataBaseException

    public List<OutgoingIntraUserNetworkServiceMessage> findAll(Map<String, Object> filters) throws CantReadRecordDataBaseException

    public void delete(Long id) throws CantDeleteRecordDataBaseException

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-template-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/template/developer/bitdubai/version_1/database/IncomingMessageDao.java

    public IncomingTemplateNetworkServiceMessage findById(String id) throws CantReadRecordDataBaseException

    public List<IncomingTemplateNetworkServiceMessage> findAll() throws CantReadRecordDataBaseException

    public List<IncomingTemplateNetworkServiceMessage> findAll(String columnName, String columnValue) throws CantReadRecordDataBaseException

    public List<IncomingTemplateNetworkServiceMessage> findAll(Map<String, Object> filters) throws CantReadRecordDataBaseException

    public void update(IncomingTemplateNetworkServiceMessage entity) throws CantUpdateRecordDataBaseException

    public void delete(Long id) throws CantDeleteRecordDataBaseException

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-template-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/template/developer/bitdubai/version_1/database/OutgoingMessageDao.java

    public OutgoingTemplateNetworkServiceMessage findById(String id) throws CantReadRecordDataBaseException

    public List<OutgoingTemplateNetworkServiceMessage> findAll() throws CantReadRecordDataBaseException

    public List<OutgoingTemplateNetworkServiceMessage> findAll(Map<String, Object> filters) throws CantReadRecordDataBaseException

    public void delete(Long id) throws CantDeleteRecordDataBaseException

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-template-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/template/developer/bitdubai/version_1/structure/TemplateNetworkServiceLocal.java

    public void sendMessage(Message message)

    public String getRemoteNetworkServicePublicKey()

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-template-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/template/developer/bitdubai/version_1/structure/TemplateNetworkServiceManager.java

    public void connectTo(String remoteNetworkServicePublicKey)

    public void closeConnection(String remoteNetworkServicePublicKey)

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-wallet-resources-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/wallet_resources/developer/bitdubai/version_1/database/NetworkServicesWalletResourcesDAO.java

    public void createRepository(Repository repository,UUID skinId) throws CantCreateRepositoryException



- Class

* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-wallet-store-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/wallet_store/developer/bitdubai/version_1/structure/networkService/database/WalletStoreNetworkServiceDatabaseFactory.java
* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-wallet-store-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/wallet_store/developer/bitdubai/version_1/structure/networkService/WalletStoreNetworkServiceManager.java
* /DMP/android/sub_app/fermat-dmp-android-sub-app-intra-user-bitdubai/src/main/java/com/bitdubai/sub_app/intra_user/fragments/RegisterIntraUserFragment.java
* /DMP/android/sub_app/fermat-dmp-android-sub-app-shop-manager-bitdubai/src/main/java/com/bitdubai/sub_app/shop_manager/fragment/ShopDesktopFragment.java
* /DMP/android/sub_app/fermat-dmp-android-sub-app-wallet-factory-bitdubai/src/main/java/com/bitdubai/sub_app/wallet_factory/fragment/version_3/utils/BusProvider.java
* /DMP/android/sub_app/fermat-dmp-android-sub-app-wallet-factory-bitdubai/src/main/java/com/bitdubai/sub_app/wallet_factory/fragment/version_3/utils/FragmentEvent.java
* /DMP/android/sub_app/fermat-dmp-android-sub-app-wallet-factory-bitdubai/src/main/java/com/bitdubai/sub_app/wallet_factory/fragment/version_3/utils/SmartFragmentStatePagerAdapter.java
* /DMP/android/sub_app/fermat-dmp-android-sub-app-wallet-factory-bitdubai/src/main/java/com/bitdubai/sub_app/wallet_factory/MyLayoutInflaterFactory.java
* /DMP/android/sub_app/fermat-dmp-android-sub-app-wallet-manager-bitdubai/src/main/java/com/bitdubai/sub_app/wallet_manager/WalletManagerSubApp.java
* /DMP/plugin/actor/fermat-dmp-plugin-actor-intra-user-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/actor/intra_user/developer/bitdubai/version_1/exceptions/CantGetIntraUserActorException.java
* /DMP/plugin/composite_wallet/fermat-dmp-plugin-composite-wallet-multi-account-wallet-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/composite_wallet/multi_account_wallet/developer/bitdubai/version_1/exceptions/CantCalculateBalanceException.java
* /DMP/plugin/composite_wallet/fermat-dmp-plugin-composite-wallet-multi-account-wallet-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/composite_wallet/multi_account_wallet/developer/bitdubai/version_1/exceptions/CantInitializeWalletException.java
* /DMP/plugin/composite_wallet/fermat-dmp-plugin-composite-wallet-multi-account-wallet-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/composite_wallet/multi_account_wallet/developer/bitdubai/version_1/interfaces/AccountService.java
* /DMP/plugin/composite_wallet/fermat-dmp-plugin-composite-wallet-multi-account-wallet-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/composite_wallet/multi_account_wallet/developer/bitdubai/version_1/interfaces/WalletService.java
* /DMP/plugin/composite_wallet/fermat-dmp-plugin-composite-wallet-multi-account-wallet-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/composite_wallet/multi_account_wallet/developer/bitdubai/version_1/MultiAccountWalletCompositeWalletPluginRoot.java
* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-wallet-language-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/wallet_language/developer/bitdubai/version_1/utils/RepositoryManager.java
* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-wallet-manager-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/wallet_manager/developer/bitdubai/version_1/structure/WalletManagerMiddlewareInstallationInformation.java
* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-wallet-navigation-structure-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/navigation_structure/developer/bitdubai/version_1/developerUtils/WalletnavigationStructureMiddlewareDeveloperDatabaseFactory.java
* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-wallet-settings-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/wallet_settings/developer/bitdubai/version_1/structure/WalletSettingsConstants.java
* /DMP/plugin/middleware/fermat-dmp-plugin-middleware-wallet-skin-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/middleware/wallet_skin/developer/bitdubai/version_1/utils/RepositoryManager.java
* /DMP/plugin/module/fermat-dmp-plugin-module-intra-user-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/module/intra_user/developer/bitdubai/version_1/structure/IntraUsersModuleLoginConstants.java
* /DMP/plugin/module/fermat-dmp-plugin-module-wallet-manager-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/module/wallet_manager/developer/bitdubai/version_1/event_handlers/NavigationStructureUpdatedEventHandler.java
* /DMP/plugin/module/fermat-dmp-plugin-module-wallet-manager-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/module/wallet_manager/developer/bitdubai/version_1/event_handlers/UserCreatedEventHandler.java
* /DMP/plugin/module/fermat-dmp-plugin-module-wallet-manager-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/module/wallet_manager/developer/bitdubai/version_1/event_handlers/UserLoggedInEventHandler.java
* /DMP/plugin/module/fermat-dmp-plugin-module-wallet-manager-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/module/wallet_manager/developer/bitdubai/version_1/event_handlers/WalletCreatedEventHandler.java
* /DMP/plugin/module/fermat-dmp-plugin-module-wallet-manager-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/module/wallet_manager/developer/bitdubai/version_1/event_handlers/WalletResourcesInstalledEventHandler.java
* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-crypto-addresses-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/crypto_addresses/developer/bitdubai/version_1/event_handlers/IntraUserCreatedEventHandler.java
* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-intra-user-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/intra_user/developer/bitdubai/version_1/event_handlers/UserLoggedInEventHandler.java
* /DMP/plugin/network_service/fermat-dmp-plugin-network-service-intra-user-bitdubai/src/main/java/com/bitdubai/fermat_ccp_plugin/layer/network_service/intra_user/developer/bitdubai/version_1/event_handlers/UserLoggedOutEventHandler.java







