= Definitions Layer

At the moment this layer provides definitions to the others layers like the list of all the crypto currencies supported by the platform, list of plug-ins, list of addons, etc. +
It also provides some standard implementations of common pieces of code like asymmetric encryption methods and currency conversion calculation methods. +

Some folders and their description:

crypto/asymmetric:: Package that provide asymmetric encryption methods using eliptic curve cryptography.
crypto/util:: related classes for the asymmetric package implementation.
developer:: (*draft of a*) Class related to manage the information of a developer, like email, name and other information.
event:: We can also find the definition of the EventMonitor, PlatformEvent and DeasWithEventMonitor interfaces. 
NOTE: This classes may be relocated to the platform service layer. +

diagrams/wallets:: *classes with not quite clear purpose*
enums:: Enums that represent different lists like plug-ins, addons, crypto currencies, fiat currencies, etc.
Money:: *Containers classes (classes with setter and getters) for different data. Not entirely well implemented (for example, they use double to represent currency amounts instead of long)*

util:: Simple methods that may appear along the platform and should be implemented in a standard way like money conversion calculations.
