[[Fermat-DMP-NetworkServiceLayer]]
= Network Service Layer

== Layer Description

The plug-ins in this layer are the ones that let the functionality of the platform transcend a single device to let different users interact with each other over the platform. This layer is the main consumer of the <<Fermat-P2P-CommunicationLayer,communication layer>> services. +

The modules in the world layer also implement interaction with entities that live outside the device, but in that layer the components we interact with live outside the platform. +

There are some common patterns in the way all the network services (the plug-ins in this layer) act. +
Let's say we have two devices A and B and a network service that is implemented in both devices. The network service implementations will communicate as pairs, i.e. the  network service implementation of A will interact directly (in a logical way) to the  implementation in B and vice versa. Physically the communication will be conducted trough the communication layer but the components will interact as if they where talking directly to each other (as if they were in the same device). +

To implement this, each plug-in (network service) has two special classes. One represent the local network service and the other represent the remote network service. +
The remote network service class internally has a connection provided by communication layer. When two devices A and B interact trough a network service we have this imageMiddleware:

----
       Device A           Device B
    +-------------+    +-------------+
    | +---------+ |    | +---------+ |
    | |  Local  | |    | | Remote  | |
    | | Network |========| Network | |
    | | Service | |    | | Service | |
    | +---------+ |    | +---------+ |
    |      *      |    |      *      |
    |      *      |    |      *      |    
    |      *      |    |      *      |
    | +---------+ |    | +---------+ |
    | | Remote  | |    | |  Local  | |
    | | Network |========| Network | |
    | | Service | |    | | Service | |
    | +---------+ |    | +---------+ |
    +-------------+    +-------------+
 
 Reference:
      ====  connection
      ****  interaction
----

Network services have a pair of cryptography asymmetric keys. They use this keys to identify themself and sign the messages they communicate through the network.

== Plug-ins in this layer