[[Fermat-DMP-CryptoTransactionLayer]]
= Crypto Transaction Layer

[[Fermat-DMP-CryptoTransactionLayer-LayerDescription]]
== Layer Description

Transactions are one of the core functionalities developed over Fermat. +
Fermat uses crypto currencies to transfer the real value from a user to another, but we have to remember that you can make transactions of other assets apart from crypto currencies. +
For example, we can transfer 100 dollars from one wallet to another. The mechanism to do this involve the value transaction which is managed by transferring an amount of crypto currency like bitcoin equivalent to 100 dollars between the users and an information transaction which provide the information about the meaning of those bitcoins. In this case the information would be that the bitcoins sent by the crypto network are represented as 100 dollars. +

Therefore, when we make a transaction in Fermat we can identify two components: *meta data* and *value*. +
The value at this moment is stored at a crypto vault, specifically under a crypto addresses managed managed by the vault plugin. On the other hand the information tell us, among other things, which and how much fiat currency or other asset is beign transmitted. +

The meta data and the value travel through different channels, so they will be be acknowledged by a device at different moments in time. This means that we can receive a notification that 100 dollars have been sent to us before we get any new bitcoins that represent the value or vice versa, we can get new bitcoins before receiving the notification of what those bitcoins represent and why they have been sent. +

The responsibility of this layer is to keep these concepts synchronized and within each device the transactional and balance information in a consistent state. The plug-ins that live here detect the arrival of value and information and will update the balances of the system vaults and wallets in an atomic transactional way, i.e. they will update things only when both meta data *and* value are acknowledged. +
No loss of value nor meta data can be permitted. The mechanisms implemented by this layer will need to contemplate many different kinds of problems (device shut down, network failure, etc.).

NOTE: The plug-ins in this layer will need to communicate with the wallets and crypto vaults using events or at least a more complex mechanism that simple method call. The plug-ins need to know that the information inside the wallets and volt was actually updated and persisted before ending the synchronization protocol.

In the next section we will explore a general idea behind the protocols and failures considered in the design of this layer.

== Transaction Data Structure

To attack the problems we deal with in this layer we will need to design a few data structures to contain and share important information. +
To simplify the analysis let's give a name to the data strcutures that contains the value and information associated to the fermat transaction. We will call them TransactionInformation and MetaTransactionInformation respectively. +

As we will get the value and meta-value separetely and in no predictable order we will introduce in the MetaTransactionInformation a reference to the associated TransactionInformation. In this way we will be able to know when we have all the information needed to reflect the transaction in the wallets among other components. +

The TransactionInformation will store.

* The crypto currency we are dealing with as value.
* The amount of crypto currency. 
* A transaction identifier that distinguish the crypto transaction.
* The source crypto address of the transaction.
* The destination crypto address of the transaction.
* The timestamp that stablish the creation time of the transaction.

NOTE: In a single crypto transaction could be bundled many meta transactions. (Think for the future)

The MetaTransactionInformation will store:

. The asset represented by the transaction (fiat currency, bonds, etc)
. A representation of relevant information associated to the asset, e.g. in fiat currency would be the amount of currency involved.
. The transaction identifier of the associated TransactionInformation.
. The timestamp that stablish the creation time of the transaction. 

NOTE: We could consider as a simple secutiry mechanism to ask for this timestamp to be the same timestamp present in the associated TransactionInformation.

This cointainers descriptions are a draft presentation. We will add some fields to them to attack the syncronization problems. +

An important aspect to consider is that lower layers (like network services and crypto networks) will interact with this containers as they are the layers that will give us this information. +

[[Fermat-DMP-CryptoTransactionLayer-TransactionTransferProtocol]]
== Transaction Transference Protocols

:leveloffset: 2
include::protocols/transactionTransferenceProtocol-v1.asciidoc[]

:leveloffset: 2
include::protocols/transactionTransferenceProtocol-v2.asciidoc[]

== Plug-ins in this layer

:leveloffset: 2
include::incomingCrypto/developersIndex.asciidoc[]

:leveloffset: 2
include::outgoingCrypto/developersIndex.asciidoc[]

