== FERMAT Crypto Currency Platform
This platform provides the niche wallets to manage existing crypto currencies - Bitcoin, Litecoin, etc - and also the resources to develop wallets of new cryptocurrencies invented in the future. + 
For a *niche wallet* to run, we need reference wallets and underlying plug-ins to grant:

. user identification 
. device identification
. cryptonetwork services to allow connection to existing cryptocurrencies networks for *transporting value*
. cyptoaddress management (addressbook)
. network services for *transportin meta-data* 
. world services ( to allow access to information provided from services living in the web like exchange rates,...)
. transaction layer ( to allow the broadcasting of transaction created in a wallet)

The essential user identity introduced in this platform is the *device user* 
The main actor identity is the *plug-in developer*. +

=== Bitcoin Wallet
This wallet is one of FERMAT's basic building block to allow interaction with the
most popular cryptonetwork: Bitcoin. + 
FERMAT's Bitcoin's Niche *Reference Wallet*  is a _basic wallet_ in terms of its functionalities, even simpler as other popular BTC wallets on the market. This is so  to maximize its ulterior reutilisation. + 
This wallet provides the minimum necessary functionalities to perform a succesful transaction of Bitcoins: (+)

* to make a payment in BTC ( send value to a BTC Wallet owner)
* to receive payments in BTC
* to show the transactions 
* to show the balance of the wallet
* to show a basic contacts list ( username and cryptoaddress related to each contact)

The wallet prompts the user to provide a *password* ( or *passphrase* ) on first run. Then it generates a pair of privat key/public Key for him, and derived from it, a valid _bitcoin address_ and the QR-Code image associated with it.
When the user decides to send a payment, he enteres the amount and chooses the destination among the addresses stored in the contact's list, the wallet software creates a transaction with the valid format of a bitcoin transaction, it signes the transaction with the wallet's user unique digital signature (derived from his privat/public key), and sends it to the bitcoin network to be propagated among the active nodes.,s and when it is confirmed by others, it becomes part of the blockchain. When the transaction is confirmed by a mining node, it is written inside a transaction block of a new bitcoin blockchain's block. +
At this stage, the BTC amoun was really "spent" i.e. transfered from the wallet's user to the destination user.  
The Bi-Wa will then be able to show its up-dated balance, and also the succesful transaction in the wallet's transaction's log.


NOTE: the simplicity of this wallet is maximized. Bi-Wa does NOT handles payment or money request and and it is _wether_ interconnected with other wallets _not_ showing anything else but plain BTC currency. (no FIAT money abstraction!)

=== Bitcoin Loss Protected Wallet 
BLP is the second *Reference Wallet* developed by FERMAT, and its main goal is to protect the user from losing money when attemping to spend 
Bitcoin at a change curse lower that the price when that Bitcoin amount was purchased (entered the wallet). +
The new functionalities added are:

* to store the *exchange rate* when a BTC amount is received in the wallet
* to check the *exchange rate* when the user attemps to spend an amount of BTC and to freeze the funds if they are below the *purchase price* 


