
== Chapter 1: Fermat Master Plan

As a Master Plan, Fermat has it's own vision of how a collaborative project should be carried out. The main concept is to define a large master plan far into the future, and start building it phase by phase adjusting the target when needed. It is designed in this way to absorb the efforts of thousands of contributors over the years into a unified architectural vision. +

After the pioneer step of Sakamoto who gave rise to *Bitcoin* and its revolutionary blockchain technology, in the last years, there has been a lot of fin tech investment money given to a myriad of startup initiating in this industry. This fostered the next evolutionary step resumend in the so called *"cryptocurrency 2.0"*, although its development has still not reached the level of mass adoption as expected. Maybe the evident  unbalance between  the considerable investment of funds and effort and the few global and lasting result obtained until now lay in the following reason: there is so much that has to be done to master this technology, that any isolated effort  trying to build something useful starting form zero point seems almost too much and too risky to obtain the necessary support. However, taking into consideration many sucessful *open source* projects in the software industry and other sustainable *global projects* , the Fermat Community believes to be able to find and implement the solutions to the challenges mentioned in their purpose and mission by using the systemic approach of *collaborative environments*.

=== Foundations 

Foundational services in Fermat's master plan can described following the analogy of the case of building a modern city. 

. First, we need the ground were to build :: 
in this case, the ground is all the available technology available today in internet, specially the available open source software, and all the devices and network technologies that let digital communication be available at a massive level. 
.Then, we need to lay down the pipes, tubes, conduits and wires (basic infrastructure) ::  
this in provided by the the _Fermat Core Platform_, which initilizes the entire system starting every plugin and unfolding the infrastructure. 
. After that, the basics services can be granted (like water, electricity, gas, etc) ::
** connection to the diferent Operating Systems  
** interconnectivity to cryptonetworks and blockchain services providers
** P2P communication of the devices running Fermat 
.Later on, the  first "building in the city" is created, similar to a huge "main entrance hall" ::
systems users are identified, low level plugins are recognized, communications services are provided (network services).

NOTE: At this stage of development, Fermat already offers a wide scope of REUSABLE components for third parts to build on top, encouraging further development of the plan, enrichnening it with every single addition.


=== PHASE I

The next "buildings" are the different software *platforms" included in Fermat System, each one offering a set of functionalities to build :

* a decentralized Wallet Production Line
* a Crypto Currency platform
* a Shoping platform
* a Digital Asset platform
* a Marketing platform based on Digital Assets
* a Crypto Broker platform
* a Crypto Distribution Network

among others...
    
Are you interested in getting to know them deeper? Follow next chapters to get a more detailed description of each one.

:numbered:
  
=== Continue Reading

link:book-appendix-03-money.asciidoc[Appendix 03: Fiat Money & Crypto Currency]

link:book-chapter-02.asciidoc[Next Chapter]

link:book-intro.asciidoc[Previous Chapter]





