== Fermat Crypto Commodity Money
This platform introduces the first abstraction to manage Fiat Money over Crypto. 

=== New components
Some of the new components added to the framework by this platform are :

* fiat money requests and fiat money transmission
* Crypto Commodity Money Wallet
* Discount Wallet

=== Crypto Commodity Money Wallet

=== Discount Wallet
This niche wallet aims to protect the value stored in the user's by suggesting profitable conditiones to spend it. It checks the _exchange rate_ at the time the end user considerates spending the money and compares it with the rate when the crypto value was purchased, and shows the *positive difference* (gain) as a virtual *discount rate* to the end user at the time que considerates spending it.

=== Continue reading ...
////
link:book-chapter-19.asciidoc[Digital Assets Platform]
////

link:book-chapter-14.asciidoc[Next Chapter]

link:book-chapter-12.asciidoc[Previous Chapter]


////
=== _Network Service layer_
Money Request ::
Money Transmission :: +

=== _Wallet layer_
Crypto Commodity Wallet :: 
Discount Wallet :: +

=== _Composite Wallet layer_
Multiaccount Wallet :: +

=== _Crypto Money Transaction layer_
Incoming Device User ::
Incoming Extra Actor ::
Incoming Intra Actor ::
Intra Wallet ::
Outgoing Device User ::
Outgoing Extra Actor ::
Outgoing Intra Actor ::
Inter Account :: + 

=== _Request layer_
Money Request :: +

=== _Reference Wallet layer_
Discount Wallet :: +
////



