
== Chapter 1: Fermat Master Plan

As a Master Plan, Fermat has it's own vision of how a collaborative project should be carried out. The main concept is to define a large master plan far into the future, and start building it phase by phase adjusting the target when needed. It is designed in this way to absorb the efforts of thousands of contributors over the years into a unified architectural vision. +

After the pioneer step of Sakamoto who gave rise to *Bitcoin* and its revolutionary blockchain technology, in the last years, there has been a lot of fin tech investment money given to a myriad of startup initiating in this industry. This fostered the next evolutionary step resumend in the so called *"cryptocurrency 2.0"*, although its development has still not reached the level of mass adoption as expected. Maybe the evident  unbalance between  the considerable investment of funds and effort and the few global and lasting result obtained until now lay in the following reason: there is so much that has to be done to master this technology, that any isolated effort  trying to build something useful starting form zero point seems almost too much and too risky to obtain the necessary support. However, taking into consideration many sucessful *open source* projects in the software industry and other sustainable *global projects* , the Fermat Community believes to be able to find and implement the solutions to the challenges mentioned in their purpose and mission by using the systemic approach of *collaborative environments*.

=== Foundations 

Foundational concepts in Fermat's master plan are similar to the idea of a master plan for developing a modern city.

. First, we need the ground were to build :: 
in this case, the ground is all the available technology available today in internet, specially the available open source software, and all the devices and network technologies that let digital communication be available at a massive level. 
.Then, we need the basics services (electricity, gas, water supplies, etc) ::  
In Fermat, the first platform which initilizes the system, _Fermat Core Platform_,  also provides the basic services:
** FERMAT-OSA (FERMAT OPERATING SYSTEMS API ) provides the  connection to the diferent OPERATIVE SYSTEMS (filesystems and data base systems).
** FERMAT-BCH (FERMAT BLOCKCHAIN) provides interconnectivity to crytonetworks and blockchain services providers.
** FERMAT-P2P (FERMAT PEER-TO-PEER) provides interconectivity to all kinds of devices running FERMAT. 
* The first visible infrastructure, or the first "building in the city", it is similar to a huge "main entrance hall" were citizen are identified and granted the permission to enter the city. 
** FERMAT-PIP (FERMAT PLUG-INS PLATFORM) provides the necessary services to interact (consume services) and develop (create your own) the basic components of the system, the PLUG-INS.

NOTE: At this stage of development, FERMAT already offers a wide scope of REUSABLE components for third parts to build on top, encouraging further development of the plan, enrichnening it with every single addition, which is more profitable for the whole and for the individual actor than struggling for conquering a small niche of a much more limited market with the great burden of building everything from zero point.

NOTE: *At FERMAT we firmly believe that the comunity has much more talent and intelligent collectively than isolated individuals. We strive to reach a world-wide difussion of the blockchain  ecosystem with the conviction that we are laying the foundations of a global collaborative endeavour. Our development is a firm call to peers and colleagues to commiting themselves to be part of the transformation we want to bring forth. We call upon corageous minds who dare to build something great.* 


==== PHASE II

Here comes the building of the next set of platforms within FERMAT, that covers the functionalities to offer a:

* a decentralized Wallet Production Line
* a Shop platform
* a Digital Asset platform
* a Marketing platform based on Digital Assets
* a Crypto Broker platform
* a Crypto Distribution Network

    
A more detailed description of each one of these follow in the next chapters.

:numbered:
  
=== FERMAT as financial network
:numbered!: 
==== What's behind money?
In our daily live we have accepted money as something present in almost every activity of human endeavour, and most of us use it without reflecting on its origin or its deeper meaning. Making it simple, money is an agreed mean of exchanging value. By its universal adoption it allows a flow of products and services between the different actors in a producer-consumer chain ( or better, in a "web" of commercial interactions) and following this, an exchange of the value associated with each step, rewarding each actor with a portion of the entire value, what we call "profit". 
During the early ages trading was made directly exchanging certain goods for other goods, then as trading was growing at scale, the necessity of unification of mass and measures lead to the rising of money representing in some way the value of what was being exchange and a relative consensus over it. Later on, with the rising of the different nations which created a certain unification under certain name, language and goverment and rules to be applied to a determined territory and its inhabitants, this nations extended their souveranity also to the issue of a national currency and the printing of "official" paper money. At the begginning the amount of paper money was guaranteed by a national reserve on gold, but most of goverment abandoned the * gold standard* after the 1930 world crisis, and after 1971 the US goverment severed definitely the link between US Dollar to gold. This means, that the current money we use only depends on the "trust" we deposit on the goverment that rules its emission and this "legal curse" is enforced by law. There is NOT ANY OTHER intrinsec propierty on paper money to ensure its value than this!! When talking about corruption in some of our political and financial institutions, we can easily perceive how often this trust has been abused. This kind of money enforced by law which value is not linked to any specific asset has been called *fiat money*.

==== Cryptocurrency
When Bitcoin solved the issues that prevented other digital currencies to become a viable digital money ( "authenticity" (of the issuing and ownership) and the "double-spend" problem) it opened a whole new world in financial systems and economy, where cryptography provides the basis for trusting the legitimacy of a user's claim to value. So, this new kind of currency that is entirely virtual and that is implied in transactions that transfer value from sender to recipient based on crytographic signatures is what we call *cryptocurrency*

NOTE: The undeniable achievement of Bitcoin's electronic signature protocol based on *crytography* is the creation of a distributed public ledger of peer-to-peer electronic transactions that is transparent and at the same time preserves the anonimity and the security needed to become a safe way of transporting *value*, based on *consensus agreement*. This technology opens the door to a new paradigma in economics, computer science, financial operations, and world-wide commerce. +  
Sakamoto's invention makes possible to unveil the world of financial transactions, to get rid of the necessity of *trust* into a third party institution or central goverments, to make money a secure thing, and transactions transparent and effortless. It returns to the money's owner the absolute control over his richnes. +
The cryptocurrency scheme encourages us to adopt a radical new point of view on money and the concept of value itself and its transport, so radical, that it will take us  time and effort to really grasp it, because it leads to the unconditionally honoring and empowering of each individual. 


TIP: Taking Bitcoin as "the" paradigmatic model of every cryptocurrency, we need to have in mind that for Bitcoin to exist following is needed: +
* A decentralized peer-to-peer network (the bitcoin protocol) + 
* A public transaction ledger (the blockchain) +
* A decentralized mathematical and deterministic currency issuance (distributed mining) +
* A decentralized transaction verification system (transaction script) +


:numbered!:
=== Continue Reading
link:book-chapter-02.asciidoc[Next Chapter]

link:book-intro.asciidoc[Back to Introduction]





