:numbered:
== FERMAT P2P Network and Communication Superlayer
This superlayer provides connectivity between devices. FERMAT P2P Network is a dumb network connecting platform network services to each other irrespective of what these services are doing. It provides the communication channels and on top of its connectivity layer network services interact with each other across different devices. Anybody can provide new network services as *plug-ins*.
This ensures a rich *set of abstractions for wallet applications running on top of the platform*. + 
Fermat P2P Network is used for transporting the information associated with the transaction. *TRANSPORT OF INFORMATION* (METADATA)

[[Fermat-P2P-CommunicationLayer]]
= Communication Layer

== Layer Description

At the moment of the creation of this document the communication layer is the main (and only) layer inside Fermat-P2P subsystem. +

This layer give the communication services to the upper layers. +
A distinguished difference between this layer and others in Fermat system is that this is the first layer that interact with upper layers as a whole and not as plug-ins, i.e. plug-ins that need communication services ask them to the layer interface and not to the plug-ins inside. +
Even more, a purpose of this layer is to abstract completely the plug-ins managing the real connection The upper layers should not be aware of the technology in use (wi-fi, NFC, p2p, bluetooth, etc.) and problems related to a connection should be solved by the communication layer without disturbing the clients. +

[[Fermat-P2P-CommunicationLayer-CloudServer-Connection-Technologies]]
== Connection technologies

=== Cloud

In this first implementation will rely in a cloud server. At initialization the devices will contact through the cloud client plug-in with the server to inform they are online and can be contacted by other users. +

There is an identification system that identify devices, actors and <<Fermat-DMP-NetworkServiceLayer,network services>> that consist in pairs of keys generating by asymmetric cryptography methods. +

=== P2P

In the future we intend to move our communication infrastructure to a peer-to-peer architecture. This will bring both many challenges and advantages. For example, if we rely in a server or group of servers attacks to the service could be focused on the server. +


== Plug-ins in this layer

Plug-ins in this layer essentially consist on the modules needed for the implementation of the communication protocols and interfaces for the different <<Fermat-P2P-CommunicationLayer-CloudServer-Connection-Technologies,connection technologies>>. 
=== _Communication layer_
:numbered!:

Cloud Server :: _description ..._
Cloud Client :: _description ..._
P2P :: _description ..._
Geofenced :: _description ..._
Near Field Communication :: _description ..._
WiFi :: _description ..._
Mesh :: _description ..._

:numbered:


