:numbered:

== FERMAT BlockChain Superlayer
This superlayer provides to the entire FERMAT multiplatform system the necessary functionalities to manage blockchain technology.

=== _Crypto Networks layer_
This layer builds the interface between FERMAT and each cryptonetwork available. + 
There is one module for each cryptocurrency: Bitcoin, Litecoin, Ripple, Ethereum,  etc +
The main _responsibility_ for each module is to handle every outgoing/incoming request to/from the corresponding cryptonetwork.

=== _Crypto Vaults layers_
As well as in a traditional *funds management* of a Bank, the entire money that a Banks posseses is store in one _main vault_, and the _user's account managing system_ acknowledges how much money corrsponds to every one, in FERMAT, all the value processed by the system by managing each specific cryptocurrency is stored in the corresponding *vault*. +
Then is task of every FERMAT *wallet* to manage the amount of cryptocurrency owned by each *actor*.
 
Bitcoin Vault :: it stores the entire system's available _Bitcoin_ funds (*value storage*) 
Assets over Bitcoin :: it stores each little amount of_Bitcoin_ used to create a *Digital Asset* ( *metada storage* of what is represented by the *asset* , this is primerly *NOT* a storage of *value* ).  (See full explanation in the section about _Digital Assets_ [dap] )
Bitcoin Watch Only Vault :: used in the _Digital Asset Platform_ to store bitcoins that are needed to let the *redeem points* work. See full explanation in the section about _Digital Assets_ [dap] ) +

=== _Crypto Modules layer_
Crypto Address Book ::

=== _Crypto Router layer_
Incoming Crypto ::
Outgoing Crypto ::







