[[DigitalAssets]]
== FERMAT Digital Asset Platform. Blockchain beyond currency 

=== What is a Digital Asset ?


 

=== _Network Service layer_
Each time that a certain system function must perform any operation *outside* the device where FERMAT is running, a _network service_ is required to follow the execution in other devices until is completed. +
Network services' modules need to have a * communication channel* stablished and maintained between the parties involved, what is done by the *P2P networks and communication superlayer* ( see the explanation at the previous section <<communicationLayer>> )+
Each *network service module* running on a _local device_ stablish communication EXCLUSIVELY to its _counterpart_ running in the _remote device_. +
 
Asset Transmission :: +

=== _Actor Network Service layer_
Asset Issuer :: 
Asset User ::
Redeem Point :: +

=== _Identity layer_
Asset Issuer :: 
Asset User ::
Redeem Point :: +

=== _Wallet layer_
Asset Issuer Wallet ::
Asset User Wallet ::
Redeem Point Wallet :: +

=== _Digital Asset Transaction_
Asset Distribution ::
Asset Reception :: 
Asset Issuing :: 
Issuer Redemption :: 
User Redemption ::
Redeem Point Redemption ::
Asset Appropiation :: 
Appropiation Stats :: +

=== _Middleware layer_
Asset Factory :: +

=== _Actor layer_
Asset Issuer :: 
Asset User ::
Redeem Point :: +

=== _Desktop Module layer_
Sub App Manager :: 
Wallet Manager :: +

=== _Sub App Module layer_
Asset Factory :: :: 
Asset Issuer Community :: 
Asset User Community ::
Redeem Point Community ::+

=== _Wallet Module layer_
Asset Issuer :: 
Asset User ::
Redeem Point :: +

=== _Desktop layer_
Sub App Manager :: 
Wallet Manager :: +

=== _Sub App layer_
Asset Factory :: :: 
Asset Issuer Community :: 
Asset User Community ::
Redeem Point Community ::+

=== _Reference Wallet layer_
Asset Issuer :: 
Asset User ::
Redeem Point :: +
