== FERMAT Crypto Commodity Money

This platform ....


=== _Network Service layer_
Each time that a certain system function must perform any operation *outside* the device where FERMAT is running, a _network service_ is required to follow the execution in other devices until is completed. +
Network services' modules need to have a * communication channel* stablished and maintained between the parties involved, what is done by the *P2P networks and communication superlayer* ( see the explanation at the previous section <<communicationLayer>> )+
Each *network service module* running on a _local device_ stablish communication EXCLUSIVELY to its _counterpart_ running in the _remote device_. +
 
Money Request ::
Money Transmission :: +


=== _Wallet layer_
Crypto Commodity Wallet :: 
Discount Walet :: +


=== _Composite Wallet layer_
Multiaccount Wallet :: +


=== _Crypto Money Transaction layer_
Incoming Device User ::
Incoming Extra Actor ::
Incoming Intra Actor ::
Intra Wallet ::
Outgoing Device User ::
Outgoing Extra Actor ::
Outgoing Intra Actor ::
Inter Account :: + 


=== _Request layer_
Money Request :: +

=== _Reference Wallet layer_
Discount Wallet :: +


