== FERMAT Cryto Broker Platform
In this platform the actors involved are the *cryptobroker* and his customers (*cryptocustomers*). A *cryptobroker* is a person or small organization whose business logic is to buy and sell cryptocurrency for fiat money in his local market, obtaining his profits from the difference in the buy/sell price. We distinguish also two common level of * cryptobrokers*, those acting as *cryptobrokers wholesalers* adn those who deal with final users/customers.   

=== FERMAT Cryptobroker Wallet
This Wallet is designed with the theoretical assumption that the broker always has available stock of cryptocurrency and fiat money and that his activity is to be constantly selling this two kind of products obtaining profit. The functionalities offered should help him to run the business in a simple way, taking the responsability of the basic management of the broker's fund (in cryptocurrency and fiat money, in cash and in bank accounts), the management of the contact list of his customers, and a balance of the profits generated. +
Key functionalities are:

* *Funds replenishment*:
** Crypto Currency 
** Cash Money (Fiat money in cash)
** Bank Money (Fiat money in a bank account)
* *Incoming/Outgoing money*: 
** Cash on Hand 
** Delivered Cash
** Money Bank Deposit 
* *Special functions* for _associated crypto brokers network_ (*agreement* between colleagues to be able to manage joint operations when needed) :
** keep track of *Broker-to-Broker contract*



=== FERMAT Cryptobroker Customer Wallet





