:numbered:
== FERMAT Plug-ins Platform

FERMAT Plug-ins Platform is open source and run on end users’ devices. It allows third party developers to extend the platform functionality thereby enabling quick adaption to a rapidly evolving environment. A micro licensing system allows plug-ins and segment specific wallet developers to profit from their investment and motivates any member of the community to participate in the project bringing in even more knowledge and ideas in a quick, efficient and profitable way.

=== _Platform Services layer_

Error Manager ::
Event Manager ::
Connectivity Subsystem ::
Location Subsystem ::
Power Subsystem ::
Platform Info :: + 


=== _Hardware layer_

Local Device ::
Device Network ::


=== _Users layer_

Device User ::


=== _Plugin layer_

Identity ::
Dependency ::


=== _License layer_

Plugin ::


=== _Network Service layer_

Sub App Resources ::
System Monitor ::
Error Manager ::
Messenger ::
Technical Support ::


=== _Actor Network Service layer_
Developer::


=== _Identity layer_
Developer ::
Designer ::


=== _World layer_
=== _Middleware layer_
=== _Actor layer_
=== _Desktop Module layer_
=== _Subapp Module layer_
=== _Engine layer_
=== _Desktop layer_
=== _Subapp layer_
