:numbered:

=== System-wide definitions
One of main concept's inside FERMAT's design is the distinction of different _levels of identities_ depending on the realm where this _identities_ are valid. These creates a hierarchical structure of _identities_ and the _credentials_ associated with it.
The *real person* who wants to use FERMAT, has to install the software in at least one *device* and then let it run.
At this stage, the real person gets an initial identity a *device user*, which is automatically given by FERMAT and is transparent to him (needs not to worry about it and/or decide anything about it). This is valid for all the functions that happend INSIDE the device, and it contains certain information about himself/herself that is known to the device operating system, and which is stored in the device's memory/hard drive. + 
Then, to start using FERMAT, he/she is prompted by the software to choose a *master identity* within FERMAT. That means to choose an _username_ (or _ alias_) and a _password_ to be recognized as a *FERMAT system user*, and has certain _profile_ associated with it. 
Then, the *real person* turned into a *user* of FERMAT, chooses to run any of FERMAT's products, and this takes him to play certain role within a specific FERMAT Platform available, what turns him/she into an *actor* of the platform. As such, he/she must define an _actor identity_  within THIS platform, which is INDEPENDENT to any other created in other platforms, although it is related to the FERMAT system-wide *master identity*. + 
This *actor* has the possibility to define a set of multiple _wallet identities_ to operate within each wallet, defining a _profile_ for each one,  choosing the profile concepts to include (name, picture, occupation, etc) and the content of them, having total control of which information he shares with the world. + 
For the external world, each _wallet identity_ appears to be a "different person" and there are NO RELATIONS between them. However, for the *Fermat User* owning his *master identity*, all his *actor identities* and *wallet identities* are interconnected.

.Example of hierarchichal identities 
* *master identity* eg. John Doe, Colorado Springs, CO, USA.
** *actor identity 1* eg. "John cryptobroker"
*** *wallet identity1* eg. "The Commander Venezuela Cryptobroker"
*** *wallet identity1* eg. "Colorado Exchange Cryptobroker"
** *actor identity 2* eg. "Alice Brenda Smith cryptocurrency owner"
*** *wallet identity1* eg. "Alice bitcoin wallet user"
*** *wallet identity2* eg. "A.B.S. Bitcoin Loss Protected user"
** *actor identity3* eg. "Aunt Betty Muffins asset issuer"


=== Fermat'S actors
Cryptocurrencies live in a public and distributed ledger, the *blockchain*, in a decentralized p2p network (spread in every network node). + 
They are held and stored by their owners in specific applications called *wallets* living in a certain device which has access to the corresponding cryptonetwork. +
*Wallets* store the owner's _privat key_ and the corresponding _public key_ to unlock the cryptocurrency amount of a given *transaction*. + 
For a *transaction* to take place, a *crypto address* is needed to identify both the sender of the value as well as the receiver. + 
*Crypto addresses* are generated by the wallet derived from the _privat/public key_ pair of the wallet's owner. +
Although *wallets* are similar in relationship to their basic functionalities, the _natural segmentation of the world population_ and the specific demand of every segment requires to be taken into account when designing *wallets*. +
Fermat defines different system *actors* to identify the specific needs and level of abstraction required to each actor, and consequently being able to design Fermat's products with the appropiated orientation.
 

:numbered!:

==== segmentation 
Fermat understands that there exists on the world so many different tastes and preferences like humans exists on earth, because each one is _unique_, and therefore there are potentially a huge number of differents ways of shaping the applications being developed, considering its functionalities, accessibility, and appearance among other various customizable characteristics, although they are conceived to deal with the same tasks of managing cryptocurrencies and blockchain technology.  + 
Here begins the huge differentation between Fermat applications and the rest ! + 
Fermat takes very _seriously_ into account the _actor's profile_ to develop attractive applications in each case to match very specificaly the demand of each consumer's niche. For instance, some actors with a more complex relationships world require more complexity in their wallets and in the wallet of his partners.

==== levels of abstraction
On the other hand, while certain actors need basic operations, other's use of blockchain technology may demand higher levels of abstraction.
For instance, low abstraction is needed for user that only need to see their value in *cryptocurrency*. Others may want to have their wallets showing them their content in *fiat money*. Others might need some functionalities that prevent them for *losing value* depending on the exchange rate they purchased the currency and when they want to spend it, and some of them would like even to see the profitable exchange rate as a *discount* obtained in the purchase of goods.. There are also many who will only serve themselves of the cryptonetwork not to transport value, but to issue *digital assets* instead, assets that are made public through the blockchain ledger... + 
All this different _*abstraction levels*_ are possible within Fermat, and Fermat multi-platform system is specifically designed to match this increasing demand in the industry, and at the same time, the use of Fermat'S products foster the creation of real-world environments, connecting in a very efficient, secure, and scalable way, the actors offering services with those consuming them.


==== Overview of Fermat's products and their actors

Fermat WALLET FACTORY ::   -> for marketers to re-brand any of the already existing segment specific wallets in a few steps (without the need to deal with the source code of the base wallet selected!)
Fermat WALLET PUBLISHER ::  -> for wallet designers/marketing agency to offer their rebranded Wallet to the world !
Fermat WALLET STORE ::  -> the store where available wallets live, ready to be adopted !
Fermat BITCOIN WALLET :: -> for those devoted "BTC-only" users!
Fermat BITCOIN LOSS PROTECTED WALLET -> for conservative user's caring about never selling under the purchase price ! (preserving value!)
Fermat ARGENTINE BLP WALLET :: -> for citizen's of the nr.1 potential mass market for BTC (designed to match argentine culture of steady comparison between argentine$, USD (oficial and blue!) and even Eu$!)
Fermat CRYPTO COMMODITY MONEY WALLET :: ->
Fermat DISCOUNT WALLET :: -> for discount and bonus chasers! ( recommend selling when price gets convinient, and shows it as a " discount" !)*
Fermat BANK NOTES  WALLET :: -> for those wanting to visualize their investment in "real money traditional bank notes" of their usual fiat/currency ( rest on Fermat, we do the "dirty work" with all the crypto stuff!)*
Fermat SHOP WALLET :: -> *for shop owners who accept cryptocurrency in payment of their products !*
Fermat BRAND WALLET :: -> *for brands owners who accept cryptocurrency in their retailers network.*
Fermat RETAILER WALLET :: -> *for* 
Fermat ASSET ISSUER WALLET :: -> for company or brand that issues a Digital Assets to offer to their customers*
Fermat ASSET USER  WALLET :: -> for *the customer who accepts/obtain some Digital Assets according to his interests*
Fermat REDEEM POINT WALLET :: -> for the place/shop/person that exchanges the Asset for a certain service or product (redeems it).*
Fermat VOUCHER WALLET :: -> for 
Fermat COUPON WALLET :: -> for 
Fermat DISCOUNT WALLET :: -> for 
Fermat CRYPTO BROKER WALLET :: -> for persons/organizations whose business activity is exchanging cryptocurrency for fiat-money
Fermat CRYPTO BROKER'S USER WALLET ::  ->  for customers of the cryptobroker
Fermat CRYPTO WHOLESALER WALLET :: -> for organizations owing a certain large amount of crypto-credit to sell through a distribution chain.
Fermat CRYPTO DISTRIBUTOR WALLET :: -> for those who form the next level in the distribution, buying to wholesalers and re-selling to Top Up Point
Fermat TOP UP POINT WALLET :: -> for shops/organizations/persons who transfer crypto-credit in exchange for fiat-money (receives money - gives crypto)
Fermat CASH OUT POINT WALLET :: -> for shops/organizations/persons who gives out money in exchange for a transfer of crypto (receive crypto - gives money)













