:numbered:
== FERMAT: a platform stack system


*FERMAT* is, technically speaking , an Open Source P2P (Peer-to-Peer) Platfor Stack System built on a Plug-in Architecture running on end-user's devices. 

 
=== What makes FERMAT different from other wallet platforms or services?

* **FERMAT is P2P.** This makes it censorship resistent and difficult to be attacked.

* **FERMAT is built with plugins.** This enables functionality to be reused and opens the door to any developer to participate.

* **FERMAT runs on end users' devices.** This enables users to hold their own money eliminating the need to trust a third party. 

* **FERMAT is inclusive.** By creating their own plugins, current industry members can integrate with FERMAT to offer their services and products to FERMAT user base. 

* **FERMAT segments the world population and offers a custom tailored solution for each segment.** Any developer can easily create niche wallets for a particular group of people. Brands can create their own wallets for their followers. All the heavy lifting is done by the FERMAT platform.

* **FERMAT guaratees plugins and wallet developers a revenue stream.** FERMAT implements an innovative business model which allows plugins and wallet developers to define a use license, and FERMAT itself enforces this license on behalf of developers. )

The first goal is to get very close to the *end user* offering and easy way of coming onboard the crytocurrency world by means of possesing a digital *wallet* running on his preferred device. +
At the same time, the open source *plug-in platform* allows any skilled actor in the community to jump in and develop applications and offer services with different abstraction levels and addressing a wide range of segmented markets. In fact, as we have seen in the section about FERMAT as a master plan, the possibility of using the existent global talent and intelligence that the community already has in a clever collaborative way, can rapidily expand this technology to mass adoption. + 
Instead of begginning a new project in this industry completley from zero point, the clear and firm logic of FERMAT can make it a new standard in the industry, giving the collective a strong and stabile group coherence it had never experienced before. All participants in the different sectors get , because of FERMAT's transparency, clear logic and solid foundations, a sense of trust, safety and equity, and the corresponding right to become a revenue for each one's contribution and effort.


=== What characteristics has FERMAT as a software system ?
FERMAT is 

* OPEN SOURCE
The code can be reviewed and audited by anyone.

* DECENTRALIZED
It runs on end users’ devices.

* PUBLIC
Anybody can connect to the Fermat P2P network and use its services. Anybody can write plug-ins for the platform.

* OPEN
Anybody can participate and innovate without requiring permission.

* INCLUSIVE
Any existing crypto service running outside the Fermat network / platform can be integrated and consumed from within the network.

* OPEN STANDARD
Can be freely adopted, implemented and extended.

=== FERMAT's architecture 
:numbered!:
FERMAT has a specific architecture to ensures the fullfillment of the goals and mission set.
First we describe the components and then how they are organised (system architecture).

.Types of components
* *libraries*: structural components of the core of the system (downlevel) (FERMAT-CORE - FERMAT-API) 
* *androids*: applications that run on Android System and present the graphic environment to the user.
* *plug-ins*: components which encapsulates a very specific sets of functions, that offer a public interface to consum services (*INPUT*) from other alike components and offers certain other services to be consumed (*OUTPUT*).
* *add-ons*: this is an original name coined in FERMAT to address to certain low level plug-ins that provides the core functionalities of the system, and therefore are developed by FERMAT'S developer team, while plug-ins are open to include third party developers from its inception.

==== plug-in architecture

*PLUG-INS* are very convienent bacause of its defyning feature: as long as the INTERFACE (i.e. the shape of the interconnection) is known and publish, the plug-in can interact with others, consuming and offering services, INDEPENDENTLY of its inner structure and how it is built. As long as they conserve this INTERFACE, they can safely evolve to more efficient functioning WITHOUT altering a single service that has been built upon it ! 
Inside FERMAT, each plug-in is given certain specific responsability within the whole, it lives in a certain layer, and it is allow to communicate only with plug-ins of the next layer on top, building a hierarchical structure on dependance and allowing an ordered transmission of responsability from one component to the next in the thread to provide a certain function.

NOTE: FERMAT'S core concept of REUSABILITY relies on this plug-in/add-on architechture chosen to develop it.


Through its plug-ins, FERMAT is able to connect and reuse most of the infrastructure deployed by the industry.
  
==== multilayer architecture
FERMAT needs to be adaptable, provide highly component reutilisation, and offer a scalability that match the complexity of the service that is running on in. Therefore the components are set in layers stacking one over the other. Each layer groups components that provide a similar functionality, eg. communications layer is designed to provide a way to connect one device to another building a "communications channel" using different available tecnologies ( cloud servers, wifi, NFT, etc), and in performing this task, it let other components from other layers do their specific task consumming services of this communication layer in a transparent way, without any concern on how the communication is actually being stablished. +
*Layers* let themselves be collected under certain need to provide services as a whole, and this layers ensemble turn into a *platform* of services that are offered.

==== platform architecture
A *platform* consists of a group of components living in different *layers* interconnected to offer a specific set of services for a discovered niche. For example, if we address to cryptocurrency users, we will need a crytocurrency wallet for each cryptocurrency available running on FERMAT-CCP (Crypto Currency Platform). This wallet would operate on the selected cryptonetwork by means of a connection to it provided by FERMAT-BCH (Block Chain Platform), and will interact with the user by means of an app living in the ANDROID-APP layer. 

==== p2p architecture
FERMAT is a decentralized system, so it needs to stablish a connection between every actor and every device using it, and this is done by creating a P2P-NETWORK between them, based on the services provided by FERMAT-P2P Platform and its components.

==== multi OS architecture
FERMAT IS *code-base portable*, meaning that the components are written in code that runs in different operating systems. 
So, through FERMAT-OSA (FERMAT OPERATING SYSTEM API) , the components that are specific to a given Operating SYstem connect to the rest of FERMAT that is OS independent.

.General overview on FERMAT'S platforms and product's families
* FERMAT CORE
** FERMAT OSA (operating system)
** FERMAT P2P (network and communication layers)
*** This layer provides connectivity between devices. FERMAT-P2P is a dumb network connecting platform network services to each other irrespective of what these services are doing. It provides the communication channels and on top of its connectivity layer network services interact with each other across different devices. Anybody can provide new network services as *plug-ins*.
This ensures a rich *set of abstractions for wallet applications running on top of the platform*. Fermat P2P is used for transporting the information associated with the transaction. *TRANSPORT OF INFORMATION* (METADATA)
** FERMAT BCH (blockchain) 
*** This layer provides the conenction to cryptonetworks for transporting value.*TRANSPORT OF VALUE* 
** FERMAT PIP (Plug-ins Platform)
***Fermat PIP is an open source platform running on end users’ devices . It allows third party developers to extend the platform functionality thereby enabling quick adaption to a rapidly evolving environment. A micro licensing system allows plug-ins and segment specific wallet developers to profit from their investment and motivates any member of the community to participate in the project bringing in even more knowledge and ideas in a quick, efficient and profitable way.

:numbered:

=== Segmentation and different levels of abstraction in FERMAT
Cryptocurrencies are born into existent by a very specific mathemathical algorithym based on cryptographics rules run by a computer in a process called " mining". They are held and stored by their owners in specific applications called *wallets* that live in a certain device of the decentralized p2p network. To start using a cryptocurrency you have to download a client application ( full node or leightweight) to your device or use a cloud base application. The client application provides the basic functionalities to operate, i.e. usually one or a couple of "basic wallets" which generates an user unique identification and also a specific adress in the chosen cryptonetwork.

:numbered!:

==== segmentation 
FERMAT understands that there exists on the world so many different tastes and preferences like humans exists on earth, because each one is unique, and therefore there are potentially so many differents ways of shaping the accessibility, appearance and functionality of applications dealing with cryptocurrencies and blockchain technology to match very specific need and scalable demand of each consumer's niche. Here begins the huge differentation between FERMAT applications and the rest ! + 
FERMAT takes very seriously into account the actor's profile to develop attractive applications in each case. Well, for some actor's with more complex relationships world, more complexity is also wanted in ther wallets and in the wallet of kindred actor's that interdepend and interact in the same *niche*. 

==== levels of abstraction
While certain actors need basic operations, others utilization of blockchain technology can required different levels of abstraction.
For instance, low abstraction is needed for user that only need to see their value in *cryptocurrency*. Other may want to haver their wallets showing them their content in * fiat money*. Others might need some functionalities that prevent them for *losing value* depending on the exchange rate they purchased the currency and when they want to spend it, and some of them would like to see the profitable exchange rate as a * discount* obtained in the purchase of goods.. There are also many who will only serve themselves of the cryptonetwork not to transport value, but to issue * digital assets* that are made public through the blockchain ledger... + 
All this different * abstraction levels* are possible within FERMAT, and FERMAT'S PLATFORM are specifically designed to match certain needs of a niche and they foster the creation of a real-world environment, linking actors offering services with those consuming them.

:numbered:

=== FERMAT's products to the world.
A visible way of grasping all the complexity of FERMAT as well as all its potential to evolve into a global sytem, is to take a look at some of the specific products created and running on FERMAT.

.Wallets "ready-to-use"
* FERMAT WPD (Wallet Production & Distribution)
** WaFa (Wallet Factory)  -> *for marketers to re-brand any of the already existing segment specific wallets in a few steps (without the need to deal with the source code of the base wallet selected!)*
** WaPu (Wallet Publisher) -> *for wallet designers/marketing agency to offer their rebranded Wallet to the world !*
** WaSt (Wallet Store) -> the store where available wallets live, ready to be adopted !
** WaMa (Wallet Manager)  -> for everyone who uses more than one wallet, to manage them !
* FERMAT CCP (crypto currency platform)
** BitWa (Basic Bitcoin Wallet)  -> *for those devoted "BTC-only" users!*
** Argentine Bitcoin wallet -> *for citizen's of the nr.1 potential mass market for BTC (designed to match argentine culture of steady* comparison between argentine$, USD (oficial and blue!) and even Eu$!)
** BLP (Bitcoin Loss Protected wallet) -> *for conservative user's caring about never selling under the purchase price ! (preserving value!)*
* FERMAT CCM (Crypto Currency Money)
** CCM (Crypto Currency Money Wallet)
** DiWa (Discount Wallet) -> *for discount and bonus chasers! ( recommend selling when price gets convinient, and shows it as a " discount" !)*
* FERMAT BNK (Bank Notes)
** BaNo (Bank Notes Wallet) -> *for those wanting to visualize their investment in "real money traditional bank notes" of their usual fiat/currency ( rest on FERMAT, we do the "dirty work" with all the crypto stuff!)*
* FERMAT SHP (Shop Platform)
** ShWa (Shop Wallet) -> *for shop owners who accept cryptocurrency in payment of their products !*
** BrWa (Brand Wallet) -> *for brands owners who accept cryptocurrency in their retailers network.*
** ReWa (Retail wallet) -> *for* 
ated
** AsUs (Shop wallet) -> for *the customer who accepts/obtain some Digital Assets according to his interests*
** RePo (Shop wallet) -> for the place/shop/person that exchanges the Asset for a certain service or product (redeems it).*
* FERMAT MKT  (Market Platform)
** VoWa (VShop wallet) -> for 
** CoWa (Voucher Wallet) -> for 
** DiWa (Shop wallet) -> for shop owners who accept cryptocurrency in payment of their products !
* FERMAT CBP (Crypto Broker Platform)
** CrBr (Crypto Broker Wallet) -> for persons/organizations whose business activity is exchanging cryptocurrency for fiat-money
** CrCu (Crypto Broker Customer Wallet) ->  for customers of the cryptobroker
* FERMAT CDN (Crypto Distribution Network)
** CrWh (Crypto Wholesaler) -> for organizations owing a certain large amount of crypto-credit to sell through a distribution chain.
** CrCu (Crypto Distributor) -> for those who form the next level in the distribution, buying to wholesalers and re-selling to Top Up Point
** TUP (Top Up Point) -> for shops/organizations/persons who transfer crypto-credit in exchange for fiat-money (receives money - gives crypto)
** COP (Cash Out Point) -> for shops/organizations/persons who gives out money in exchange for a transfer of crypto (receive crypto - gives money)


For a cool visualization of the constant growing system of layers & columns, platforms and wallets visit http://fermat.org





