[preface]
== Preface

=== Being part of Fermat 

=== Intended Audience

This book is mostly intended for coders. If you can use a programming language, this book will teach you how cryptographic currencies work, how to use them, and how to develop software that works with them. The first few chapters are also suitable as an in-depth introduction to bitcoin for noncoders—those trying to understand the inner workings of bitcoin and cryptocurrencies.

=== 
=== How to Contact Us

Please address comments and questions concerning this book to the publisher:

++++
<simplelist>
<member>
</member>
</simplelist>
++++

We have a web page for this book, where we list errata, examples, and any additional information. You can access this page at link:$$http:// ......... $$[].


To comment or ask technical questions about this book, send email to pass:[<email>@bitdubai.com</email>].



=== Acknowledgments

This book represents the efforts and contributions of many people.
[[github_contrib]]
==== Early Release Draft (GitHub Contributions)

Many contributors offered comments, corrections, and additions to the early-release draft on GitHub. Thank you all for your contributions to this book. Following is a list of notable GitHub contributors, including their GitHub ID in parentheses:


