= Version 1

== Plug-in Description

Cuando el usuario hace un envío de dinero a través de la bitcoin wallet, se invoca a este plug-in para que ejecute el envío pedido y para que actualice los balances de la wallet. +
Cuando se invoca a este módulo conceptualmente se crea una transacción a ejecutar, la cuál debe mantener consistente tanto el estado del balance de la wallet como el estado de los fondos en la crypto red.  +
El balance es llevado por el plug-in BitCoinWalletBasicWallet mientras que el envío que se hace en la red es llevado por el plug-in CryptoVault de la red bitcoin. +

Cuando se desea hacer un pago a una wallet se le pide a este plug-in un TransactionManager. Este objeto implementa un método de envío de bitcoins que requiere como parámetros el ID de la wallet que se usa para enviar el dinero, la dirección de destino y el monto a enviar. +

El TransactionManager debe buscar a la wallet indicada, actualizar su balance y enviar el monto por la red bitcoin. +
Si bien esto parece simple, debemos considerar varias posibles fallas:

. Que el sistema se caiga en cualquier punto de las actualizaciones.
. Que no se pueda enviar la transacción bitcoin por la red por cuestiones diversas (imposibilidad de conectarse a la red, dirección ingresada con formato erroneo). 

Cuando se entrega un transaction manager para una wallet se debería abrir una base de datos que tiene el registro de las transacciones creadas con un estado asociado. 

* NEW (NEW): Cuando el usuario ejecuta el envío del pago
* PERSISTED_IN_WALLET (PIW): Cuando hemos persistido exitosamente el cambio del balance en la bitcoin wallet
* SENT_TO_CRYPTO_VOULT (STCV): Cuando se envió correctamente por la red bitcoin.
* SUCCESSFUL_SENT (SS): Cuando se registró el envío en la red.

A futuro:

* REVERSED (REV): Cuando la vault avisa que se reversó la transacción enviada (la vault se encarga de reenviarla)
