[[DocumentationOrganization]]
= Documentation Organization

The system documentation is written is asciidoc format in order to be portable to many formats. +
We will decompose the system in the following way: 

* First we will describe the system functionality as a whole app, where we will describe the actors and sub-apps involved in the system.
* The next part is divided in the description of each layer. Inside every layer section we will find a general explanation of the layer, and follow by a list of all the plug-ins living in the layer.
* Every plug-in will have its own subdivision, where we will find one reference for every developer who is in charge of an implementation of the plug-in.
* Then each developer will have a final subdivision of its documentation to refer separately to the different version of the plug-in implemented.

In this way we will get a central documentation where we will find a whole range of information about the system, from usage examples of the application to technical description of the plug-ins. We don't want show code in this document, all the implementation details will be described inside the source files. Although, we will see in some cases technical discussions about the implementation challenges described in a slightly more abstract way than the source code.

So, the general structure of this document can be seen in the following way

* Platform Description
** Layer Description
*** Plug-in Developer Index
**** Developer Version Index
***** Version Description
