= Fermat Documentation

If you want to read the documentation offline clone this repo and excecute.

 $ asciidoctor -d book -b docbook5 documentation.asciidoc

This will create documentation.xml, you can navigate it using yelp

 $ yelp documentation.xml

You can also create a local html file using:

 $ asciidoctor -d book documentation.asciidoc

And navigate it using your favourite browser.


If you want to navigate offline a subsection and not all the documentation you can use the steps described above with the desire files.

To read the documentation here in github just start in the next link

include::documentation.asciidoc[]

We decided to use asciidoc instead of markdown (the .md files) because of the support to build other document formats. +
If you have something written in markdown syntax you can convert it to asciidoc using pandoc in this way:

 $ pandoc -t asciidoc -f markdown archivo.md > archivo.asciidoc

After the conversion you need to change the "anchors" generated by pandoc (the \[[SectionName]] labels that are written above section tittles) or just add a distinctive prefix (something like LayerName-PluginName-Developer-VersiónNumer-). For example: \[[OSLayer-DatabaseSystem-Bitdubai-1-Introduction]]) because all links references are global in the whole documentation when you navigate it offline.
