package com.bitdubai.wallet_platform_api.layer._10_middleware.app_runtime;

/**
 * Created by ciencias on 2/14/15.
 */
public enum Activities {
    
    CWP_SHELL_LOGIN,
    CWP_WALLET_MANAGER_MAIN,
    CWP_WALLET_RUNTIME_WALLET_AGE_KIDS_ALL_BITDUBAI_MAIN,
    CWP_WALLET_STORE_MAIN,
    CWP_WALLET_ADULTS_ALL_MAIN,
    CWP_WALLET_RUNTIME_STORE_MAIN,
    CWP_WALLET_RUNTIME_ADULTS_ALL_MAIN,
    CWP_WALLET_RUNTIME_ADULTS_ALL_ACCOUNTS,
    CWP_WALLET_RUNTIME_ADULTS_ALL_BANKS,
    CWP_WALLET_RUNTIME_ADULTS_ALL_COUPONS,
    CWP_WALLET_RUNTIME_ADULTS_ALL_DISCOUNTS,
    CWP_WALLET_RUNTIME_ADULTS_ALL_VOUCHERS,
    CWP_WALLET_RUNTIME_ADULTS_ALL_GIFT_CARDS,
    CWP_WALLET_RUNTIME_ADULTS_ALL_CLONES,
    CWP_WALLET_RUNTIME_ADULTS_ALL_CHILDS,
    CWP_WALLET_RUNTIME_ADULTS_ALL_CONTACTS,
    CWP_WALLET_ADULTS_ALL_SHOPS,
    CWP_WALLET_ADULTS_ALL_REFFILS,
    CWP_WALLET_ADULTS_ALL_REQUESTS_RECEIVED,
    CWP_WALLET_ADULTS_ALL_REQUEST_SEND,
    CWP_WALLET_FACTORY_MAIN;
}
