package com.bitdubai.wallet_platform_api.layer._10_middleware.app_runtime;

/**
 * Created by ciencias on 2/14/15.
 */
public enum Fragments {

    CWP_SHELL_LOGIN,
    CWP_WALLET_MANAGER_MAIN,
    CWP_WALLET_RUNTIME_WALLET_AGE_KIDS_ALL_BITDUBAI_PROFILE,
    CWP_WALLET_RUNTIME_WALLET_AGE_KIDS_ALL_BITDUBAI_DESKTOP,
    CWP_WALLET_RUNTIME_WALLET_AGE_KIDS_ALL_BITDUBAI_CONTACTS,
    CWP_WALLET_RUNTIME_WALLET_AGE_KIDS_ALL_BITDUBAI_COMMUNITY,
    CWP_WALLET_STORE_MAIN,
    CWP_WALLET_FACTORY_MAIN;
    
}
