package com.bitdubai.fermat_api.layer.all_definition.navigation_structure.enums;

import com.bitdubai.fermat_api.layer.all_definition.enums.FermatFragments;
import com.bitdubai.fermat_api.layer.all_definition.exceptions.InvalidParameterException;

/**
 * Created by rodrigo on 2015.07.20..
 */
public enum Fragments implements FermatFragments {
    CWP_SHELL_LOGIN("CSL"),
    CWP_WALLET_MANAGER_MAIN("CWMM"),
    CWP_SUB_APP_DEVELOPER("CSAD"),
    CWP_WALLET_MANAGER_SHOP("CWMS"),
    CWP_SHOP_MANAGER_MAIN("CSMM"),
    CWP_SHOP_MANAGER_FREE("CSMF"),
    CWP_SHOP_MANAGER_PAID("CSMP"),
    CWP_SHOP_MANAGER_ACCEPTED_NEARBY("CSMAN"),

    CWP_WALLET_PUBLISHER_MAIN_FRAGMENT("CWPMF"),

    // Wallet Store
    CWP_WALLET_STORE_MAIN_ACTIVITY("CWPWSMA"),
    CWP_WALLET_STORE_DETAIL_ACTIVITY("CWPWSDA"),
    CWP_WALLET_STORE_MORE_DETAIL_ACTIVITY("CWPWSMDA"),

    // usados por la sub app intra user de Matias
    CWP_WALLET_STORE_ACCEPTED_NEARBY_FRAGMENT("CWSANF"),
    CWP_WALLET_STORE_ALL_FRAGMENT("CWSAF"),
    CWP_WALLET_STORE_FREE_FRAGMENT("CWSFF"),
    CWP_WALLET_STORE_PAID_FRAGMENT("CWSPF"),
    CWP_WALLET_STORE_SEARCH_MODE("CWSSM"),

    DAP_SUB_APP_ASSET_FACTORY_EDITABLE_TAB_FRAGMENT("DAPSAAFETF"),
    DAP_SUB_APP_ASSET_FACTORY_PUBLISHED_TAB_FRAGMENT("DAPSAAFPTF"),
    DAP_SUB_APP_ASSET_EDITOR_ACTIVITY("DSAAEA"),
    DAP_SUB_APP_ASSET_FACTORY_SETTINGS("DSAAFS"),
    DAP_SUB_APP_ASSET_FACTORY_SETTINGS_NETWORK_MAIN("DSAAFSNM"),
    DAP_SUB_APP_ASSET_FACTORY_SETTINGS_NOTIFICATIONS("DSAAFN"),
    DAP_SUB_APP_ASSET_FACTORY_WIZARD_MULTIMEDIA("DSAAFWM"),
    DAP_SUB_APP_ASSET_FACTORY_WIZARD_PROPERTIES("DSAAFWP"),
    DAP_SUB_APP_ASSET_FACTORY_WIZARD_CRYPTO("DSAAFWC"),
    DAP_SUB_APP_ASSET_FACTORY_WIZARD_VERIFY("DSAAFWV"),

    DAP_ASSET_ISSUER_COMMUNITY_ACTIVITY_MAIN("DAPAICAM"),
    DAP_ASSET_ISSUER_COMMUNITY_ACTIVITY_PROFILE_FRAGMENT("DAICAPF"),
    DAP_ASSET_ISSUER_COMMUNITY_CONNECTIONS_LIST_FRAGMENT("DAICCLF"),
    DAP_ASSET_ISSUER_COMMUNITY_NOTIFICATION_FRAGMENT("DAICNF"),
    DAP_ASSET_ISSUER_COMMUNITY_SETTINGS("DAICS"),

    DAP_ASSET_USER_COMMUNITY_ACTIVITY_MAIN("DAPAUCAM"),
    DAP_ASSET_USER_COMMUNITY_ACTIVITY_ADMINISTRATIVE_GROUP_FRAGMENT("DAPAUCAGF"),
    DAP_ASSET_USER_COMMUNITY_ACTIVITY_ADMINISTRATIVE_GROUP_USERS_FRAGMENT("DAUCAAGUF"),
    DAP_ASSET_USER_COMMUNITY_ACTIVITY_ADMINISTRATIVE_USERS("DAUCAAU"),
    DAP_ASSET_USER_COMMUNITY_ACTIVITY_PROFILE_FRAGMENT("DAUCAPF"),
    DAP_ASSET_USER_COMMUNITY_CONNECTION_LIST_OTHER_PROFILE_FRAGMENT("DAUCCLOPF"),
    DAP_ASSET_USER_COMMUNITY_CONNECTION_LIST_FRAGMENT("DAUCCLF"),
    DAP_ASSET_USER_COMMUNITY_NOTIFICATION_FRAGMENT("DAUCNF"),
    DAP_ASSET_USER_COMMUNITY_SETTINGS_FRAGMENT("DAUCSF"),

    DAP_ASSET_REDEEM_POINT_COMMUNITY_ACTIVITY_MAIN("DAPARPCAM"),
    DAP_ASSET_REDEEM_POINT_COMMUNITY_ACTIVITY_PROFILE_FRAGMENT("DARPCSPF"),
    DAP_ASSET_REDEEM_POINT_COMMUNITY_CONNECTION_LIST_FRAGMENT("DARPCCLF"),
    DAP_ASSET_REDEEM_POINT_COMMUNITY_NOTIFICATION_FRAGMENT("DARPCNF"),
    DAP_ASSET_REDEEM_POINT_COMMUNITY_SETTINGS_FRAGMENT("DARPCSF"),

    /**
     * REFERENCE WALLET
     */

    CWP_WALLET_RUNTIME_WALLET_BITCOIN_ALL_BITDUBAI_SEND("CWRWBTCABS"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_ALL_BITDUBAI_BALANCE("CWRWBTCABB"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_ALL_BITDUBAI_RECEIVE("CWRWBTCABR"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_ALL_BITDUBAI_TRANSACTIONS("CWRWBTCABT"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_ALL_BITDUBAI_CONTACTS("CWRWBTCABC"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_ALL_BITDUBAI_DETAIL_CONTACTS("CWRWBABDC"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_ALL_BITDUBAI_CREATE_CONTACTS("CWRWBABCC"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_ALL_BITDUBAI_MONEY_REQUEST("CWRWBTCABMR"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_ALL_BITDUBAI_TRANSACTIONS_BOOK("CWRWBTCABTB"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_ALL_BITDUBAI_TRANSACTIONS_AVAILABLE("CWRWBTCABTA"),

    CCP_BITCOIN_WALLET_TRANSACTIONS_SENT("CCPBWTS"),
    CCP_BITCOIN_WALLET_TRANSACTIONS_RECEIVED("CCPBWTR"),
    CCP_BITCOIN_WALLET_REQUEST_RECEIVED("CCPBWRR"),
    CCP_BITCOIN_WALLET_REQUEST_SEND("CCPBWRS"),
    CCP_BITCOIN_WALLET_TRANSACTIONS_SENT_HISTORY("CCPBWTSH"),
    CCP_BITCOIN_WALLET_TRANSACTIONS_RECEIVED_HISTORY("CCPBWTRH"),
    CCP_BITCOIN_WALLET_REQUEST_SENT_HISTORY("CCPBWRSH"),
    CCP_BITCOIN_WALLET_REQUEST_RECEIVED_HISTORY("CCPBWRRH"),

    CCP_BITCOIN_WALLET_SEND_FORM_FRAGMENT("CPPBWSFF"),
    CCP_BITCOIN_WALLET_REQUEST_FORM_FRAGMENT("CCPBWRFF"),
    CCP_BITCOIN_WALLET_SETTINGS_FRAGMENT("CCPBWSF"),
    CCP_BITCOIN_WALLET_SETTINGS_FRAGMENT_NOTIFICATIONS("CCPBWSFN"),
    CCP_BITCOIN_WALLET_SETTINGS_FRAGMENT_MAIN_NETWORK("CCPBWSFMN"),
    CCP_BITCOIN_WALLET_ADD_CONNECTION_FRAGMENT("CCPBWACF"),
    CCP_BITCOIN_WALLET_NO_IDENTITY_FRAGMENT("CCPBWNIF"),
    CCP_BITCOIN_WALLET_MNEMONIC_FRAGMENT("CCPBWMNF"),
    CCP_BITCOIN_WALLET_SEND_ERROR_REPORT_FRAGMENT("CCPBWSER"),

    /**
     * END REFERENCE
     */


    /**
     * LOSS PROTECTED WALLET
     */

    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_SEND("CWRWBTCLPABS"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_BALANCE("CWRWBTCLPABB"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_RECEIVE("CWRWBTCLPABR"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_TRANSACTIONS("CWRWBTCLPABT"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_CONTACTS("CWRWBTCLPABC"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_DETAIL_CONTACTS("CWRWBLPABDC"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_CREATE_CONTACTS("CWRWBABCC"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_MONEY_REQUEST("CWRWBTCLPABMR"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_TRANSACTIONS_BOOK("CWRWBTCLPABTB"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_TRANSACTIONS_AVAILABLE("CWRWBTCLPABTA"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_CHUNCK_VALUES("CWRWBTCLPABCV"),

    CCP_BITCOIN_LOSS_PROTECTED_WALLET_HOME("CCPBLPWH"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_TRANSACTIONS_SENT("CCPBLPWTS"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_TRANSACTIONS_RECEIVED("CCPBLPWTR"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_REQUEST_RECEIVED("CCPBLPWRR"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_REQUEST_SEND("CCPBLPWRS"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_TRANSACTIONS_SENT_HISTORY("CCPBLPWTSH"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_TRANSACTIONS_RECEIVED_HISTORY("CCPBLPWTRH"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_REQUEST_SENT_HISTORY("CCPBLPWRSH"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_REQUEST_RECEIVED_HISTORY("CCPBLPWRRH"),

    CCP_BITCOIN_LOSS_PROTECTED_WALLET_SEND_FORM_FRAGMENT("CPPBLPWSFF"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_SEND_WALLET_FORM_FRAGMENT("CPPBLPWSWFF"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_REQUEST_FORM_FRAGMENT("CCPLPBWRFF"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_SETTINGS_FRAGMENT("CCPBWSF"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_SETTINGS_FRAGMENT_NOTIFICATIONS("CCPLPBWSFN"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_SETTINGS_FRAGMENT_MAIN_NETWORK("CCPLPBWSFMN"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_ADD_CONNECTION_FRAGMENT("CCPLPBWACF"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_NO_IDENTITY_FRAGMENT("CCPLPBWNIF"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_MNEMONIC_FRAGMENT("CCPLPBWMNF"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_CHUNCK_VALUES_DETAIL_FRAGMENT("CCPLPBWCVDF"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_SEND_ERROR_REPORT_FRAGMENT("CCPLPBWSER"),

    /**
     * LOSS PROTECTED
     */


    /**
     * FERMAT WALLET
     */

    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_SEND("CWRWBTCFABS"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_BALANCE("CWRWBTCFABB"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_RECEIVE("CWRWBTCFABR"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_TRANSACTIONS("CWRWBTCFABT"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_CONTACTS("CWRWBTCFABC"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_DETAIL_CONTACTS("CWRWBFABDC"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_CREATE_CONTACTS("CWRWBTCFABCC"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_MONEY_REQUEST("CWRWBTCFABMR"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_TRANSACTIONS_BOOK("CWRWBTCFABTB"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_TRANSACTIONS_AVAILABLE("CWRWBTCFABTA"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_FERMAT_ALL_BITDUBAI_CHUNCK_VALUES("CWRWBTCFABCV"),

    CCP_BITCOIN_FERMAT_WALLET_HOME("CCPFWH"),
    CCP_BITCOIN_FERMAT_WALLET_TRANSACTIONS_SENT("CCPFWTS"),
    CCP_BITCOIN_FERMAT_WALLET_TRANSACTIONS_RECEIVED("CCPFWTR"),
    CCP_BITCOIN_FERMAT_WALLET_REQUEST_RECEIVED("CCPFWRR"),
    CCP_BITCOIN_FERMAT_WALLET_REQUEST_SEND("CCPFWRS"),
    CCP_BITCOIN_FERMAT_WALLET_TRANSACTIONS_SENT_HISTORY("CCPFWTSH"),
    CCP_BITCOIN_FERMAT_WALLET_TRANSACTIONS_RECEIVED_HISTORY("CCPFWTRH"),
    CCP_BITCOIN_FERMAT_WALLET_REQUEST_SENT_HISTORY("CCPFWRSH"),
    CCP_BITCOIN_FERMAT_WALLET_REQUEST_RECEIVED_HISTORY("CCPFWRRH"),

    CCP_BITCOIN_FERMAT_WALLET_SEND_FORM_FRAGMENT("CPPFWSFF"),
    CCP_BITCOIN_FERMAT_WALLET_SEND_WALLET_FORM_FRAGMENT("CPPFWSWFF"),
    CCP_BITCOIN_FERMAT_WALLET_REQUEST_FORM_FRAGMENT("CCPFWRFF"),
    CCP_BITCOIN_FERMAT_WALLET_SETTINGS_FRAGMENT("CCPFWSF"),
    CCP_BITCOIN_FERMAT_WALLET_SETTINGS_FRAGMENT_NOTIFICATIONS("CCPFWSFN"),
    CCP_BITCOIN_FERMAT_WALLET_SETTINGS_FRAGMENT_MAIN_NETWORK("CCPFWSFMN"),
    CCP_BITCOIN_FERMAT_WALLET_ADD_CONNECTION_FRAGMENT("CCPFWACF"),
    CCP_BITCOIN_FERMAT_WALLET_NO_IDENTITY_FRAGMENT("CCPFWNIF"),
    CCP_BITCOIN_FERMAT_WALLET_MNEMONIC_FRAGMENT("CCPFWMNF"),
    CCP_BITCOIN_FERMAT_WALLET_CHUNCK_VALUES_DETAIL_FRAGMENT("CCFBWCVDF"),
    CCP_BITCOIN_FERMAT_WALLET_SEND_ERROR_REPORT_FRAGMENT("CCPFWSER"),

    /**
     * FERMAT WALLET
     */


    CWP_WALLET_RUNTIME_WALLET_AGE_KIDS_ALL_BITDUBAI_PROFILE("CWRWAKABP"),
    CWP_WALLET_RUNTIME_WALLET_AGE_KIDS_ALL_BITDUBAI_DESKTOP("CWRWAKABD"),
    CWP_WALLET_RUNTIME_WALLET_AGE_KIDS_ALL_BITDUBAI_CONTACTS("CWRWAKABC"),
    CWP_WALLET_RUNTIME_WALLET_AGE_KIDS_ALL_BITDUBAI_COMMUNITY("CWRWAKABCT"),

    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_HOME("CWRWAABH"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_BALANCE("CWRWAABB"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_SEND("CWRWAABS"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_RECEIVE("CWRWAABR"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_SHOPS("CWRWAABSS"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_REFFIL("CWRWAABRF"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_DISCOUNTS("CWRWAABD"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_SHOP_SHOP("CWRWAABSHS"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_SHOP_PRODUCTS("CWRWAABSHP"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_SHOP_REVIEWS("CWRWAABSHR"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_SHOP_CHAT("CWRWAABSHC"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_SHOP_HISTORY("CWRWAABSHH"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_SHOP_MAP("CWRWAABSHM"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_ACCOUNTS_DEBITS("CWRWAABAD"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_ACCOUNT_CREDITS("CWRWAABAC"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_ACCOUNTS_ALL("CWRWAABAA"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_CONTACTS_CHAT("CWRWAABCC"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_CONTACTS("CWRWAABC"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_CONTACTS_SEND("CWRWAABCS"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_CONTACTS_NEW_SEND("CWRWAABCNS"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_CONTACTS_RECEIVE("CWRWAABCR"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_CONTACTS_NEW_RECEIVE("CWRWAABCNR"),
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI_CHAT_TRX("CWRWAABCTX"),
    CWP_WALLET_RUNTIME_ADULTS_ALL_AVAILABLE_BALANCE("CWRAAAB"),

    CWP_WALLET_ADULTS_ALL_REQUESTS_RECEIVED("CWAARR"),
    CWP_WALLET_ADULTS_ALL_REQUESTS_RECEIVED_HISTORY("CWAARRH"),
    CWP_WALLET_ADULTS_ALL_REQUEST_SEND("CWAARS"),
    CWP_WALLET_ADULTS_ALL_SEND_HISTORY("CWAASH"),
    CWP_WALLET_ADULTS_ALL_DAILY_DISCOUNT("CWAADD"),
    CWP_WALLET_ADULTS_ALL_WEEKLY_DISCOUNT("CWAAWD"),
    CWP_WALLET_ADULTS_ALL_MONTHLY_DISCOUNT("CWAAMD"),

    CWP_WALLET_DEVELOPER_TOOL_DATABASE_LIST_FRAGMENT("CWDTDLF"),
    CWP_WALLET_DEVELOPER_TOOL_DATABASE_TABLE_LIST_FRAGMENT("CWDTDTLF"),
    CWP_WALLET_DEVELOPER_TOOL_DATABASE_TABLE_RECORD_LIST_FRAGMENT("CWDTDTRLF"),
    CWP_WALLET_DEVELOPER_TOOL_DATABASE_FRAGMENT("CWDTDF"),
    CWP_WALLET_DEVELOPER_TOOL_LOG_FRAGMENT("CWDTLF"),
    CWP_WALLET_DEVELOPER_TOOL_LOG_LEVEL_1_FRAGMENT("CWDTLL1F"),
    CWP_WALLET_DEVELOPER_TOOL_LOG_LEVEL_2_FRAGMENT("CWDTLL2F"),
    CWP_WALLET_DEVELOPER_TOOL_LOG_LEVEL_3_FRAGMENT("CWDTLL3F"),

//    CWP_SUB_APP_DEVELOPER_DATABASE_TOOLS_DATABASES("CSADDTD"),
//    CWP_SUB_APP_DEVELOPER_DATABASE_TOOLS_TABLES("CSADDTT"),
//    CWP_SUB_APP_DEVELOPER_DATABASE_TOOLS_RECORDS("CSADDTR"),
//    CWP_SUB_APP_DEVELOPER_DATABASE_TOOLS("CSADDT"),
//    CWP_SUB_APP_DEVELOPER_LOG_TOOLS("CSADLT"),
//    CWP_SUB_APP_DEVELOPER_LOG_LEVEL_1_TOOLS("CSADLL1T"),
//    CWP_SUB_APP_DEVELOPER_LOG_LEVEL_2_TOOLS("CSADLL2T"),
//    CWP_SUB_APP_DEVELOPER_LOG_LEVEL_3_TOOLS("CSADLL3T"),

    CWP_WALLET_PUBLISHER_MAIN("CWPM"),

    DAP_WALLET_ASSET_ISSUER_MAIN_ACTIVITY("DWAIMA"),
    DAP_WALLET_ASSET_ISSUER_MAIN_SETTINGS_ACTIVITY("DWAIMSA"),
    DAP_WALLET_ASSET_ISSUER_SETTINGS_MAIN_NETWORK_ACTIVITY("DWAISMNA"),
    DAP_WALLET_ASSET_ISSUER_SETTINGS_NOTIFICATIONS_ACTIVITY("DWAISNA"),
    //    DAP_WALLET_ASSET_ISSUER_HISTORY_ACTIVITY("DWAIHA"),
//    DAP_WALLET_ASSET_ISSUER_STADISTICS_ACTIVITY("DWAISA"),
    DAP_WALLET_ASSET_ISSUER_ASSET_DETAIL("DWAIAD"),
    DAP_WALLET_ASSET_ISSUER_USER_DELIVERY_LIST("DWAIUDL"),
    DAP_WALLET_ASSET_ISSUER_USER_DELIVERY_LIST_HEADER("DWAIUDLH"),
    DAP_WALLET_ASSET_ISSUER_USER_REDEEMED_LIST("DWAIURL"),
    DAP_WALLET_ASSET_ISSUER_ASSET_DELIVERY("DWAIADL"),
    DAP_WALLET_ASSET_ISSUER_ASSET_DELIVERY_TAB_SELECT_USERS("DWAIADTSU"),
    DAP_WALLET_ASSET_ISSUER_USER_APPROPIATE_LIST("DWAIUAL"),
    DAP_WALLET_ASSET_ISSUER_ASSET_DELIVERY_TAB_SELECT_GROUPS("DWAIADTSG"),
    DAP_WALLET_ASSET_ISSUER_ASSET_DELIVERY_TABS("DWAIADT"),

    DAP_WALLET_ASSET_USER_MAIN_ACTIVITY("DWUIMA"),
    DAP_WALLET_ASSET_USER_HISTORY_ACTIVITY("DWAUHA"),
    DAP_WALLET_ASSET_USER_ASSET_DETAIL_TRANSACTIONS("DWAUADT"),
    DAP_WALLET_ASSET_USER_ASSET_DETAIL_RECIEVED_TAB("DWAUADRT"),
    DAP_WALLET_ASSET_USER_ASSET_REDEEM("DWAUAR"),
    DAP_WALLET_ASSET_USER_ASSET_REDEEM_SELECT_REDEEMPOINTS("DWAUARSRP"),
    DAP_WALLET_ASSET_USER_SETTINGS_ACTIVITY("DWAUSA"),
    DAP_WALLET_ASSET_USER_SETTINGS_MAIN_NETWORK("DWAUSMN"),
    DAP_WALLET_ASSET_USER_SETTINGS_NOTIFICATIONS("DWAUSN"),
    DAP_WALLET_ASSET_USER_ASSET_SELL_FRAGMENT("DWAUASF"),
    DAP_WALLET_ASSET_USER_ASSET_SELL_SELECT_USERS_FRAGMENT("DWAUASSUF"),
    DAP_WALLET_ASSET_USER_ASSET_TRANSFER_FRAGMENT("DWAUATF"),
    DAP_WALLET_ASSET_USER_ASSET_TRANSFER_SELECT_USERS_FRAGMENT("DWAUATSUF"),
    DAP_WALLET_ASSET_USER_ASSET_NEGOTIATION_DETAIL_FRAGMENT("DWAUANDF"),

    DAP_WALLET_ASSET_USER_V2_HOME("DWAUH"),
    DAP_WALLET_ASSET_USER_V2_DETAIL("DWAUD"),
    DAP_WALLET_ASSET_USER_V2_REDEEM_POINTS("DWAURP"),

    DAP_WALLET_ASSET_USER_V3_HOME("DWAU3H"),

    DAP_WALLET_REDEEM_POINT_MAIN_ACTIVITY("DWRPMA"),
    DAP_WALLET_REDEEM_POINT_HISTORY_ACTIVITY("DWRPHA"),
    DAP_WALLET_REDEEM_POINT_STADISTICS_ACTIVITY("DWRPSA"),
    DAP_WALLET_REDEEM_POINT_DETAILS_USERS_TAB("DWRPDUT"),
    DAP_WALLET_REDEEM_POINT_DETAILS_TRANSACTIONS_TAB("DWRPDTT"),
    DAP_WALLET_REDEEM_POINT_SETTINGS_MAIN_NETWORK("DWRPSMN"),
    DAP_WALLET_REDEEM_POINT_ASSET_SETTINGS_ACTIVITY("DWRPASA"),
    DAP_WALLET_REDEEM_POINT_ASSET_SETTINGS_NOTIFICATIONS("DWRPASN"),

    DAP_WALLET_REDEEM_POINT_MAIN_PENDING_TAB_FRAGMENT("DWRPMPTF"),
    DAP_WALLET_REDEEM_POINT_MAIN_HISTORY_TAB_FRAGMENT("DWRPMHTF"),
    DAP_WALLET_REDEEM_POINT_USER_DETAIL_FRAGMENT("DWRPUDF"),

    /**
     * WAllet factory
     */
    CWP_WALLET_FACTORY_DEVELOPER_PROJECTS("CWFDP"),
    CWP_WALLET_FACTORY_AVAILABLE_PROJECTS("CWFAP"),

    CWP_WALLET_FACTORY_WIZARD_CREATE_STEP_1("CWFWCS1"),
    CWP_WALLET_FACTORY_WIZARD_CREATE_STEP_2("CWFWCS2"),

    // Crypto Broker Wallet
    CBP_CRYPTO_BROKER_WALLET_OPEN_NEGOTIATIONS_TAB("CBPCBWHAONT"),
    CBP_CRYPTO_BROKER_WALLET_OPEN_CONTRACTS_TAB("CBPCBWHAOCT"),
    CBP_CRYPTO_BROKER_WALLET_MARKET_RATE_STATISTICS("CBPCBWMRS"),
    CBP_CRYPTO_BROKER_WALLET_STOCK_STATISTICS("CBPCBWHASS"),
    CBP_CRYPTO_BROKER_WALLET_OPEN_NEGOTIATION_DETAILS("CBPCBWOND"),
    CBP_CRYPTO_BROKER_WALLET_CLOSE_NEGOTIATION_DETAILS("CBPCBWCND"),
    CBP_CRYPTO_BROKER_WALLET_CLOSE_CONTRACT_DETAILS("CBPCBWCCD"),
    CBP_CRYPTO_BROKER_WALLET_CONTRACTS_HISTORY("CBPCBWCH"),
    CBP_CRYPTO_BROKER_WALLET_EARNINGS("CBPCBWE"),
    CBP_CRYPTO_BROKER_WALLET_SETTINGS("CBPCBWS"),
    CBP_CRYPTO_BROKER_WALLET_SET_IDENTITY("CBPCBWSI"),
    CBP_CRYPTO_BROKER_WALLET_SET_MERCHANDISES("CBPCBWSM"),
    CBP_CRYPTO_BROKER_WALLET_SET_EARNINGS("CBPCBWSE"),
    CBP_CRYPTO_BROKER_WALLET_SET_PROVIDERS("CBPCBWSP"),
    CBP_CRYPTO_BROKER_WALLET_SET_LOCATIONS("CBPCBWSL"),
    CBP_CRYPTO_BROKER_WALLET_SET_BANK_ACCOUNT("CBPCBWSBA"),
    CBP_CRYPTO_BROKER_WALLET_CREATE_NEW_LOCATION_IN_WIZARD("CBPCBWCNLIW"),
    CBP_CRYPTO_BROKER_WALLET_SETTINGS_MY_LOCATIONS("CBPCBWSML"),
    CBP_CRYPTO_BROKER_WALLET_CREATE_NEW_LOCATION_IN_SETTINGS("CBPCBWCNLIS"),
    CBP_CRYPTO_BROKER_WALLET_SETTINGS_BANK_ACCOUNT("CBPCBWSSBA"),
    CBP_CRYPTO_BROKER_WALLET_SETTINGS_STOCK_MERCHANDISES("CBPCBWSSM"),
    CBP_CRYPTO_BROKER_WALLET_SETTINGS_FEE_MANAGEMENT("CBPCBWSFM"),
    CBP_CRYPTO_BROKER_WALLET_OTHER_SETTINGS("CBPCBWOS"),
    CBP_CRYPTO_BROKER_WALLET_CONTRACT_DETAILS("CBPCBWCD"),

    // Crypto Customer Wallet
    CBP_CRYPTO_CUSTOMER_WALLET_OPEN_NEGOTIATIONS_TAB("CBPCCWHAONT"),
    CBP_CRYPTO_CUSTOMER_WALLET_OPEN_CONTRACTS_TAB("CBPCCWHAOCT"),
    CBP_CRYPTO_CUSTOMER_WALLET_MARKET_RATE_STATISTICS("CBPCCWMRS"),
    CBP_CRYPTO_CUSTOMER_WALLET_START_NEGOTIATION("CBPCCWSN"),
    CBP_CRYPTO_CUSTOMER_WALLET_OPEN_NEGOTIATION_DETAILS("CBPCCWOND"),
    CBP_CRYPTO_CUSTOMER_WALLET_OPEN_NEGOTIATION_ADD_NOTE("CBPCCWONAN"),
    CBP_CRYPTO_CUSTOMER_WALLET_CLOSE_NEGOTIATION_DETAILS("CBPCCWCND"),
    CBP_CRYPTO_CUSTOMER_WALLET_CLOSE_CONTRACT_DETAILS("CBPCCWCCD"),
    CBP_CRYPTO_CUSTOMER_WALLET_CONTRACTS_HISTORY("CBPCCWCH"),
    CBP_CRYPTO_CUSTOMER_WALLET_BROKER_LIST("CBPCCWBL"),
    CBP_CRYPTO_CUSTOMER_WALLET_SETTINGS("CBPCCWS"),
    CBP_CRYPTO_CUSTOMER_WALLET_SET_IDENTITY("CBPCCWSI"),
    CBP_CRYPTO_CUSTOMER_WALLET_SET_BITCOIN_WALLET_AND_PROVIDERS("CBPCCWSBWP"),
    CBP_CRYPTO_CUSTOMER_WALLET_SET_LOCATIONS("CBPCCWSL"),
    CBP_CRYPTO_CUSTOMER_WALLET_SET_BANK_ACCOUNT("CBPCCWSBA"),
    CBP_CRYPTO_CUSTOMER_WALLET_CREATE_NEW_LOCATION_IN_WIZARD("CBPCCWCNLW"),
    CBP_CRYPTO_CUSTOMER_WALLET_CREATE_NEW_BANK_ACCOUNT_IN_WIZARD("CBPCCWCNBAW"),
    CBP_CRYPTO_CUSTOMER_WALLET_SETTINGS_MY_LOCATIONS("CBPCCWSML"),
    CBP_CRYPTO_CUSTOMER_WALLET_CREATE_NEW_LOCATION_IN_SETTINGS("CBPCCWCNLIS"),
    CBP_CRYPTO_CUSTOMER_WALLET_SETTINGS_BANK_ACCOUNTS("CBPCCWSBAS"),
    CBP_CRYPTO_CUSTOMER_WALLET_CREATE_NEW_BANK_ACCOUNT_IN_SETTINGS("CBPCCWCNBAIS"),
    CBP_CRYPTO_CUSTOMER_WALLET_SETTINGS_PROVIDERS("CBPCCWP"),
    CBP_CRYPTO_CUSTOMER_WALLET_SETTINGS_MANAGEMENT_FEE("CBPCCWSMF"),
    CBP_CRYPTO_CUSTOMER_WALLET_CONTRACT_DETAILS("CBPCCWCD"),

    // Crypto Broker Identity
    CBP_SUB_APP_CRYPTO_BROKER_IDENTITY_MAIN_FRAGMENT("CBPSACBIMF"),
    CBP_SUB_APP_CRYPTO_BROKER_IDENTITY_IMAGE_CROPPER_FRAGMENT("CBPSACBIICF"),
    CBP_SUB_APP_CRYPTO_BROKER_IDENTITY_CREATE_IDENTITY_FRAGMENT("CBPSACBICIF"),
    CBP_SUB_APP_CRYPTO_BROKER_IDENTITY_EDIT_IDENTITY_FRAGMENT("CBPSACBIEIF"),
    CBP_SUB_APP_CRYPTO_BROKER_IDENTITY_GEOLOCATION_FRAGMENT("CBPSACBIGIF"),

    // Crypto Customer Identity
    CBP_SUB_APP_CRYPTO_CUSTOMER_IDENTITY_MAIN_FRAGMENT("CBPSACCIMF"),
    CBP_SUB_APP_CRYPTO_CUSTOMER_IDENTITY_IMAGE_CROPPER_FRAGMENT("CBPSACCIICF"),
    CBP_SUB_APP_CRYPTO_CUSTOMER_IDENTITY_CREATE_IDENTITY_FRAGMENT("CBPSACCICIF"),
    CBP_SUB_APP_CRYPTO_CUSTOMER_IDENTITY_EDIT_IDENTITY_FRAGMENT("CBPSACCIEIF"),
    CBP_SUB_APP_CRYPTO_CUSTOMER_IDENTITY_GEOLOCATION_FRAGMENT("CBPSACCIGIF"),
    //Bank Money Wallet
    BNK_BANK_MONEY_WALLET_ACCOUNTS_LIST("BNKBMWAL"),
    BNK_BANK_MONEY_WALLET_ACCOUNT_DETAIL("BNKBMWAD"),
    BNK_BANK_MONEY_WALLET_ADD_ACCOUNT("BNKBMWAA"),
    BNK_BANK_MONEY_WALLET_EDIT_ACCOUNT("BNKBMWEA"),
    BNK_BANK_MONEY_WALLET_SETUP("BNKBMWS"),
    BNK_BANK_MONEY_WALLET_TRANSACTION_DETAIL("BNKBMWTD"),

    //TKY Fan Wallet
    TKY_FAN_WALLET_MAIN_ACTIVITY("TKYFWMA"),
    TKY_FAN_WALLET_SONGS_TAB_FRAGMENT("TKYFWSTF"),
    TKY_FAN_WALLET_FOLLOWING_TAB_FRAGMENT("TKYFWFTF"),

    //Cash Money Wallet
    CSH_CASH_MONEY_WALLET_BALANCE_SUMMARY("CSHCMWBS"),
    CSH_CASH_MONEY_WALLET_TRANSACTION_DETAIL("CSHCMWTD"),
    CSH_CASH_MONEY_WALLET_SETUP("CSHCMWS"),

    // CCP Identity
    CCP_SUB_APP_CRYPTO_CUSTOMER_IDENTITY_MAIN_FRAGMENT("CCPSACCIMF"),
    CCP_SUB_APP_CRYPTO_CUSTOMER_IDENTITY_CREATE_IDENTITY_FRAGMENT("CCPSACCICIF"),
    CCP_SUB_APP_INTRA_IDENTITY_GEOLOCATION_IDENTITY("CCPSACCIGI"),

    // DAP Issuer Identity
    DAP_SUB_APP_ASSET_ISSUER_IDENTITY_MAIN_FRAGMENT("DSAAIIMF"),
    DAP_SUB_APP_ASSET_ISSUER_IDENTITY_CREATE_IDENTITY_FRAGMENT("DSAAIICIF"),
    DAP_SUB_APP_ASSET_ISSUER_IDENTITY_GEOLOCATION_FRAGMENT("DSAAIIGF"),

    // DAP User Identity
    DAP_SUB_APP_ASSET_USER_IDENTITY_MAIN_FRAGMENT("DAPSAAUIMF"),
    DAP_SUB_APP_ASSET_USER_IDENTITY_CREATE_IDENTITY_FRAGMENT("DAPSAAUICIF"),
    DAP_SUB_APP_ASSET_USER_IDENTITY_GEOLOCATION_FRAGMENT("DSAAUIGF"),

    // DAP REDEEM POINT IDENTITY
    DAP_SUB_APP_REDEEM_POINT_IDENTITY_MAIN_FRAGMENT("DAPSARPIMF"),
    DAP_SUB_APP_REDEEM_POINT_IDENTITY_CREATE_IDENTITY_FRAGMENT("DAPSARPICIF"),
    DAP_SUB_APP_REDEEM_POINT_IDENTITY_GEOLOCATION_FRAGMENT("DAPSARPIGF"),

    // CCP Community
    CCP_SUB_APP_INTRA_USER_COMMUNITY_FRAGMENT("CCPSAIUCF"),
    CCP_SUB_APP_INTRA_USER_COMMUNITY_CONNECTIONS_FRAGMENT("CCPSAIUCCF"),
    CCP_SUB_APP_INTRA_USER_COMMUNITY_CONNECTION_DETAIL_FRAGMENT("CCPSAIUCCDF"),
    CCP_SUB_APP_INTRA_USER_COMMUNITY_CONNECTION_NOTIFICATIONS_FRAGMENT("CCPSAIUCCNF"),
    CCP_SUB_APP_INTRA_USER_COMMUNITY_CONNECTION_OTHER_PROFILE_FRAGMENT("CCPSAIUCCOPF"),
    CCP_SUB_APP_INTRA_USER_COMMUNITY_CONNECTION_WORLD_FRAGMENT("CCPSAIUCCWF"),
    CCP_SUB_APP_INTRA_USER_COMMUNITY_CONNECTION_FRIEND_LIST_FRAGMENT("CCPSAIUCCFLF"),
    CCP_SUB_APP_INTRA_USER_COMMUNITY_CONNECTION_SETTINGS_FRAGMENTS("CCPSAIUCCSF"),

    // CBP Crypto Broker COMMUNITY .-
    CBP_SUB_APP_CRYPTO_BROKER_COMMUNITY_CONNECTIONS("CBPSACBCCF"),
    CBP_SUB_APP_CRYPTO_BROKER_COMMUNITY_CONNECTION_DETAIL("CBPSACBCCDF"),
    CBP_SUB_APP_CRYPTO_BROKER_COMMUNITY_CONNECTION_NOTIFICATIONS("CBPSACBCCNF"),
    CBP_SUB_APP_CRYPTO_BROKER_COMMUNITY_CONNECTION_OTHER_PROFILE("CBPSACBCCOPF"),
    CBP_SUB_APP_CRYPTO_BROKER_COMMUNITY_CONNECTION_WORLD("CBPSACBCCWF"),
    CBP_SUB_APP_CRYPTO_BROKER_COMMUNITY_CONNECTION_FRIEND_LIST("CBPSACBCCFLF"),

    // CBP Crypto Customer COMMUNITY .-
    CBP_SUB_APP_CRYPTO_CUSTOMER_COMMUNITY_CONNECTIONS("CBPSACCCCF"),
    CBP_SUB_APP_CRYPTO_CUSTOMER_COMMUNITY_CONNECTION_DETAIL("CBPSACCCCDF"),
    CBP_SUB_APP_CRYPTO_CUSTOMER_COMMUNITY_CONNECTION_NOTIFICATIONS("CBPSACCCCNF"),
    CBP_SUB_APP_CRYPTO_CUSTOMER_COMMUNITY_CONNECTION_OTHER_PROFILE("CBPSACCCCOPF"),
    CBP_SUB_APP_CRYPTO_CUSTOMER_COMMUNITY_CONNECTION_WORLD("CBPSACCCCWF"),
    CBP_SUB_APP_CRYPTO_CUSTOMER_COMMUNITY_CONNECTION_FRIEND_LIST("CBPSACCCCFLF"),

    /**
     * Chat
     */
    CHT_CHAT_OPEN_CHATLIST_TAB_FRAGMENT("CHTOCHLTF"),
    CHT_CHAT_OPEN_CONTACTLIST_TAB_FRAGMENT("CHTOCONTLTF"),
    CHT_CHAT_OPEN_CONNECTIONLIST_TAB_FRAGMENT("CHTOCONNTLTF"),
    CHT_CHAT_OPEN_CONTACTLIST_FRAGMENT("CHTOCONLTF"),
    CHT_CHAT_OPEN_MESSAGE_LIST_FRAGMENT("CHTOMLF"),
    CHT_CHAT_OPEN_CHAT_DETAIL_FRAGMENT("CHTOCHDF"),
    CHT_CHAT_OPEN_CONTACT_DETAIL_FRAGMENT("CHTOCODF"),
    CHT_CHAT_EDIT_CONTACT_FRAGMENT("CHTEDCOF"),
    CHT_CHAT_OPEN_CONNECTIONLIST_FRAGMENT("CHTOCONNLTF"),
    CHT_CHAT_OPEN_PROFILELIST_FRAGMENT("CHTOPLF"),
    CHT_CHAT_OPEN_PROFILE_DETAIL_FRAGMENT("CHTOPODF"),
    CHT_CHAT_BROADCAST_WIZARD_TWO_DETAIL("CHTBWTD"),
    CHT_CHAT_BROADCAST_WIZARD_ONE_DETAIL("CHTBWOD"),
    CHT_CHAT_BROADCAST_WIZARD_TWO_SCHEDULED_DETAIL("CHTBWTSD"),
    CHT_CHAT_CREATE_IDENTITY_FRAGMENT("CHTCIF"),
    CHT_CHAT_GEOLOCATION_IDENTITY_FRAGMENT("CHTGIF"),
    CHT_CHAT_OPEN_SEND_ERROR_REPORT_FRAGMENT("CHTOSERF"),
    CHT_SUB_APP_CHAT_COMMUNITY_FRAGMENT("CHTSACCF"),
    CHT_SUB_APP_CHAT_COMMUNITY_CONNECTIONS_FRAGMENT("CHTSACCCF"),
    CHT_SUB_APP_CHAT_COMMUNITY_CONNECTION_DETAIL_FRAGMENT("CHTSACCCDF"),
    CHT_SUB_APP_CHAT_COMMUNITY_CONNECTION_NOTIFICATIONS_FRAGMENT("CHTSACCCNF"),
    CHT_SUB_APP_CHAT_COMMUNITY_CONNECTION_OTHER_PROFILE_FRAGMENT("CHTSACCCOPF"),
    CHT_SUB_APP_CHAT_COMMUNITY_CONNECTION_WORLD_FRAGMENT("CHTSACCCWF"),
    CHT_SUB_APP_CHAT_COMMUNITY_CONNECTION_CONTACTS_LIST_FRAGMENT("CHTSACCCCLF"),
    CHT_SUB_APP_CHAT_COMMUNITY_CONNECTION_SETTINGS_FRAGMENT("CHTSACCCSF"),


    //ART
    ART_SUB_APP_ARTIST_IDENTITY_CREATE_PROFILE("ASAAICP"),
    //ART_WALLET_STORE_ALL_FRAGMENT("AWSAF"),
    ART_SUB_APP_FAN_COMMUNITY_CONNECTIONS("ARTSAFCC"),
    ART_SUB_APP_FAN_COMMUNITY_CONNECTION_DETAIL("ARTSAFCCD"),
    ART_SUB_APP_FAN_COMMUNITY_CONNECTION_FRIEND_LIST("ASAFCCFL"),
    ART_SUB_APP_FAN_COMMUNITY_CONNECTION_NOTIFICATIONS("ASAFCCN"),
    ART_SUB_APP_FAN_COMMUNITY_CONNECTION_OTHER_PROFILE("ASAFCCOP"),
    ART_SUB_APP_FAN_COMMUNITY_CONNECTION_WORLD("ASAFCCW"),
    ART_SUB_APP_FAN_COMMUNITY_LOCAL_IDENTITIES_LIST("ASAFCLIL"),

    ART_SUB_APP_ARTIST_COMMUNITY_CONNECTIONS("ARTSAACC"),
    ART_SUB_APP_ARTIST_COMMUNITY_CONNECTION_DETAIL("ARTSAACCD"),
    ART_SUB_APP_ARTIST_COMMUNITY_CONNECTION_FRIEND_LIST("ASAACCFL"),
    ART_SUB_APP_ARTIST_COMMUNITY_CONNECTION_NOTIFICATIONS("ASAACCN"),
    ART_SUB_APP_ARTIST_COMMUNITY_CONNECTION_OTHER_PROFILE("ASAACCOP"),
    ART_SUB_APP_ARTIST_COMMUNITY_CONNECTION_WORLD("ASAACCW"),
    ART_SUB_APP_ARTIST_COMMUNITY_LOCAL_IDENTITIES_LIST("ASAACLIL"),

    ART_SUB_APP_FAN_IDENTITY_CREATE_IDENTITY_FRAGMENT("ARTSAFICIF"),

    ART_SUB_APP_FAN_IDENTITY_TEST_FRAGMENT("ARTSAFITF"),

    ART_MUSIC_PLAYER_MAIN_ACTIVITY("ARTMPMA"),

    //TKY
    TKY_ARTIST_IDENTITY_HOME("TAIH"),
    TKY_ARTIST_IDENTITY_ACTIVITY_CREATE_PROFILE("TACACP"),
    TKY_SUB_APP_FAN_IDENTITY_CREATE_IDENTITY_FRAGMENT("TKYSUBAPPFANCREATE"),

    DESKTOP_SETTINGS("DS"),
    DESKTOP_APPS_MAIN("DAM"),
    DESKTOP_P2P_MAIN("DP2PM"),
    DESKTOP_SOCIAL_MAIN("DSM"),
    COMMUNITIES_FRAGMENT("CF"),
    DESKTOP_SETTING_IMPORT_KEY("DSIK"),
    DESKTOP_SETTING_EXPORT_KEY("DSEK"),
    DESKTOP_MORE_SETTINGS("DMS"),


    // Welcome wizard
    WELCOME_WIZARD_FIRST_SCREEN_FRAGMENT("WWFISF"),
    WELCOME_WIZARD_SECOND_SCREEN_FRAGMENT("WWSSF"),
    WELCOME_WIZARD_THIRD_SCREEN_FRAGMENT("WWTSF"),
    WELCOME_WIZARD_FOURTH_SCREEN_FRAGMENT("WWFOSF"),;

    private String code;

    Fragments(String code) {
        this.code = code;
    }

    public static Fragments getValueFromString(String code) throws InvalidParameterException {
        for (Fragments fragments : Fragments.values()) {
            if (fragments.code.equals(code)) {
                return fragments;
            }
        }
        return null;

        // throw an IllegalArgumentException or return null
        // throw new IllegalArgumentException("the given number doesn't match any Status.");
        //return null;
    }

    public String getKey() {
        return this.code;
    }

    public String getStringValue() {
        return this.code;
    }

    public String toString() {
        return code;
    }
}
