package com.bitdubai.fermat_api.layer.all_definition.navigation_structure.enums;

/**
 * Created by rodrigo on 2015.07.20..
 */
public enum Wallets {
    CWP_WALLET_RUNTIME_WALLET_AGE_KIDS_ALL_BITDUBAI,
    CWP_WALLET_RUNTIME_WALLET_AGE_TEEN_ALL_BITDUBAI,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI,
    CWP_WALLET_RUNTIME_WALLET_AGE_YOUNG_ALL_BITDUBAI,
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_WALLET_ALL_BITDUBAI;
}
