:numbered:
== Fermat System-wide definitions


=== Identities
NOTE: The *identification system* in Fermat uses a pair of *privat-public keys* generated by asymmetric cryptography methods, to identify any component of the system, a *plug-in*, an *intraActor*, a *deviceUser*, a *network service*, a *communication channel*, etc... + 
Some *identities* are created only ONCE FOR ALL (when installing Fermat), others ONCE for the entire session, and others are _dynamically_ asigned when a process starts to run (they survive the entire process' life cycle). There are some keys that are the most ephimere because the are _renewed_ each time the process changes its *status*.

One of main concept's inside Fermat's design is the distinction of different _levels of identities_ depending on the realm where this _identities_ are valid. These creates a hierarchical structure of _identities_ and the _credentials_ associated with it.
The *real person* who wants to use Fermat, has to install the software in at least one *device* and then let it run.
At this stage, the real person gets an initial identity a *device user*, which is automatically given by Fermat and is transparent to him (needs not to worry about it and/or decide anything about it). This is valid for all the functions that happend INSIDE the device, and it contains certain information about himself/herself that is known to the device operating system, and which is stored in the device's memory/hard drive. + 
Then, to start using Fermat, he/she is prompted by the software to choose a *master identity* within Fermat. That means to choose an _username_ (or _ alias_) and a _password_ to be recognized as a *Fermat system user*, and has certain _profile_ associated with it. 
Then, the *real person* turned into a *user* of Fermat, chooses to run any of Fermat's products, and this takes him to play certain role within a specific Fermat Platform available, what turns him/she into an *actor* of the platform. As such, he/she must define an _actor identity_  within THIS platform, which is INDEPENDENT to any other created in other platforms, although it is related to the Fermat system-wide *master identity*. + 
This *actor* has the possibility to define a set of multiple _wallet identities_ to operate within each wallet, defining a _profile_ for each one, choosing the profile concepts to include (name, picture, occupation, etc) and the content of them, having total control of which information he shares with the world. + 
For the external world, each _wallet identity_ appears to be a "different person" and there are NO RELATIONS between them. However, for the *Fermat User* owning his *master identity*, all his *actor identities* and *wallet identities* are interconnected.

.Example of hierarchichal identities 
* *master identity* eg. John Doe, Colorado Springs, CO, USA.
** *actor identity 1* eg. "John cryptobroker"
*** *wallet identity1* eg. "The Commander Venezuela Cryptobroker"
*** *wallet identity1* eg. "Colorado Exchange Cryptobroker"
** *actor identity 2* eg. "Alice Brenda Smith cryptocurrency owner"
*** *wallet identity1* eg. "Alice bitcoin wallet user"
*** *wallet identity2* eg. "A.B.S. Bitcoin Loss Protected user"
** *actor identity3* eg. "Aunt Betty Muffins asset issuer"

=== Actors
Cryptocurrencies live in a public and distributed ledger, the *blockchain*, in a decentralized p2p network (spread in every network node). + 
They are held and stored by their owners in specific applications called *wallets* living in a certain device which has access to the corresponding cryptonetwork. +
*Wallets* store the owner's _privat key_ and the corresponding _public key_ to unlock the cryptocurrency amount of a given *transaction*. + 
For a *transaction* to take place, a *crypto address* is needed to identify both the sender of the value as well as the receiver. + 
*Crypto addresses* are generated by the wallet derived from the _privat/public key_ pair of the wallet's owner. +
Although *wallets* are similar in relationship to their basic functionalities, the _natural segmentation of the world population_ and the specific demand of every segment requires to be taken into account when designing *wallets*. +
Fermat defines different system *actors* to identify the specific needs and level of abstraction required to each actor, and consequently being able to design Fermat's products with the appropiated orientation.

////
:numbered!:
==== Overview of Fermat's products and their actors
[horizontal]
 Wallet FACTORY ::   -> for marketers to re-brand any of the already existing segment specific wallets in a few steps (without the need to deal with the source code of the base wallet selected!)
Fermat Wallet PUBLISHER ::  -> for wallet designers/marketing agency to offer their rebranded Wallet to the world !
Wallet STORE ::  -> the store where available wallets live, ready to be adopted !
BITCOIN Wallet :: -> for those devoted "BTC-only" users!
BITCOIN LOSS PROTECTED Wallet -> for conservative user's caring about never selling under the purchase price ! (preserving value!)
CRYPTO COMMODITY MONEY Wallet :: ->
DISCOUNT Wallet :: -> for discount and bonus chasers! ( recommend selling when price gets convinient, and shows it as a " discount" !)*
BANK NOTES  Wallet :: -> for those wanting to visualize their investment in "real money traditional bank notes" of their usual fiat/currency ( rest on Fermat, we do the "dirty work" with all the crypto stuff!)*
SHOP Wallet :: -> *for shop owners who accept cryptocurrency in payment of their products !*
BRAND Wallet :: -> *for brands owners who accept cryptocurrency in their retailers network.*
RETAILER Wallet :: -> *for* 
ASSET ISSUER Wallet :: -> for company or brand that issues a Digital Assets to offer to their customers*
ASSET USER  Wallet :: -> for *the customer who accepts/obtain some Digital Assets according to his interests*
REDEEM POINT Wallet :: -> for the place/shop/person that exchanges the Asset for a certain service or product (redeems it).*
VOUCHER Wallet :: -> for 
COUPON Wallet :: -> for 
DISCOUNT Wallet :: -> for 
CRYPTO BROKER Wallet :: -> for persons/organizations whose business activity is exchanging cryptocurrency for fiat-money
CRYPTO BROKER'S USER Wallet ::  ->  for customers of the cryptobroker
CRYPTO WHOLESALER Wallet :: -> for organizations owing a certain large amount of crypto-credit to sell through a distribution chain.
CRYPTO DISTRIBUTOR Wallet :: -> for those who form the next level in the distribution, buying to wholesalers and re-selling to Top Up Point
TOP UP POINT Wallet :: -> for shops/organizations/persons who transfer crypto-credit in exchange for fiat-money (receives money - gives crypto)
CASH OUT POINT Wallet :: -> for shops/organizations/persons who gives out money in exchange for a transfer of crypto (receive crypto - gives money)
////












