package com.bitdubai.wallet_platform_api.layer._2_platform_service.event_manager;

/**
 * Created by ciencias on 24.01.15.
 */
public enum EventType {

    USER_CREATED, 
    USER_LOGGED_IN, 
    USER_LOGGED_OUT,
    INTRA_USER_CONTACT_CREATED,

    WALLET_CREATED, 
    WALLET_WENT_ONLINE, 
    WALLET_INSTALLED, 
    BEGUN_WALLET_INSTALLATION, 
    WALLET_UNINSTALLED, 
    WALLET_CLOSED, 
    WALLET_OPENED,
    WALLET_RESOURCES_INSTALLED,
    NAVIGATION_STRUCTURE_UPDATED,
    MONEY_RECEIVED, FINISHED_WALLET_INSTALLATION

}
