package com.bitdubai.fermat_api.layer._2_platform_service.event_manager;

/**
 * Created by ciencias on 24.01.15.
 */
public enum EventSource {
    USER_DEVICE_USER_PLUGIN,
    CRYPTO_NETWORK_BITCOIN_PLUGIN,
    COMMUNICATION_CLOUD_PLUGIN,
    NETWORK_SERVICE_INTRA_USER_PLUGIN,
    NETWORK_SERVICE_WALLET_RESOURCES_PLUGIN,
    NETWORK_SERVICE_WALLET_COMMUNITY_PLUGIN,
    MIDDLEWARE_APP_RUNTIME_PLUGIN,
    MIDDLEWARE_WALLET_CONTACTS_PLUGIN,
    MIDDLEWARE_WALLET_PLUGIN,
    MODULE_WALLET_MANAGER_PLUGIN,
    NETWORK_SERVICE_MONEY_PLUGIN
    
    }
