[[flujo-general-BitDubai-V1]]

= Flujo General de la Plataform DAP


El actor ISSUER procede a crear el Asset donde colocara la informacion relevante:

  * Tienen un Emisor, que es alguno de los actores del sistema.
  * Tienen una fecha de expiración. (aunque en algunos casos puede ser que no expiren nunca)
  * Tienen uno o mas elementos multi-media (imagen, sonido, video, animación, etc.) destinados a
    representar ante el usuario final dicho asset.
  * Son de un determinado tipo.
  * Pueden ser redimido.
  * Tienen una lista de condiciones que dependen de su tipo. (Las entienden cualquier wallet que maneje
    ese tipo de Assets)
  * Son de un determinado sub-tipo.
  * Tienen una lista de condiciones que dependen de su sub-tipo. (Las entienden cualquier wallet que
    maneje ese sub-tipo de Assets)
  * Tienen una lista de condiciones que dependen de su emisor. (Solo las entienden las wallets del emisor)

El Issuer determinara en que momento el Asset estara disponible para su envio o publicacion a las Wallets instaladas en otros dispositivos y de manera asincrona comenzara
la instalacion del Asset, siempre y cuando se haya validado algunas informacion tecnica del Asset, por ejemplo que no haya caducado, el actor User, debera de una manera aceptar
el Asset recibido.

Deberiamos de buscar la manera de saber el codigo de la billetera para proceder a enviar el asset.

Interacion y Flujo de pluggin, subapp, explicacion.

= Flujo Desarrollo

Quizas para una primera version, la plataforma tenga definido el contrato de características de los tipos y subtipos de Assests soportados.
Por ejemplo, para el asset tipo voucher, existirán x condiciones que el issuer debe especificar.

El issuer define propiedades generales de assets, y dependiendo del tipo de asset, las condiciones que aplican. --> Resultado: Digital Asset.

Una vez finalizado y cerrado el asset, se genera la Genesis Transaction.

= Consumo de Assests

 1) La branded wallet específica de un tipo de Asset (por ej. vourcher), al iniciarse la plataforma registra en el cloud server su existencia con su direccion de Bitcoin,
 para que el issuer (en forma automática) envíe el asset al usuario que tiene instalada la wallet.

 2) Proceso de redimir el asset: una posibilidad es que en el local de MacDonalds, el usuario tenga que escanera un código QR con la dirección bitcoins a donde enviar los bitcoins del asset.
 Un proceso background se encargará de generar la transacción bitcoin y marcar el asset como consumido.

 3) La dirección del issuer hacia donde enviar el dinero al redimirlo, puede estar incluida dentro de la metadata del asset. Esto quizas sea mandatorio para recuperar el dinero
 de assets expirados no redimidos. (Si es que el contrato exige recuperar el dinero).


 = Consultas principales:

 La Asset Vault no solamente guardará los bitcoins de los assets, sino tambien el Digital Asset (es decir, el contrato, la definición, imagenes, etc. y el hash del asset).



