== Primer borrador

== Digital Assets Platform

= DAP



Introducción

La Plataforma de Digital Assets dentro de Fermat permite sentar los cimientos sobre los cuales se
construirán otras funcionalides que administrarán ciertos tipos de assets más específicos para cada
industria. En particular, por ejemplo, los assets asociados al márketing con
todo su manejo específico se construirán en Fermat MKT.


Digital Asset

En Fermat definimos un Fermat Digital Asset como un asset emitido por algun actor del sistema,
el cual está registrado en alguna crypto network, y que su propiedad puede ser transferida a otros
actores del sistema incluyendo a extra users.

En una primera etapa, nos vamos a focalizar en los mecanismos para emitir y transferir assets
solo dentro de Fermat por su importancia táctica, dejando la interoperatividad con usuarios
externos para el futuro.


Características Principales

En general, todos los digital assets comparten las siguientes características:

    Tienen un Emisor, que es alguno de los actores del sistema.

    Tienen una fecha de expiración. (aunque en algunos casos puede ser que no expiren nunca)

    Tienen uno o mas elementos multi-media (imagen, sonido, video, animación, etc.) destinados
    a representar ante el usuario final dicho asset.

    Son de un determinado tipo.

    Tienen una lista de condiciones que dependen de su tipo. (Las entienden cualquier wallet que
    maneje ese tipo de Assets)

    Son de un determinado sub-tipo.

    Tienen una lista de condiciones que dependen de su sub-tipo. (Las entienden cualquier wallet
    que maneje ese sub-tipo de Assets)

    Tienen una lista de condiciones que dependen de su emisor. (Solo las entienden las wallets del emisor)


A la lista de condiciones que aplican sobre un asset, le vamos a llamar Asset Contract.
A toda la información que representa al asset, le vamos a llamar Digital Asset.

Ejemplos de tipos y sub-tipos de Assets

    Voucher
        Tourism voucher : permite tomar un servicio en una fecha y lugar predeterminado.
        Mobile phone voucher : los venden los retailers para recargar teléfonos móviles.

    Coupon

    Discount

    Company Shares


Como funcionan?

En términos generales, un Actor emite un Asset registrando un hash del Digital Asset en alguna
blockchain. En otras palabras transfiere una cierta cantidad de crypto currency a una dirección
que llamaremos Asset Genesis Address. La transacción donde se emite el asset le llamaremos
Genesis Transaction. Al monto con el que se inicializa el asset le llamaremos Genesis Amount.

Luego transfiere dicho asset a algún otro actor de la plataforma realizando dos cosas a la vez:

    Transfiriendo el Genesis Amount a una dirección del destinatario.
    Transfiriendo el Digital Asset como meta-data de dicha transacción al actor destinatario
    firmado por la identidad del emisor. Como parte de la meta-data se transfiere el hash de la
    Genesis Transaction.

El destinatario puede validar que el Asset recibido es válido si se cumplen las siguientes condiciones:

    Todavía se cumplen las condiciones del Asset Contract.
    El hash del Digital Asset está en la transacción indicada como Genesis Transaction.
    La Genesis Transaction es un ancestro de la transacción crypto recibida.
    Ninguna transacción crypto desde la Genesis Transaction hasta la transacción recibida ha
    inflado la cantidad de assets.

En general el destinatario podrá hacer lo siguiente con el asset recibido:

    Descartar el Digital Asset y quedarse con la crypto currency.
    Simplemente tenerlo (En algunos casos los assets devengan dividendos o intereses).
    Volver a transferirlo a otro actor del sistema (si el Asset Contract lo permite).
    Venderselo a otro actor del sistema (si el Asset Contract lo permite).
    Venderlo en un mercado p2p para ese tipo de Assets (si el Asset Contract lo permite).
    Redimirlo (si el tipo de Asset lo permite) (si el Asset Contract lo permite).

Cada una de las acciones anteriores tiene su propios desafíos y forma de resolverse.

Wallet del Emisor

Fermat determina, por cuestiones tácticas que para recibir assets de un determinado emisor,
uno debe tener la wallet de dicho emisor que soporte ese tipo / sub-tipo de assets. Esta condición
es favorable para que las empresas emitan assets como manera de expandir su base wallets instaladas.


En general para validar si un emisor de assets se corresponde con una entidad de la vida real,
DAP se basa en el supuesto de que el usuario validó al momento de instalar la wallet del emisor
que esta se corresponda con la entidad de la vida real indicada.

Encima de DAP

Lo anterior es común para todo tipo de assets. A partir de allí, lo que suceda
dependerá del tipo / sub-tipo y de las condicioes embebidas en el Asset Contract.


Implementación

Vamos a analizar lo que necesitamos implementar para poder construir la base del manejo de assets
en Fermat.


Vaults

Para empezar vamos a necesitar implementar una crypto vault para almacenar los assets,
independiente de la vault actual, porque no se puede mezclar la crypto currency con los assets sin
riesgo de que los assets se destruyan si se toman como simplemente crypto currency.

De aquí se desprende lo siguientes componentes en la capa CRY / Crypto Vault:

    Bitcoin Currency : Deriva del plugin actual Bitcoin y servirá para manejar bitcoin como moneda.
    Bitcoin Assets : Es un nuevo plugin que sirve para mantener en él los assets basados en bitcoin.

Crypto Network

Mientras que en la capa CRY / Crypto Network, el plugin Bitcoin debe hacer lo siguiente:

    Tomar una transacción creada en cualquiera de las dos Vaults y enviarla a la red Bitcoin.
    Anunciar la llegada de Crypto para que sea procesada la transacción.
    (este plugin no sabe si es una transacción monetaria o de assets)


Crypto Router

Por otro lado en la capa CRY / Crypto Router, el plugin IncomingCrypto se le debe hacer un
upgrade para que distinga las transacciones que se correspondan con assets y dispare el evento
que corresponda a una IncomingAsset para que sea procesada por el plugin correspondiente.

Antes de disparar el evento, el Crypto Router debe notificar a la vault que corresponda para que 
esta actualice su estado y sepa cuanto y donde llegó. Esa información le será crítica para luego 
poder armar nuevas transacciones.


Incoming Asset Intra Actor

Todos los assets recibidos que fueron enviados por otros actores de Fermat exepto un Extra User 
pasan por este plugin. El mismo se encarga de sincronizar la transacción crypto con la meta-data y 
validar que el Asset recibido es en general bueno y válido. No llega a procesar las condiciones 
relaciondas al tipo de Asset, al sub-tipo ni condiciones relacionadas con el issuer. 
Se limita a verificar que las condiciones definidas por el protocolo Fermat de transferencia de 
Assets se haya cumplido.


Outgoing Asset Intra Actor

Este plugin se encarga de coordinar la transacción de transferencia de propiedad de un asset 
hacia un Intra Actor. Es el que le solicita a la Asset Vault que arme la transacción crypto y 
la entrega a la Crypto Network. Adicional a esto envía la meta-data necesaria para completar la 
transacción.


Asset Wallets

En Fermat, Asset Wallets son aquellas wallets que son capaces de entender el concepto de 
Fermat Digital Asset. Teóricamente, una asset wallet entiende de Assets de una manera genérica, 
sin poder llegar a las condiciones específicas que dependen del tipo o sub-tipo de Asset.


Branded Wallets

Llamamos en Fermat Branded Wallets a las wallets creadas por una marca de la vida real, 
como por ejemplo Mc Donalds. Pudieramos afirmar también que una Branded Wallet casi siempre va a 
ser a su vez una Aseet Wallet para uno o mas tipos y sub-tipos de Assets. En particular para los 
tipos y sub-tipos de Assets que la marca en cuestion emite a sus usuarios.





MKT

Fermat Marketing


Introducción

Esta columna de funcionalidad incorpora a la plataforma el conocimiento de como operar digtal assets 
relacionados al mundo del marketing, como por ejemplo: vouchers, cupones, descuentos, etc.


Voucher

En markeging, un voucher es un bono que puede ser redimido de una determinada manera, ante ciertas 
condiciones y a cambio de cosas específicas y que tiene un cierto valor monetario.


Por ahora nos vamos a limitar a este tipo de asset, hasta implementarlo completamente, y 
crear toda la infraestructura necesaria para que funcione. Luego incorporaremos distintos sub-tipos 
y otros tipos de assets usados en la industria del marketing.

