= Wallet Statistics

Este plug-in escucha el evento de la Wallet Store sub App que anuncia que una wallet se está
instalando y envía información al wallet statistic del developer informando la actualización.
Como receptor lanza un evento que dice que un usuario

Posiblemente se informen otros datos del usuario que instaló la wallet como por ejemplo la localización del mismo.
También registrará la calificación que el usuario le de a la wallet, comentarios, etc.


== A futuro

Sería iteresante que este (u otro) plugin registre diversas estadísticas del uso de una wallet. Entre otras:

* Gastos (montos y tipos de gastos)
* Ingresos

Estos datos no tienen por qué ser compartidos con otros nework services si el usuario no lo desea.
Más aún, como una idea futura este plugin se podría usar para que el usuario controle la información
que desea compartir y su vez darle la opción de que él pueda vender esta información a empresas
interesadas en sus datos. Actualmente muchos sitios hacen esto sin darle ningún rédito al usuario,
aquí buscaríamos que el usuario sea no sólo quien controle su información sino también quien obtenga un pago por su aporte.
