package com.bitdubai.reference_niche_wallet.loss_protected_wallet.fragment_factory;

import com.bitdubai.fermat_android_api.layer.definition.wallet.enums.FermatFragmentsEnumType;

/**
 * Created by Matias Furszyfer on 2015.07.22..
 */
public enum LossProtectedFragmentsEnumType implements FermatFragmentsEnumType<LossProtectedFragmentsEnumType> {


    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_SEND("CWRWBTCLPABS"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_BALANCE("CWRWBTCLPABB"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_RECEIVE("CWRWBTCLPABR"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_TRANSACTIONS("CWRWBTCLPABT"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_CONTACTS("CWRWBTCLPABC"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_DETAIL_CONTACTS("CWRWBLPABDC"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_CREATE_CONTACTS("CWRWBABCC"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_MONEY_REQUEST("CWRWBTCLPABMR"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_TRANSACTIONS_BOOK("CWRWBTCLPABTB"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_TRANSACTIONS_AVAILABLE("CWRWBTCLPABTA"),
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_LOSS_PROTECTED_ALL_BITDUBAI_CHUNCK_VALUES("CWRWBTCLPABCV"),

    CCP_BITCOIN_LOSS_PROTECTED_WALLET_HOME("CCPBLPWH"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_TRANSACTIONS_SENT("CCPBLPWTS"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_TRANSACTIONS_RECEIVED("CCPBLPWTR"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_REQUEST_RECEIVED("CCPBLPWRR"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_REQUEST_SEND("CCPBLPWRS"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_TRANSACTIONS_SENT_HISTORY("CCPBLPWTSH"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_TRANSACTIONS_RECEIVED_HISTORY("CCPBLPWTRH"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_REQUEST_SENT_HISTORY("CCPBLPWRSH"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_REQUEST_RECEIVED_HISTORY("CCPBLPWRRH"),

    CCP_BITCOIN_LOSS_PROTECTED_WALLET_SEND_FORM_FRAGMENT("CPPBLPWSFF"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_SEND_WALLET_FORM_FRAGMENT("CPPBLPWSWFF"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_REQUEST_FORM_FRAGMENT("CCPLPBWRFF"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_SETTINGS_FRAGMENT("CCPBWSF"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_SETTINGS_FRAGMENT_NOTIFICATIONS("CCPLPBWSFN"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_SETTINGS_FRAGMENT_MAIN_NETWORK("CCPLPBWSFMN"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_ADD_CONNECTION_FRAGMENT("CCPLPBWACF"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_NO_IDENTITY_FRAGMENT("CCPLPBWNIF"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_MNEMONIC_FRAGMENT("CCPLPBWMNF"),
    CCP_BITCOIN_LOSS_PROTECTED_WALLET_CHUNCK_VALUES_DETAIL_FRAGMENT("CCPLPBWCVDF");


    private String key;

    LossProtectedFragmentsEnumType(String key) {
        this.key = key;
    }

    public static LossProtectedFragmentsEnumType getValue(String name) {
        for (LossProtectedFragmentsEnumType fragments : LossProtectedFragmentsEnumType.values()) {
            if (fragments.key.equals(name)) {
                return fragments;
            }
        }
        // throw an IllegalArgumentException or return null
        // throw new IllegalArgumentException("the given number doesn't match any Status.");
        //TODO Return null method - OJO: only informative for visual aid during debug - remove if it bothers
        return null;
    }

    @Override
    public String getKey() {
        return this.key;
    }

    @Override
    public String toString() {
        return key;
    }


}
