package com.bitdubai.fermat_api.layer._15_middleware.app_runtime.enums;

/**
 * Created by ciencias on 2/14/15.
 */
public enum Wallets {

    CWP_WALLET_RUNTIME_WALLET_AGE_KIDS_ALL_BITDUBAI,
    CWP_WALLET_RUNTIME_WALLET_AGE_TEEN_ALL_BITDUBAI,
    CWP_WALLET_RUNTIME_WALLET_ADULTS_ALL_BITDUBAI,
    CWP_WALLET_RUNTIME_WALLET_AGE_YOUNG_ALL_BITDUBAI,
    CWP_WALLET_RUNTIME_WALLET_BITCOIN_WALLET_ALL_BITDUBAI;
}
